[package]
name = "snav-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "starnav"
path = "src/lib.rs"

[[bin]]
name = "snav"
path = "src/smoke_test.rs"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
