// Decompiled code dump generated by Code Dumper (Callers/Callees/Refs)
// Start Functions:
//   - 0x14033C3D0 (sub_14033C3D0)
//   - 0x14033C4B0 (sub_14033C4B0)
//   - 0x141376910 (sub_141376910)
//   - 0x1425D7A00 (sub_1425D7A00)
//   - 0x1425D7FC0 (sub_1425D7FC0)
//   - 0x1425DF270 (sub_1425DF270)
//   - 0x1425E1A70 (sub_1425E1A70)
//   - 0x142C05B30 (sub_142C05B30)
//   - 0x142DA6300 (sub_142DA6300)
//   - 0x142DAF9B0 (sub_142DAF9B0)
//   - 0x1449E0F70 (sub_1449E0F70)
// Caller Depth: 1
// Callee/Ref Depth: 1
// Total Functions Found: 62
// ------------------------------------------------------------

// --- Function: sub_14033A210 (0x14033A210) ---
__int64 __fastcall sub_14033A210(__int64 a1)
{
  return sub_140520C50(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_14033A210 (0x14033A210) ---

// --- Function: sub_14033A220 (0x14033A220) ---
__int64 __fastcall sub_14033A220(__int64 a1)
{
  return sub_140520C80(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_14033A220 (0x14033A220) ---

// --- Function: sub_14033A230 (0x14033A230) ---
__int64 __fastcall sub_14033A230(__int64 a1)
{
  return sub_140520C90(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_14033A230 (0x14033A230) ---

// --- Function: sub_14033A260 (0x14033A260) ---
__int64 __fastcall sub_14033A260(__int64 a1)
{
  return sub_140520D50(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_14033A260 (0x14033A260) ---

// --- Function: sub_14033C3D0 (0x14033C3D0) ---
void __fastcall sub_14033C3D0(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **, __int64 (__fastcall *)()); // rsi
  __int64 Size_1; // rax
  size_t Size; // rbx
  _DWORD *v5; // rax
  unsigned int v6; // eax
  void *p_CLocIdentifier; // [rsp+30h] [rbp+8h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **, __int64 (__fastcall *)()))(*(_QWORD *)a1 + 16LL);
  p_CLocIdentifier = (char *)&qword_149808ABC + 4;
  Size_1 = -1;
  do
  {
    ++Size_1;
  }
  while ( aClocidentifier[Size_1] );
  Size = (int)Size_1;
  if ( (_DWORD)Size_1 )
  {
    v5 = (_DWORD *)sub_14739AFC0((int)Size_1 + 9LL, 0);
    p_CLocIdentifier = v5 + 2;
    *v5 = Size;
    v5[1] = Size;
    *((_BYTE *)p_CLocIdentifier + Size) = 0;
    if ( p_CLocIdentifier != "CLocIdentifier" )
    {
      memcpy(p_CLocIdentifier, "CLocIdentifier", Size);
    }
  }
  v6 = sub_14033D800();
  v2(a1, v6, &p_CLocIdentifier, sub_14033F310);
  if ( *((int *)p_CLocIdentifier - 1) > 0 )
  {
    sub_14739AF10((char *)p_CLocIdentifier - 8);
  }
}

// --- End Function: sub_14033C3D0 (0x14033C3D0) ---

// --- Function: sub_14033C4B0 (0x14033C4B0) ---
_QWORD *__fastcall sub_14033C4B0(__int64 a1)
{
  _QWORD *result; // rax
  __int64 Size_1; // rax
  unsigned __int8 *v4; // rbx
  size_t Size; // rdi
  _DWORD *v6; // rax
  const void **v7; // [rsp+20h] [rbp-28h] BYREF
  char v8; // [rsp+28h] [rbp-20h]
  int *v9; // [rsp+50h] [rbp+8h] BYREF

  v9 = &dword_14980BD54;
  result = (_QWORD *)sub_140354880(a1 + 8, (__int64)&v7, (unsigned __int8 *)&v9);
  if ( v8 )
  {
    Size_1 = -1;
    v4 = (unsigned __int8 *)&qword_149808ABC + 4;
    do
    {
      ++Size_1;
    }
    while ( aClocidentifier[Size_1] );
    Size = (int)Size_1;
    if ( (_DWORD)Size_1 )
    {
      v6 = (_DWORD *)sub_14739AFC0((int)Size_1 + 9LL, 0);
      v4 = (unsigned __int8 *)(v6 + 2);
      *v6 = Size;
      v6[1] = Size;
      *((_BYTE *)v6 + Size + 8) = 0;
      if ( v6 + 2 != (_DWORD *)"CLocIdentifier" )
      {
        memcpy(v6 + 2, "CLocIdentifier", Size);
      }
    }
    sub_140527E00((int *)a1, v4);
    if ( *((int *)v4 - 1) > 0 )
    {
      sub_14739AF10(v4 - 8);
    }
    sub_140527D70((_DWORD *)a1, "m_sIdentifier");
    sub_140527DD0(a1);
    return sub_1403E0CA0((_QWORD *)(a1 + 8), &v9, v7);
  }
  return result;
}

// --- End Function: sub_14033C4B0 (0x14033C4B0) ---

// --- Function: sub_14033D560 (0x14033D560) ---
__int64 sub_14033D560()
{
  __int64 result; // rax
  unsigned int v1; // edi
  _QWORD **v2; // rcx
  _QWORD *v3; // rdx
  _QWORD *v4; // rbx
  _DWORD v5[4]; // [rsp+20h] [rbp-58h] BYREF
  const void *v6[2]; // [rsp+30h] [rbp-48h] BYREF
  __int128 v7; // [rsp+40h] [rbp-38h] BYREF
  __int64 v8; // [rsp+50h] [rbp-28h]

  result = (unsigned int)dword_14980BD40;
  if ( !dword_14980BD40 )
  {
    sub_140526EF0((__int64)v5);
    sub_14033BB50((__int64)v5, (__int64)&p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
    v1 = v5[0];
    if ( (_QWORD)v7 )
    {
      sub_14039EFB0((__int64)&v7, (const void *)v7, (v8 - v7) & 0xFFFFFFFFFFFFFFF8uLL);
      v7 = 0;
      v8 = 0;
    }
    v2 = (_QWORD **)v6[0];
    **((_QWORD **)v6[0] + 1) = 0;
    v3 = *v2;
    if ( *v2 )
    {
      do
      {
        v4 = (_QWORD *)*v3;
        sub_14039EFB0((__int64)v6, v3, 0x18u);
        v3 = v4;
      }
      while ( v4 );
    }
    sub_14039EFB0((__int64)v6, v6[0], 0x18u);
    result = v1;
    dword_14980BD40 = v1;
  }
  return result;
}

// --- End Function: sub_14033D560 (0x14033D560) ---

// --- Function: sub_14033D640 (0x14033D640) ---
__int64 sub_14033D640()
{
  __int64 result; // rax
  unsigned int v1; // edi
  _QWORD **v2; // rcx
  _QWORD *v3; // rdx
  _QWORD *v4; // rbx
  _DWORD v5[4]; // [rsp+20h] [rbp-58h] BYREF
  const void *v6[2]; // [rsp+30h] [rbp-48h] BYREF
  __int128 v7; // [rsp+40h] [rbp-38h] BYREF
  __int64 v8; // [rsp+50h] [rbp-28h]

  result = (unsigned int)dword_14980BD4C;
  if ( !dword_14980BD4C )
  {
    sub_140526EF0((__int64)v5);
    sub_14033BD70(v5, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
    v1 = v5[0];
    if ( (_QWORD)v7 )
    {
      sub_14039EFB0((__int64)&v7, (const void *)v7, (v8 - v7) & 0xFFFFFFFFFFFFFFF8uLL);
      v7 = 0;
      v8 = 0;
    }
    v2 = (_QWORD **)v6[0];
    **((_QWORD **)v6[0] + 1) = 0;
    v3 = *v2;
    if ( *v2 )
    {
      do
      {
        v4 = (_QWORD *)*v3;
        sub_14039EFB0((__int64)v6, v3, 0x18u);
        v3 = v4;
      }
      while ( v4 );
    }
    sub_14039EFB0((__int64)v6, v6[0], 0x18u);
    result = v1;
    dword_14980BD4C = v1;
  }
  return result;
}

// --- End Function: sub_14033D640 (0x14033D640) ---

// --- Function: sub_14033D800 (0x14033D800) ---
__int64 sub_14033D800()
{
  __int64 result; // rax
  unsigned int v1; // edi
  _QWORD **v2; // rcx
  _QWORD *v3; // rdx
  _QWORD *v4; // rbx
  _DWORD v5[4]; // [rsp+20h] [rbp-58h] BYREF
  const void *v6[2]; // [rsp+30h] [rbp-48h] BYREF
  __int128 v7; // [rsp+40h] [rbp-38h] BYREF
  __int64 v8; // [rsp+50h] [rbp-28h]

  result = (unsigned int)dword_14980BD54;
  if ( !dword_14980BD54 )
  {
    sub_140526EF0((__int64)v5);
    sub_14033C4B0(v5, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
    v1 = v5[0];
    if ( (_QWORD)v7 )
    {
      sub_14039EFB0((__int64)&v7, (const void *)v7, (v8 - v7) & 0xFFFFFFFFFFFFFFF8uLL);
      v7 = 0;
      v8 = 0;
    }
    v2 = (_QWORD **)v6[0];
    **((_QWORD **)v6[0] + 1) = 0;
    v3 = *v2;
    if ( *v2 )
    {
      do
      {
        v4 = (_QWORD *)*v3;
        sub_14039EFB0((__int64)v6, v3, 0x18u);
        v3 = v4;
      }
      while ( v4 );
    }
    sub_14039EFB0((__int64)v6, v6[0], 0x18u);
    result = v1;
    dword_14980BD54 = v1;
  }
  return result;
}

// --- End Function: sub_14033D800 (0x14033D800) ---

// --- Function: sub_14033F310 (0x14033F310) ---
__int64 __fastcall sub_14033F310(__int64 a1)
{
  return sub_14033C7E0(a1, "m_sIdentifier", 0);
}

// --- End Function: sub_14033F310 (0x14033F310) ---

// --- Function: sub_140354880 (0x140354880) ---
__int64 __fastcall sub_140354880(__int64 a1, __int64 a2, unsigned __int8 *a3)
{
  _QWORD *v5; // r15
  __int64 v6; // rax
  unsigned __int64 v7; // rdx
  __int64 v8; // rcx
  __int64 v9; // rdx
  _QWORD *v10; // rbx
  _QWORD *v11; // r13
  _QWORD *v12; // rbp
  _QWORD *v13; // rcx
  _QWORD *v15; // r12
  _QWORD *v16; // rdi
  __int64 v17; // rcx
  float v18; // xmm1_4
  float v19; // kr00_4
  unsigned __int64 n8_2; // rdx
  float v21; // xmm0_4
  float v22; // kr00_4
  unsigned __int64 v25; // rcx
  unsigned __int64 n8_1; // rax
  unsigned __int64 n8; // rcx
  unsigned __int64 v28; // r8
  __int64 v29; // rdx
  _QWORD *v30; // rax
  _QWORD *v31; // rdx
  __int64 v32; // rcx
  _QWORD *v33; // rdx
  __int64 v34; // rcx
  __int64 v35; // rax
  _QWORD *v36; // r8
  unsigned __int64 v37; // [rsp+70h] [rbp+8h]

  v5 = *(_QWORD **)(a1 + 8);
  v6 = a1 + 8;
  v7 = (0x100000001B3LL
      * (a3[7]
       ^ (0x100000001B3LL
        * (a3[6]
         ^ (0x100000001B3LL
          * (a3[5]
           ^ (0x100000001B3LL
            * (a3[4]
             ^ (0x100000001B3LL
              * (a3[3]
               ^ (0x100000001B3LL
                * (a3[2] ^ (0x100000001B3LL * (a3[1] ^ (0x100000001B3LL * (*a3 ^ 0xCBF29CE484222325uLL))))))))))))))))
     & *(_QWORD *)(a1 + 48);
  v37 = 0x100000001B3LL
      * (a3[7]
       ^ (0x100000001B3LL
        * (a3[6]
         ^ (0x100000001B3LL
          * (a3[5]
           ^ (0x100000001B3LL
            * (a3[4]
             ^ (0x100000001B3LL
              * (a3[3]
               ^ (0x100000001B3LL
                * (a3[2] ^ (0x100000001B3LL * (a3[1] ^ (0x100000001B3LL * (*a3 ^ 0xCBF29CE484222325uLL)))))))))))))));
  v8 = *(_QWORD *)(a1 + 24);
  v9 = 2 * v7;
  v10 = *(_QWORD **)(v8 + 8 * v9 + 8);
  if ( v10 == v5 )
  {
    v10 = v5;
    v11 = (_QWORD *)v6;
    v12 = v5;
  }
  else
  {
    v13 = *(_QWORD **)(v8 + 8 * v9);
    if ( *(_QWORD *)a3 == v10[2] )
    {
LABEL_6:
      *(_QWORD *)a2 = v10;
      *(_BYTE *)(a2 + 8) = 0;
      return a2;
    }
    while ( v10 != v13 )
    {
      v10 = (_QWORD *)v10[1];
      if ( *(_QWORD *)a3 == v10[2] )
      {
        goto LABEL_6;
      }
    }
    v5 = v10;
    v11 = (_QWORD *)(a1 + 8);
    v12 = v10;
    v6 = a1 + 8;
  }
  v15 = (_QWORD *)(a1 + 48);
  if ( *(_QWORD *)(a1 + 16) == 0xAAAAAAAAAAAAAAALL )
  {
    std::_Xlength_error("unordered_map/set too long");
  }
  v16 = (_QWORD *)sub_14038E0B0(v6, 0x18u);
  v16[2] = *(_QWORD *)a3;
  v17 = *(_QWORD *)(a1 + 16) + 1LL;
  if ( v17 < 0 )
  {
    v19 = (float)(v17 & 1 | ((unsigned __int64)v17 >> 1));
    v18 = v19 + v19;
  }
  else
  {
    v18 = (float)v17;
  }
  n8_2 = *(_QWORD *)(a1 + 56);
  if ( (n8_2 & 0x8000000000000000uLL) != 0LL )
  {
    v22 = (float)(*(_QWORD *)(a1 + 56) & 1LL | (n8_2 >> 1));
    v21 = v22 + v22;
  }
  else
  {
    v21 = (float)(__int64)n8_2;
  }
  if ( *(float *)a1 >= (float)(v18 / v21) )
  {
    v28 = v37;
  }
  else
  {
    _XMM1 = 0;
    __asm { vroundss xmm1, xmm1, xmm0, 2 }
    v25 = 0;
    if ( *(float *)&_XMM1 >= 9.223372e18 )
    {
      *(float *)&_XMM1 = *(float *)&_XMM1 - 9.223372e18;
      if ( *(float *)&_XMM1 < 9.223372e18 )
      {
        v25 = 0x8000000000000000uLL;
      }
    }
    n8_1 = v25 + (unsigned int)(int)*(float *)&_XMM1;
    n8 = 8;
    if ( n8_1 > 8 )
    {
      n8 = n8_1;
    }
    if ( n8_2 < n8 )
    {
      if ( n8_2 >= 0x200 || (n8_2 *= 8LL, n8_2 < n8) )
      {
        n8_2 = n8;
      }
    }
    sub_1403DBCD0(a1, n8_2);
    v28 = v37;
    v29 = *(_QWORD *)(a1 + 24);
    v10 = *(_QWORD **)(a1 + 8);
    v30 = *(_QWORD **)(v29 + 16 * (v37 & *(_QWORD *)(a1 + 48)) + 8);
    if ( v30 != v10 )
    {
      v31 = *(_QWORD **)(v29 + 16 * (v37 & *(_QWORD *)(a1 + 48)));
      v32 = v16[2];
      if ( v32 != v30[2] )
      {
        while ( 1 )
        {
          v10 = v30;
          if ( v30 == v31 )
          {
            break;
          }
          v30 = (_QWORD *)v30[1];
          if ( v32 == v30[2] )
          {
            goto LABEL_30;
          }
        }
        v15 = (_QWORD *)(a1 + 48);
        v11 = (_QWORD *)(a1 + 8);
        v12 = v30;
        v5 = v30;
        goto LABEL_34;
      }
LABEL_30:
      v10 = (_QWORD *)*v30;
    }
    v15 = (_QWORD *)(a1 + 48);
    v12 = v10;
    v11 = (_QWORD *)(a1 + 8);
    v5 = v10;
  }
LABEL_34:
  v33 = (_QWORD *)v10[1];
  ++*(_QWORD *)(a1 + 16);
  *v16 = v5;
  v16[1] = v33;
  *v33 = v16;
  v10[1] = v16;
  v34 = *(_QWORD *)(a1 + 24);
  v35 = 2 * (v28 & *v15);
  v36 = *(_QWORD **)(v34 + 16 * (v28 & *v15));
  if ( v36 == (_QWORD *)*v11 )
  {
    *(_QWORD *)(v34 + 8 * v35) = v16;
    goto LABEL_39;
  }
  if ( v36 != v12 )
  {
    if ( *(_QWORD **)(v34 + 8 * v35 + 8) != v33 )
    {
LABEL_40:
      *(_QWORD *)a2 = v16;
      *(_BYTE *)(a2 + 8) = 1;
      return a2;
    }
LABEL_39:
    *(_QWORD *)(v34 + 8 * v35 + 8) = v16;
    goto LABEL_40;
  }
  *(_QWORD *)(v34 + 8 * v35) = v16;
  *(_QWORD *)a2 = v16;
  *(_BYTE *)(a2 + 8) = 1;
  return a2;
}

// --- End Function: sub_140354880 (0x140354880) ---

// --- Function: CreateStringObjectFromString (0x140357920) ---
// Creates a managed string object from a null-terminated C-style string.
// Allocates memory to hold metadata (length, capacity) and the string data. The
// returned pointer points to the string data, with metadata stored immediately
// before it.  Memory Layout: `[DWORD length] [DWORD capacity] [char data...] [char
// '\0']`  @param ppStringObjectData Output parameter; receives the pointer to the
// string data within the newly created object. @param pszInputString The null-
// terminated C-style string to copy. @return Returns the `ppStringObjectData`
// pointer.
void **__fastcall CreateStringObjectFromString(void **ppStringObjectData, _BYTE *pszInputString)
{
  __int64 inputStringLength; // rbx
  _DWORD *pAllocatedBuffer; // rax

  *ppStringObjectData = (char *)&qword_149808ABC + 4;
  if ( !pszInputString )
  {
    return ppStringObjectData;
  }
  inputStringLength = -1;
  do
  {
    ++inputStringLength;
  }
  while ( pszInputString[inputStringLength] );
  if ( (_DWORD)inputStringLength )
  {
    pAllocatedBuffer = (_DWORD *)sub_14739AFC0((int)inputStringLength + 9LL, 0);
    *ppStringObjectData = pAllocatedBuffer + 2;
    *pAllocatedBuffer = inputStringLength;
    pAllocatedBuffer[1] = inputStringLength;
    *((_BYTE *)*ppStringObjectData + (int)inputStringLength) = 0;
    if ( *ppStringObjectData != pszInputString )
    {
      memcpy(*ppStringObjectData, pszInputString, (int)inputStringLength);
    }
  }
  return ppStringObjectData;
}

// --- End Function: CreateStringObjectFromString (0x140357920) ---

// --- Function: DestroyStringObject (0x14036D270) ---
// Deallocates the memory buffer associated with a string object created by
// `CreateStringObjectFromString`.  It accesses metadata stored 8 bytes before the
// provided data pointer to get the allocation base pointer required by the
// deallocation function `sub_14739AF10`.  @param ppStringObjectData Pointer to the
// variable holding the pointer to the string object's data.
void __fastcall DestroyStringObject(_QWORD *ppStringObjectData)
{
  int *pStringMetadata; // rcx

  pStringMetadata = (int *)(*ppStringObjectData - 8LL);
  if ( pStringMetadata[1] > 0 )
  {
    sub_14739AF10(pStringMetadata);
  }
}

// --- End Function: DestroyStringObject (0x14036D270) ---

// --- Function: sub_14039EFB0 (0x14039EFB0) ---
void __fastcall sub_14039EFB0(__int64 a1, const void *a2, unsigned __int64 a3)
{
  __int64 v5; // rax
  unsigned __int64 v6; // rcx
  unsigned __int64 v7; // rbx
  unsigned __int64 v8; // r10
  unsigned __int64 v9; // rcx
  unsigned __int64 n0x40; // rcx
  unsigned __int64 v11; // rcx

  v5 = sub_1403AF4C0();
  v6 = *(_QWORD *)v5;
  if ( *(_QWORD *)v5 && (unsigned __int64)a2 >= v6 && (unsigned __int64)a2 < v6 + *(unsigned int *)(v5 + 32) )
  {
    v7 = ((unsigned __int64)a2 - v6) >> 8;
    v8 = (a3 >> 8) + v7 + ((_BYTE)a3 != 0);
    v9 = v8;
    if ( v8 >= (v7 & 0xFFFFFFFFFFFFFFC0uLL) + 64 )
    {
      v9 = (v7 & 0xFFFFFFFFFFFFFFC0uLL) + 64;
    }
    n0x40 = v9 - v7;
    if ( (v7 & 0x3F) != 0 || n0x40 < 0x40 )
    {
      *(_QWORD *)(v5 + 8 * (v7 >> 6) + 40) &= ~(((1LL << n0x40) - 1) << (v7 & 0x3F));
      v7 = (v7 & 0xFFFFFFFFFFFFFFC0uLL) + 64;
    }
    for ( ; v7 + 64 <= (v8 & 0xFFFFFFFFFFFFFFC0uLL); *(_QWORD *)(v5 + 8 * (v11 >> 6) + 40) = 0 )
    {
      v11 = v7;
      v7 += 64LL;
    }
    if ( v7 < v8 )
    {
      *(_QWORD *)(v5 + 8 * (v7 >> 6) + 40) &= ~((1LL << ((__int64)v8 % 64)) - 1);
    }
  }
  else
  {
    sub_14739AF10(a2);
  }
}

// --- End Function: sub_14039EFB0 (0x14039EFB0) ---

// --- Function: sub_1403E0CA0 (0x1403E0CA0) ---
_QWORD *__fastcall sub_1403E0CA0(_QWORD *a1, _QWORD *a2, const void **a3)
{
  const void **v6; // r8
  const void **v7; // rcx
  const void *v8; // rcx
  _QWORD *v9; // rbx

  v6 = (const void **)(a1[3]
                     + 16
                     * ((0x100000001B3LL
                       * (*((unsigned __int8 *)a3 + 23)
                        ^ (0x100000001B3LL
                         * (*((unsigned __int8 *)a3 + 22)
                          ^ (0x100000001B3LL
                           * (*((unsigned __int8 *)a3 + 21)
                            ^ (0x100000001B3LL
                             * (*((unsigned __int8 *)a3 + 20)
                              ^ (0x100000001B3LL
                               * (*((unsigned __int8 *)a3 + 19)
                                ^ (0x100000001B3LL
                                 * (*((unsigned __int8 *)a3 + 18)
                                  ^ (0x100000001B3LL
                                   * (*((unsigned __int8 *)a3 + 17)
                                    ^ (0x100000001B3LL * (*((unsigned __int8 *)a3 + 16) ^ 0xCBF29CE484222325uLL))))))))))))))))
                      & a1[6]));
  v7 = (const void **)*v6;
  if ( v6[1] == a3 )
  {
    if ( v7 == a3 )
    {
      v8 = (const void *)a1[1];
      *v6 = v8;
    }
    else
    {
      v8 = a3[1];
    }
    v6[1] = v8;
  }
  else if ( v7 == a3 )
  {
    *v6 = *a3;
  }
  v9 = *a3;
  --a1[2];
  *(_QWORD *)a3[1] = v9;
  v9[1] = a3[1];
  sub_14039EFB0((__int64)(a1 + 1), a3, 0x18u);
  *a2 = v9;
  return a2;
}

// --- End Function: sub_1403E0CA0 (0x1403E0CA0) ---

// --- Function: sub_140420D70 (0x140420D70) ---
__int64 __fastcall sub_140420D70(__int64 a1)
{
  return sub_140520AE0(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_140420D70 (0x140420D70) ---

// --- Function: sub_140420D90 (0x140420D90) ---
__int64 __fastcall sub_140420D90(__int64 a1)
{
  return sub_140335900(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_140420D90 (0x140420D90) ---

// --- Function: sub_140420FA0 (0x140420FA0) ---
__int64 __fastcall sub_140420FA0(__int64 a1)
{
  return sub_140520C60(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_140420FA0 (0x140420FA0) ---

// --- Function: sub_140420FB0 (0x140420FB0) ---
__int64 __fastcall sub_140420FB0(__int64 a1)
{
  return sub_140520CB0(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_140420FB0 (0x140420FB0) ---

// --- Function: sub_140520B40 (0x140520B40) ---
void __fastcall sub_140520B40(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **); // rbx
  unsigned int v3; // eax
  void *v4; // [rsp+30h] [rbp+8h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **))(*(_QWORD *)a1 + 104LL);
  CreateStringObjectFromString(&v4, "f32");
  v3 = sub_140523F70();
  v2(a1, v3, &v4);
  DestroyStringObject(&v4);
}

// --- End Function: sub_140520B40 (0x140520B40) ---

// --- Function: sub_140521C60 (0x140521C60) ---
__int64 __fastcall sub_140521C60(__int64 a1)
{
  return sub_140522CE0(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_140521C60 (0x140521C60) ---

// --- Function: sub_140523D40 (0x140523D40) ---
__int64 sub_140523D40()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  const char *p_uint8; // rcx
  unsigned __int8 n117; // al
  unsigned int v4; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v5[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_149814F84;
  if ( !dword_149814F84 )
  {
    sub_140526EF0((__int64)&v4);
    v1 = v4;
    p_uint8 = "uint8";
    n117 = 117;
    do
    {
      ++p_uint8;
      v1 = 16777619 * (v1 ^ n117);
      n117 = *p_uint8;
    }
    while ( *p_uint8 );
    v4 = v1;
    sub_14036D6E0(v5);
    result = v1;
    dword_149814F84 = v1;
  }
  return result;
}

// --- End Function: sub_140523D40 (0x140523D40) ---

// --- Function: sub_140523E90 (0x140523E90) ---
__int64 sub_140523E90()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  const char *p_int32; // rcx
  unsigned __int8 n105; // al
  unsigned int v4; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v5[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_149814F9C;
  if ( !dword_149814F9C )
  {
    sub_140526EF0((__int64)&v4);
    v1 = v4;
    p_int32 = "int32";
    n105 = 105;
    do
    {
      ++p_int32;
      v1 = 16777619 * (v1 ^ n105);
      n105 = *p_int32;
    }
    while ( *p_int32 );
    v4 = v1;
    sub_14036D6E0(v5);
    result = v1;
    dword_149814F9C = v1;
  }
  return result;
}

// --- End Function: sub_140523E90 (0x140523E90) ---

// --- Function: sub_140523F70 (0x140523F70) ---
__int64 sub_140523F70()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  const char *p_f32; // rcx
  unsigned __int8 n102; // al
  unsigned int v4; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v5[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_149814FA4;
  if ( !dword_149814FA4 )
  {
    sub_140526EF0((__int64)&v4);
    v1 = v4;
    p_f32 = "f32";
    n102 = 102;
    do
    {
      ++p_f32;
      v1 = 16777619 * (v1 ^ n102);
      n102 = *p_f32;
    }
    while ( *p_f32 );
    v4 = v1;
    sub_14036D6E0(v5);
    result = v1;
    dword_149814FA4 = v1;
  }
  return result;
}

// --- End Function: sub_140523F70 (0x140523F70) ---

// --- Function: sub_140524250 (0x140524250) ---
__int64 sub_140524250()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  unsigned int v2; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v3[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_149814FB4;
  if ( !dword_149814FB4 )
  {
    sub_140526EF0((__int64)&v2);
    sub_140522DF0(&v2, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
    v1 = v2;
    sub_14036D6E0(v3);
    result = v1;
    dword_149814FB4 = v1;
  }
  return result;
}

// --- End Function: sub_140524250 (0x140524250) ---

// --- Function: sub_140524310 (0x140524310) ---
__int64 sub_140524310()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  const char *p_String; // rcx
  unsigned __int8 n83; // al
  unsigned int v4; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v5[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_149814FD8;
  if ( !dword_149814FD8 )
  {
    sub_140526EF0((__int64)&v4);
    v1 = v4;
    p_String = "String";
    n83 = 83;
    do
    {
      ++p_String;
      v1 = 16777619 * (v1 ^ n83);
      n83 = *p_String;
    }
    while ( *p_String );
    v4 = v1;
    sub_14036D6E0(v5);
    result = v1;
    dword_149814FD8 = v1;
  }
  return result;
}

// --- End Function: sub_140524310 (0x140524310) ---

// --- Function: sub_1405243F0 (0x1405243F0) ---
__int64 sub_1405243F0()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  unsigned int v2; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v3[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_149814E4C;
  if ( !dword_149814E4C )
  {
    sub_140526EF0((__int64)&v2);
    sub_140424460(&v2, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
    v1 = v2;
    sub_14036D6E0(v3);
    result = v1;
    dword_149814E4C = v1;
  }
  return result;
}

// --- End Function: sub_1405243F0 (0x1405243F0) ---

// --- Function: sub_140524450 (0x140524450) ---
__int64 sub_140524450()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  unsigned int v2; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v3[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_149814FC8;
  if ( !dword_149814FC8 )
  {
    sub_140526EF0((__int64)&v2);
    sub_140523560(&v2, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
    v1 = v2;
    sub_14036D6E0(v3);
    result = v1;
    dword_149814FC8 = v1;
  }
  return result;
}

// --- End Function: sub_140524450 (0x140524450) ---

// --- Function: sub_1405244B0 (0x1405244B0) ---
__int64 sub_1405244B0()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  unsigned int v2; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v3[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_14980C038;
  if ( !dword_14980C038 )
  {
    sub_140526EF0((__int64)&v2);
    sub_14033C5C0(&v2, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
    v1 = v2;
    sub_14036D6E0(v3);
    result = v1;
    dword_14980C038 = v1;
  }
  return result;
}

// --- End Function: sub_1405244B0 (0x1405244B0) ---

// --- Function: sub_140524510 (0x140524510) ---
__int64 sub_140524510()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  unsigned int v2; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v3[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_14980C034;
  if ( !dword_14980C034 )
  {
    sub_140526EF0((__int64)&v2);
    sub_14033C6D0(&v2, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
    v1 = v2;
    sub_14036D6E0(v3);
    result = v1;
    dword_14980C034 = v1;
  }
  return result;
}

// --- End Function: sub_140524510 (0x140524510) ---

// --- Function: sub_1405245D0 (0x1405245D0) ---
__int64 sub_1405245D0()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  const char *p_int64; // rcx
  unsigned __int8 n105; // al
  unsigned int v4; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v5[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_149814FA0;
  if ( !dword_149814FA0 )
  {
    sub_140526EF0((__int64)&v4);
    v1 = v4;
    p_int64 = "int64";
    n105 = 105;
    do
    {
      ++p_int64;
      v1 = 16777619 * (v1 ^ n105);
      n105 = *p_int64;
    }
    while ( *p_int64 );
    v4 = v1;
    sub_14036D6E0(v5);
    result = v1;
    dword_149814FA0 = v1;
  }
  return result;
}

// --- End Function: sub_1405245D0 (0x1405245D0) ---

// --- Function: sub_1405246B0 (0x1405246B0) ---
__int64 sub_1405246B0()
{
  __int64 result; // rax
  unsigned int v1; // ebx
  const char *p_bool; // rcx
  unsigned __int8 n98; // al
  unsigned int v4; // [rsp+20h] [rbp-58h] BYREF
  _BYTE v5[72]; // [rsp+28h] [rbp-50h] BYREF

  result = (unsigned int)dword_149814FB0;
  if ( !dword_149814FB0 )
  {
    sub_140526EF0((__int64)&v4);
    v1 = v4;
    p_bool = "bool";
    n98 = 98;
    do
    {
      ++p_bool;
      v1 = 16777619 * (v1 ^ n98);
      n98 = *p_bool;
    }
    while ( *p_bool );
    v4 = v1;
    sub_14036D6E0(v5);
    result = v1;
    dword_149814FB0 = v1;
  }
  return result;
}

// --- End Function: sub_1405246B0 (0x1405246B0) ---

// --- Function: sub_140526EF0 (0x140526EF0) ---
__int64 __fastcall sub_140526EF0(__int64 a1)
{
  _QWORD *v2; // rax
  __int64 v3; // rbx
  __int64 v4; // rax
  const void *v5; // rdx
  _QWORD *v6; // rdi
  __int64 v7; // r8
  _QWORD *v8; // rax

  *(_DWORD *)a1 = -2128831035;
  *(_DWORD *)(a1 + 8) = 0;
  *(_QWORD *)(a1 + 16) = 0;
  *(_QWORD *)(a1 + 24) = 0;
  v2 = (_QWORD *)sub_14038E0B0(a1 + 16, 0x18u);
  *v2 = v2;
  v2[1] = v2;
  *(_QWORD *)(a1 + 16) = v2;
  *(_QWORD *)(a1 + 32) = 0;
  *(_QWORD *)(a1 + 40) = 0;
  *(_QWORD *)(a1 + 48) = 0;
  *(_QWORD *)(a1 + 56) = 7;
  *(_QWORD *)(a1 + 64) = 8;
  *(_DWORD *)(a1 + 8) = 1065353216;
  v3 = *(_QWORD *)(a1 + 16);
  v4 = sub_14038E0B0(a1 + 32, 0x80u);
  v5 = *(const void **)(a1 + 32);
  v6 = (_QWORD *)v4;
  v7 = (__int64)(*(_QWORD *)(a1 + 48) - (_QWORD)v5) >> 3;
  if ( v7 )
  {
    sub_14039EFB0(a1 + 32, v5, 8 * v7);
  }
  v8 = v6 + 16;
  *(_QWORD *)(a1 + 32) = v6;
  *(_QWORD *)(a1 + 40) = v6 + 16;
  *(_QWORD *)(a1 + 48) = v6 + 16;
  do
  {
    *v6++ = v3;
  }
  while ( v6 != v8 );
  return a1;
}

// --- End Function: sub_140526EF0 (0x140526EF0) ---

// --- Function: sub_140527BC0 (0x140527BC0) ---
const char *__fastcall sub_140527BC0(_DWORD *a1)
{
  const char *p_Dictionary; // rax
  unsigned __int8 n68; // dl

  p_Dictionary = "Dictionary";
  n68 = 68;
  do
  {
    ++p_Dictionary;
    *a1 = 16777619 * (*a1 ^ n68);
    n68 = *p_Dictionary;
  }
  while ( *p_Dictionary );
  return p_Dictionary;
}

// --- End Function: sub_140527BC0 (0x140527BC0) ---

// --- Function: sub_140527D70 (0x140527D70) ---
__int64 __fastcall sub_140527D70(_DWORD *a1, unsigned __int8 *a2)
{
  __int64 result; // rax

  for ( result = *a2; (_BYTE)result; result = *a2 )
  {
    ++a2;
    *a1 = 16777619 * (*a1 ^ (unsigned __int8)result);
  }
  return result;
}

// --- End Function: sub_140527D70 (0x140527D70) ---

// --- Function: sub_140527DD0 (0x140527DD0) ---
const char *__fastcall sub_140527DD0(_DWORD *a1)
{
  const char *p_String; // rax
  unsigned __int8 n83; // dl

  p_String = "String";
  n83 = 83;
  do
  {
    ++p_String;
    *a1 = 16777619 * (*a1 ^ n83);
    n83 = *p_String;
  }
  while ( *p_String );
  return p_String;
}

// --- End Function: sub_140527DD0 (0x140527DD0) ---

// --- Function: sub_140527E00 (0x140527E00) ---
__int64 __fastcall sub_140527E00(int *a1, unsigned __int8 *a2)
{
  const char *p_Struct; // r9
  unsigned __int8 n83; // al
  int v4; // r8d
  __int64 result; // rax

  p_Struct = "Struct";
  n83 = 83;
  do
  {
    ++p_Struct;
    v4 = 16777619 * (*a1 ^ n83);
    *a1 = v4;
    n83 = *p_Struct;
  }
  while ( *p_Struct );
  for ( result = *a2; (_BYTE)result; result = *a2 )
  {
    ++a2;
    v4 = 16777619 * (v4 ^ (unsigned __int8)result);
    *a1 = v4;
  }
  return result;
}

// --- End Function: sub_140527E00 (0x140527E00) ---

// --- Function: sub_140529140 (0x140529140) ---
__int64 __fastcall sub_140529140(_DWORD *a1)
{
  const char *p_uint32; // rdx
  __int64 uint32; // rax

  p_uint32 = "uint32";
  LOBYTE(uint32) = 117;
  do
  {
    ++p_uint32;
    *a1 = 16777619 * (*a1 ^ (unsigned __int8)uint32);
    uint32 = *(unsigned __int8 *)p_uint32;
  }
  while ( (_BYTE)uint32 );
  return uint32;
}

// --- End Function: sub_140529140 (0x140529140) ---

// --- Function: sub_1405291D0 (0x1405291D0) ---
__int64 __fastcall sub_1405291D0(_DWORD *a1)
{
  const char *p_int64; // rdx
  __int64 int64; // rax

  p_int64 = "int64";
  LOBYTE(int64) = 105;
  do
  {
    ++p_int64;
    *a1 = 16777619 * (*a1 ^ (unsigned __int8)int64);
    int64 = *(unsigned __int8 *)p_int64;
  }
  while ( (_BYTE)int64 );
  return int64;
}

// --- End Function: sub_1405291D0 (0x1405291D0) ---

// --- Function: sub_14056D1B0 (0x14056D1B0) ---
void __fastcall sub_14056D1B0(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **, __int64 (__fastcall *)()); // rbx
  unsigned int v3; // eax
  void *v4; // [rsp+30h] [rbp+8h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **, __int64 (__fastcall *)()))(*(_QWORD *)a1 + 16LL);
  CreateStringObjectFromString(&v4, "SInventoryId");
  v3 = sub_14033D640();
  v2(a1, v3, &v4, sub_14033F010);
  DestroyStringObject(&v4);
}

// --- End Function: sub_14056D1B0 (0x14056D1B0) ---

// --- Function: sub_140CC93E0 (0x140CC93E0) ---
__int64 __fastcall sub_140CC93E0(__int64 a1)
{
  return sub_140520AB0(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_140CC93E0 (0x140CC93E0) ---

// --- Function: sub_1411B9200 (0x1411B9200) ---
void __fastcall sub_1411B9200(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **, void *, __int64); // rbx
  unsigned int v3; // eax
  void *v4; // [rsp+40h] [rbp+8h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **, void *, __int64))(*(_QWORD *)a1 + 96LL);
  CreateStringObjectFromString(&v4, "EItemSubType");
  v3 = sub_1411C08C0();
  v2(a1, v3, &v4, &unk_149633960, 149);
  DestroyStringObject(&v4);
}

// --- End Function: sub_1411B9200 (0x1411B9200) ---

// --- Function: sub_1411B9260 (0x1411B9260) ---
void __fastcall sub_1411B9260(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **, void *, __int64); // rbx
  unsigned int v3; // eax
  void *v4; // [rsp+40h] [rbp+8h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **, void *, __int64))(*(_QWORD *)a1 + 96LL);
  CreateStringObjectFromString(&v4, "EItemType");
  v3 = sub_1411C09C0();
  v2(a1, v3, &v4, &unk_149632DD0, 185);
  DestroyStringObject(&v4);
}

// --- End Function: sub_1411B9260 (0x1411B9260) ---

// --- Function: sub_1411C08C0 (0x1411C08C0) ---
__int64 sub_1411C08C0()
{
  __int64 result; // rax
  unsigned int v1; // edi
  _QWORD **v2; // rcx
  _QWORD *v3; // rdx
  _QWORD *v4; // rbx
  _DWORD v5[4]; // [rsp+20h] [rbp-58h] BYREF
  const void *v6[2]; // [rsp+30h] [rbp-48h] BYREF
  __int128 v7; // [rsp+40h] [rbp-38h] BYREF
  __int64 v8; // [rsp+50h] [rbp-28h]
  void *v9; // [rsp+80h] [rbp+8h] BYREF

  result = (unsigned int)dword_14998CD1C;
  if ( !dword_14998CD1C )
  {
    sub_140526EF0((__int64)v5);
    CreateStringObjectFromString(&v9, "EItemSubType");
    sub_140527BF0(v5, v9, 149, &unk_149633960);
    DestroyStringObject(&v9);
    v1 = v5[0];
    if ( (_QWORD)v7 )
    {
      sub_14039EFB0((__int64)&v7, (const void *)v7, (v8 - v7) & 0xFFFFFFFFFFFFFFF8uLL);
      v7 = 0;
      v8 = 0;
    }
    v2 = (_QWORD **)v6[0];
    **((_QWORD **)v6[0] + 1) = 0;
    v3 = *v2;
    if ( *v2 )
    {
      do
      {
        v4 = (_QWORD *)*v3;
        sub_14039EFB0((__int64)v6, v3, 0x18u);
        v3 = v4;
      }
      while ( v4 );
    }
    sub_14039EFB0((__int64)v6, v6[0], 0x18u);
    result = v1;
    dword_14998CD1C = v1;
  }
  return result;
}

// --- End Function: sub_1411C08C0 (0x1411C08C0) ---

// --- Function: sub_1411C09C0 (0x1411C09C0) ---
__int64 sub_1411C09C0()
{
  __int64 result; // rax
  unsigned int v1; // edi
  _QWORD **v2; // rcx
  _QWORD *v3; // rdx
  _QWORD *v4; // rbx
  _DWORD v5[4]; // [rsp+20h] [rbp-58h] BYREF
  const void *v6[2]; // [rsp+30h] [rbp-48h] BYREF
  __int128 v7; // [rsp+40h] [rbp-38h] BYREF
  __int64 v8; // [rsp+50h] [rbp-28h]
  void *v9; // [rsp+80h] [rbp+8h] BYREF

  result = (unsigned int)dword_14998CD18;
  if ( !dword_14998CD18 )
  {
    sub_140526EF0((__int64)v5);
    CreateStringObjectFromString(&v9, "EItemType");
    sub_140527BF0(v5, v9, 185, &unk_149632DD0);
    DestroyStringObject(&v9);
    v1 = v5[0];
    if ( (_QWORD)v7 )
    {
      sub_14039EFB0((__int64)&v7, (const void *)v7, (v8 - v7) & 0xFFFFFFFFFFFFFFF8uLL);
      v7 = 0;
      v8 = 0;
    }
    v2 = (_QWORD **)v6[0];
    **((_QWORD **)v6[0] + 1) = 0;
    v3 = *v2;
    if ( *v2 )
    {
      do
      {
        v4 = (_QWORD *)*v3;
        sub_14039EFB0((__int64)v6, v3, 0x18u);
        v3 = v4;
      }
      while ( v4 );
    }
    sub_14039EFB0((__int64)v6, v6[0], 0x18u);
    result = v1;
    dword_14998CD18 = v1;
  }
  return result;
}

// --- End Function: sub_1411C09C0 (0x1411C09C0) ---

// --- Function: sub_14135E2A0 (0x14135E2A0) ---
void __fastcall sub_14135E2A0(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **, __int64 (__fastcall *)()); // rbx
  unsigned int v3; // eax
  void *v4; // [rsp+30h] [rbp+8h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **, __int64 (__fastcall *)()))(*(_QWORD *)a1 + 80LL);
  CreateStringObjectFromString(&v4, "CStringHash");
  v3 = sub_141366DA0();
  v2(a1, v3, &v4, sub_1403286D0);
  DestroyStringObject(&v4);
}

// --- End Function: sub_14135E2A0 (0x14135E2A0) ---

// --- Function: sub_141366DA0 (0x141366DA0) ---
__int64 sub_141366DA0()
{
  __int64 result; // rax
  unsigned int v1; // edi
  _QWORD **v2; // rcx
  _QWORD *v3; // rdx
  _QWORD *v4; // rbx
  _DWORD v5[4]; // [rsp+20h] [rbp-58h] BYREF
  const void *v6[2]; // [rsp+30h] [rbp-48h] BYREF
  __int128 v7; // [rsp+40h] [rbp-38h] BYREF
  __int64 v8; // [rsp+50h] [rbp-28h]

  result = (unsigned int)dword_1499BED78;
  if ( !dword_1499BED78 )
  {
    sub_140526EF0((__int64)v5);
    sub_140529140(v5);
    v1 = v5[0];
    if ( (_QWORD)v7 )
    {
      sub_14039EFB0((__int64)&v7, (const void *)v7, (v8 - v7) & 0xFFFFFFFFFFFFFFF8uLL);
      v7 = 0;
      v8 = 0;
    }
    v2 = (_QWORD **)v6[0];
    **((_QWORD **)v6[0] + 1) = 0;
    v3 = *v2;
    if ( *v2 )
    {
      do
      {
        v4 = (_QWORD *)*v3;
        sub_14039EFB0((__int64)v6, v3, 0x18u);
        v3 = v4;
      }
      while ( v4 );
    }
    sub_14039EFB0((__int64)v6, v6[0], 0x18u);
    result = v1;
    dword_1499BED78 = v1;
  }
  return result;
}

// --- End Function: sub_141366DA0 (0x141366DA0) ---

// --- Function: sub_141376910 (0x141376910) ---
void __fastcall sub_141376910(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v3; // eax
  void *v4; // [rsp+30h] [rbp+8h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 16LL);
  CreateStringObjectFromString(&v4, "CLocIdentifier");
  v3 = sub_14033D800();
  v2(a1, v3, &v4, sub_14033F310);
  DestroyStringObject(&v4);
}

// --- End Function: sub_141376910 (0x141376910) ---

// --- Function: sub_1425D7A00 (0x1425D7A00) ---
__int64 sub_1425D7A00()
{
  unsigned int v0; // edi
  _QWORD **v1; // rcx
  _QWORD *v2; // rdx
  _QWORD *v3; // rbx
  const void **v5; // [rsp+20h] [rbp-19h] BYREF
  char v6; // [rsp+28h] [rbp-11h]
  const void **v7; // [rsp+30h] [rbp-9h] BYREF
  char v8; // [rsp+38h] [rbp-1h]
  unsigned int v9; // [rsp+40h] [rbp+7h] BYREF
  __int64 v10; // [rsp+48h] [rbp+Fh] BYREF
  const void *v11[2]; // [rsp+50h] [rbp+17h] BYREF
  __int128 v12; // [rsp+60h] [rbp+27h] BYREF
  __int64 v13; // [rsp+70h] [rbp+37h]
  int *v14; // [rsp+A0h] [rbp+67h] BYREF

  sub_140526EF0((__int64)&v9);
  v14 = &dword_149AA82CC;
  sub_140354880((__int64)&v10, (__int64)&v7, (unsigned __int8 *)&v14);
  if ( v8 )
  {
    CreateStringObjectFromString((void **)&v14, "ActorStatusUtils::SActiveDrugDetails");
    sub_140527E00((int *)&v9, (unsigned __int8 *)v14);
    DestroyStringObject(&v14);
    sub_140527D70(&v9, "m_locIdentifier");
    v14 = &dword_14980BD54;
    sub_140354880((__int64)&v10, (__int64)&v5, (unsigned __int8 *)&v14);
    if ( v6 )
    {
      CreateStringObjectFromString((void **)&v14, "CLocIdentifier");
      sub_140527E00((int *)&v9, (unsigned __int8 *)v14);
      DestroyStringObject(&v14);
      sub_140527D70(&v9, "m_sIdentifier");
      sub_140527DD0(&v9);
      sub_1403E0CA0(&v10, &v14, v5);
    }
    sub_140527D70(&v9, "m_endDate");
    v14 = &dword_14980C038;
    sub_140354880((__int64)&v10, (__int64)&v5, (unsigned __int8 *)&v14);
    if ( v6 )
    {
      CreateStringObjectFromString((void **)&v14, "CTimeValue");
      sub_140527E00((int *)&v9, (unsigned __int8 *)v14);
      DestroyStringObject(&v14);
      sub_140527D70(&v9, "m_lValue");
      sub_1405291D0(&v9);
      sub_1403E0CA0(&v10, &v14, v5);
    }
    sub_1403E0CA0(&v10, &v14, v7);
  }
  v0 = v9;
  if ( (_QWORD)v12 )
  {
    sub_14039EFB0((__int64)&v12, (const void *)v12, (v13 - v12) & 0xFFFFFFFFFFFFFFF8uLL);
    v12 = 0;
    v13 = 0;
  }
  v1 = (_QWORD **)v11[0];
  **((_QWORD **)v11[0] + 1) = 0;
  v2 = *v1;
  if ( *v1 )
  {
    do
    {
      v3 = (_QWORD *)*v2;
      sub_14039EFB0((__int64)v11, v2, 0x18u);
      v2 = v3;
    }
    while ( v3 );
  }
  sub_14039EFB0((__int64)v11, v11[0], 0x18u);
  return v0;
}

// --- End Function: sub_1425D7A00 (0x1425D7A00) ---

// --- Function: sub_1425D7FC0 (0x1425D7FC0) ---
__int64 sub_1425D7FC0()
{
  unsigned int v0; // edi
  _QWORD **v1; // rcx
  _QWORD *v2; // rdx
  _QWORD *v3; // rbx
  const void **v5; // [rsp+20h] [rbp-19h] BYREF
  char v6; // [rsp+28h] [rbp-11h]
  const void **v7; // [rsp+30h] [rbp-9h] BYREF
  char v8; // [rsp+38h] [rbp-1h]
  unsigned int v9; // [rsp+40h] [rbp+7h] BYREF
  __int64 v10; // [rsp+48h] [rbp+Fh] BYREF
  const void *v11[2]; // [rsp+50h] [rbp+17h] BYREF
  __int128 v12; // [rsp+60h] [rbp+27h] BYREF
  __int64 v13; // [rsp+70h] [rbp+37h]
  int *v14; // [rsp+A0h] [rbp+67h] BYREF

  sub_140526EF0((__int64)&v9);
  sub_140527BC0(&v9);
  sub_140529140(&v9);
  v14 = &dword_149AA82CC;
  sub_140354880((__int64)&v10, (__int64)&v7, (unsigned __int8 *)&v14);
  if ( v8 )
  {
    CreateStringObjectFromString((void **)&v14, "ActorStatusUtils::SActiveDrugDetails");
    sub_140527E00((int *)&v9, (unsigned __int8 *)v14);
    DestroyStringObject(&v14);
    sub_140527D70(&v9, "m_locIdentifier");
    v14 = &dword_14980BD54;
    sub_140354880((__int64)&v10, (__int64)&v5, (unsigned __int8 *)&v14);
    if ( v6 )
    {
      CreateStringObjectFromString((void **)&v14, "CLocIdentifier");
      sub_140527E00((int *)&v9, (unsigned __int8 *)v14);
      DestroyStringObject(&v14);
      sub_140527D70(&v9, "m_sIdentifier");
      sub_140527DD0(&v9);
      sub_1403E0CA0(&v10, &v14, v5);
    }
    sub_140527D70(&v9, "m_endDate");
    v14 = &dword_14980C038;
    sub_140354880((__int64)&v10, (__int64)&v5, (unsigned __int8 *)&v14);
    if ( v6 )
    {
      CreateStringObjectFromString((void **)&v14, "CTimeValue");
      sub_140527E00((int *)&v9, (unsigned __int8 *)v14);
      DestroyStringObject(&v14);
      sub_140527D70(&v9, "m_lValue");
      sub_1405291D0(&v9);
      sub_1403E0CA0(&v10, &v14, v5);
    }
    sub_1403E0CA0(&v10, &v14, v7);
  }
  v0 = v9;
  if ( (_QWORD)v12 )
  {
    sub_14039EFB0((__int64)&v12, (const void *)v12, (v13 - v12) & 0xFFFFFFFFFFFFFFF8uLL);
    v12 = 0;
    v13 = 0;
  }
  v1 = (_QWORD **)v11[0];
  **((_QWORD **)v11[0] + 1) = 0;
  v2 = *v1;
  if ( *v1 )
  {
    do
    {
      v3 = (_QWORD *)*v2;
      sub_14039EFB0((__int64)v11, v2, 0x18u);
      v2 = v3;
    }
    while ( v3 );
  }
  sub_14039EFB0((__int64)v11, v11[0], 0x18u);
  return v0;
}

// --- End Function: sub_1425D7FC0 (0x1425D7FC0) ---

// --- Function: sub_1425DF270 (0x1425DF270) ---
void __fastcall sub_1425DF270(__int64 a1, __int64 a2)
{
  void (__fastcall *v4)(__int64, _QWORD, void **, __int64, void (__fastcall *)(__int64)); // rdi
  unsigned int v5; // eax
  void *v6; // [rsp+40h] [rbp+8h] BYREF

  v4 = *(void (__fastcall **)(__int64, _QWORD, void **, __int64, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v6, "CLocIdentifier");
  v5 = sub_14033D800();
  v4(a1, v5, &v6, a2, sub_141376910);
  DestroyStringObject(&v6);
}

// --- End Function: sub_1425DF270 (0x1425DF270) ---

// --- Function: sub_1425E1A70 (0x1425E1A70) ---
void __fastcall sub_1425E1A70(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v3; // eax
  void (__fastcall *v4)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v5; // eax
  void *v6; // [rsp+40h] [rbp+8h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v6, "CLocIdentifier");
  v3 = sub_14033D800();
  v2(a1, v3, &v6, "m_locIdentifier", sub_141376910);
  DestroyStringObject(&v6);
  v4 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v6, "CTimeValue");
  v5 = sub_1405244B0();
  v4(a1, v5, &v6, "m_endDate", sub_14033A220);
  DestroyStringObject(&v6);
}

// --- End Function: sub_1425E1A70 (0x1425E1A70) ---

// --- Function: sub_142C05B30 (0x142C05B30) ---
void __fastcall sub_142C05B30(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v3; // eax
  void (__fastcall *v4)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v5; // eax
  void (__fastcall *v6)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v7; // eax
  void (__fastcall *v8)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v9; // eax
  void *v10; // [rsp+40h] [rbp+8h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v10, "CLocIdentifier");
  v3 = sub_14033D800();
  v2(a1, v3, &v10, "nameIdentifier", sub_141376910);
  DestroyStringObject(&v10);
  v4 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v10, "CStringHash");
  v5 = sub_141366DA0();
  v4(a1, v5, &v10, "hInteractionName", sub_14135E2A0);
  DestroyStringObject(&v10);
  v6 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v10, "bool");
  v7 = sub_1405246B0();
  v6(a1, v7, &v10, "isPrimary", sub_14033A260);
  DestroyStringObject(&v10);
  v8 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v10, "bool");
  v9 = sub_1405246B0();
  v8(a1, v9, &v10, "bImportantLocation", sub_14033A260);
  DestroyStringObject(&v10);
}

// --- End Function: sub_142C05B30 (0x142C05B30) ---

// --- Function: sub_142DA6300 (0x142DA6300) ---
__int64 sub_142DA6300()
{
  unsigned int v0; // edi
  _QWORD **v1; // rcx
  _QWORD *v2; // rdx
  _QWORD *v3; // rbx
  const void **v5; // [rsp+20h] [rbp-19h] BYREF
  char v6; // [rsp+28h] [rbp-11h]
  const void **v7; // [rsp+30h] [rbp-9h] BYREF
  char v8; // [rsp+38h] [rbp-1h]
  unsigned int v9; // [rsp+40h] [rbp+7h] BYREF
  __int64 v10; // [rsp+48h] [rbp+Fh] BYREF
  const void *v11[2]; // [rsp+50h] [rbp+17h] BYREF
  __int128 v12; // [rsp+60h] [rbp+27h] BYREF
  __int64 v13; // [rsp+70h] [rbp+37h]
  int *v14; // [rsp+A0h] [rbp+67h] BYREF

  sub_140526EF0((__int64)&v9);
  v14 = &dword_149ADACA0;
  sub_140354880((__int64)&v10, (__int64)&v7, (unsigned __int8 *)&v14);
  if ( v8 )
  {
    CreateStringObjectFromString((void **)&v14, "CEntityComponentRefineryUIProvider::SErrorData");
    sub_140527E00((int *)&v9, (unsigned __int8 *)v14);
    DestroyStringObject(&v14);
    sub_140527D70(&v9, "m_errorIdentifier");
    v14 = &dword_14980BD54;
    sub_140354880((__int64)&v10, (__int64)&v5, (unsigned __int8 *)&v14);
    if ( v6 )
    {
      CreateStringObjectFromString((void **)&v14, "CLocIdentifier");
      sub_140527E00((int *)&v9, (unsigned __int8 *)v14);
      DestroyStringObject(&v14);
      sub_140527D70(&v9, "m_sIdentifier");
      sub_140527DD0(&v9);
      sub_1403E0CA0(&v10, &v14, v5);
    }
    sub_140527D70(&v9, "m_errorValue");
    v14 = &dword_149814FC8;
    sub_140354880((__int64)&v10, (__int64)&v5, (unsigned __int8 *)&v14);
    if ( v6 )
    {
      CreateStringObjectFromString((void **)&v14, "CLocString");
      sub_140527E00((int *)&v9, (unsigned __int8 *)v14);
      DestroyStringObject(&v14);
      sub_140527D70(&v9, "m_wString");
      sub_140527DD0(&v9);
      sub_1403E0CA0(&v10, &v14, v5);
    }
    sub_1403E0CA0(&v10, &v14, v7);
  }
  v0 = v9;
  if ( (_QWORD)v12 )
  {
    sub_14039EFB0((__int64)&v12, (const void *)v12, (v13 - v12) & 0xFFFFFFFFFFFFFFF8uLL);
    v12 = 0;
    v13 = 0;
  }
  v1 = (_QWORD **)v11[0];
  **((_QWORD **)v11[0] + 1) = 0;
  v2 = *v1;
  if ( *v1 )
  {
    do
    {
      v3 = (_QWORD *)*v2;
      sub_14039EFB0((__int64)v11, v2, 0x18u);
      v2 = v3;
    }
    while ( v3 );
  }
  sub_14039EFB0((__int64)v11, v11[0], 0x18u);
  return v0;
}

// --- End Function: sub_142DA6300 (0x142DA6300) ---

// --- Function: sub_142DAF9B0 (0x142DAF9B0) ---
void __fastcall sub_142DAF9B0(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v3; // eax
  void (__fastcall *v4)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)()); // rbx
  unsigned int v5; // eax
  void *v6; // [rsp+40h] [rbp+8h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v6, "CLocIdentifier");
  v3 = sub_14033D800();
  v2(a1, v3, &v6, "m_errorIdentifier", sub_141376910);
  DestroyStringObject(&v6);
  v4 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)()))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v6, "CLocString");
  v5 = sub_140524450();
  v4(a1, v5, &v6, "m_errorValue", sub_14133F6C0);
  DestroyStringObject(&v6);
}

// --- End Function: sub_142DAF9B0 (0x142DAF9B0) ---

// --- Function: sub_1449D0AF0 (0x1449D0AF0) ---
__int64 __fastcall sub_1449D0AF0(__int64 a1)
{
  return sub_1449D47F0(a1, &p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp, 0);
}

// --- End Function: sub_1449D0AF0 (0x1449D0AF0) ---

// --- Function: sub_1449DD9F0 (0x1449DD9F0) ---
__int64 sub_1449DD9F0()
{
  __int64 result; // rax
  unsigned int v1; // edi
  _QWORD **v2; // rcx
  _QWORD *v3; // rdx
  _QWORD *v4; // rbx
  const void **v5; // [rsp+20h] [rbp-60h] BYREF
  char v6; // [rsp+28h] [rbp-58h]
  unsigned int v7; // [rsp+30h] [rbp-50h] BYREF
  __int64 v8; // [rsp+38h] [rbp-48h] BYREF
  const void *v9[2]; // [rsp+40h] [rbp-40h] BYREF
  __int128 v10; // [rsp+50h] [rbp-30h] BYREF
  __int64 v11; // [rsp+60h] [rbp-20h]
  unsigned __int8 *v12; // [rsp+90h] [rbp+10h] BYREF
  __int64 v13; // [rsp+98h] [rbp+18h] BYREF

  result = (unsigned int)dword_149B08014;
  if ( !dword_149B08014 )
  {
    sub_140526EF0((__int64)&v7);
    sub_140527DA0(&v7);
    v12 = (unsigned __int8 *)&dword_149B08180;
    sub_140354880((__int64)&v8, (__int64)&v5, (unsigned __int8 *)&v12);
    if ( v6 )
    {
      CreateStringObjectFromString((void **)&v12, "CEntityComponentShopUIProvider::SItem");
      sub_140527E00((int *)&v7, v12);
      DestroyStringObject(&v12);
      sub_1449E4160(&v7, 0);
      sub_1403E0CA0(&v8, &v13, v5);
    }
    v1 = v7;
    if ( (_QWORD)v10 )
    {
      sub_14039EFB0((__int64)&v10, (const void *)v10, (v11 - v10) & 0xFFFFFFFFFFFFFFF8uLL);
      v10 = 0;
      v11 = 0;
    }
    v2 = (_QWORD **)v9[0];
    **((_QWORD **)v9[0] + 1) = 0;
    v3 = *v2;
    if ( *v2 )
    {
      do
      {
        v4 = (_QWORD *)*v3;
        sub_14039EFB0((__int64)v9, v3, 0x18u);
        v3 = v4;
      }
      while ( v4 );
    }
    sub_14039EFB0((__int64)v9, v9[0], 0x18u);
    result = v1;
    dword_149B08014 = v1;
  }
  return result;
}

// --- End Function: sub_1449DD9F0 (0x1449DD9F0) ---

// --- Function: sub_1449E0F70 (0x1449E0F70) ---
void __fastcall sub_1449E0F70(__int64 a1)
{
  void (__fastcall *v2)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v3; // eax
  void (__fastcall *v4)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v5; // eax
  void (__fastcall *v6)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v7; // eax
  void (__fastcall *v8)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)()); // rbx
  unsigned int v9; // eax
  void (__fastcall *v10)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)()); // rbx
  unsigned int v11; // eax
  void (__fastcall *v12)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v13; // eax
  void (__fastcall *v14)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v15; // eax
  void (__fastcall *v16)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v17; // eax
  void (__fastcall *v18)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v19; // eax
  void (__fastcall *v20)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v21; // eax
  void (__fastcall *v22)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v23; // eax
  void (__fastcall *v24)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v25; // eax
  void (__fastcall *v26)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v27; // eax
  void (__fastcall *v28)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v29; // eax
  void (__fastcall *v30)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v31; // eax
  void (__fastcall *v32)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v33; // eax
  void (__fastcall *v34)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v35; // eax
  void (__fastcall *v36)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v37; // eax
  void (__fastcall *v38)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v39; // eax
  void (__fastcall *v40)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v41; // eax
  void (__fastcall *v42)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v43; // eax
  void (__fastcall *v44)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v45; // eax
  void (__fastcall *v46)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v47; // eax
  void (__fastcall *v48)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v49; // eax
  void (__fastcall *v50)(__int64, _QWORD, __int64, const char *, __int64 (__fastcall *)(__int64)); // rdi
  __int64 v51; // rbx
  unsigned int v52; // eax
  void (__fastcall *v53)(__int64, _QWORD, __int64, const char *, __int64 (__fastcall *)(__int64)); // rdi
  __int64 v54; // rbx
  unsigned int v55; // eax
  void (__fastcall *v56)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)); // rbx
  unsigned int v57; // eax
  void (__fastcall *v58)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v59; // eax
  void (__fastcall *v60)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)); // rbx
  unsigned int v61; // eax
  void *v62; // [rsp+60h] [rbp+30h] BYREF

  v2 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "EntityId");
  v3 = sub_140524510();
  v2(a1, v3, &v62, "m_entityId", sub_14033A230);
  DestroyStringObject(&v62);
  v4 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "CryGUID");
  v5 = sub_14033D560();
  v4(a1, v5, &v62, "m_classGUID", sub_140420D90);
  DestroyStringObject(&v62);
  v6 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "CLocIdentifierHash");
  v7 = sub_1405243F0();
  v6(a1, v7, &v62, "m_nameLookupHash", sub_140420FA0);
  DestroyStringObject(&v62);
  v8 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)()))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "CLocString");
  v9 = sub_140524450();
  v8(a1, v9, &v62, "m_name", sub_14133F6C0);
  DestroyStringObject(&v62);
  v10 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)()))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "CLocString");
  v11 = sub_140524450();
  v10(a1, v11, &v62, "m_desc", sub_14133F6C0);
  DestroyStringObject(&v62);
  v12 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "string");
  v13 = sub_140524310();
  v12(a1, v13, &v62, "m_manufacturerIcon", sub_14033A210);
  DestroyStringObject(&v62);
  v14 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "string");
  v15 = sub_140524310();
  v14(a1, v15, &v62, "m_model", sub_14033A210);
  DestroyStringObject(&v62);
  v16 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "int32");
  v17 = sub_140523E90();
  v16(a1, v17, &v62, "m_modelType", sub_140420D70);
  DestroyStringObject(&v62);
  v18 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "bool");
  v19 = sub_1405246B0();
  v18(a1, v19, &v62, "m_isUnregistered", sub_14033A260);
  DestroyStringObject(&v62);
  v20 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "bool");
  v21 = sub_1405246B0();
  v20(a1, v21, &v62, "m_isSellable", sub_14033A260);
  DestroyStringObject(&v62);
  v22 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "int32");
  v23 = sub_140523E90();
  v22(a1, v23, &v62, "m_amount", sub_140420D70);
  DestroyStringObject(&v62);
  v24 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "int32");
  v25 = sub_140523E90();
  v24(a1, v25, &v62, "m_size", sub_140420D70);
  DestroyStringObject(&v62);
  v26 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "Vec3");
  v27 = sub_140524250();
  v26(a1, v27, &v62, "m_occupancyVolume", sub_140521C60);
  DestroyStringObject(&v62);
  v28 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "f32");
  v29 = sub_140523F70();
  v28(a1, v29, &v62, "m_wearAndTearPercent", sub_140520B40);
  DestroyStringObject(&v62);
  v30 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "EItemType");
  v31 = sub_1411C09C0();
  v30(a1, v31, &v62, "m_itemType", sub_1411B9260);
  DestroyStringObject(&v62);
  v32 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "EItemSubType");
  v33 = sub_1411C08C0();
  v32(a1, v33, &v62, "m_itemSubType", sub_1411B9200);
  DestroyStringObject(&v62);
  v34 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "CLocIdentifier");
  v35 = sub_14033D800();
  v34(a1, v35, &v62, "m_category", sub_141376910);
  DestroyStringObject(&v62);
  v36 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "CLocIdentifier");
  v37 = sub_14033D800();
  v36(a1, v37, &v62, "m_subCategory", sub_141376910);
  DestroyStringObject(&v62);
  v38 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "string");
  v39 = sub_140524310();
  v38(a1, v39, &v62, "m_categoryIcon", sub_14033A210);
  DestroyStringObject(&v62);
  v40 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "int64");
  v41 = sub_1405245D0();
  v40(a1, v41, &v62, "m_basePrice", sub_140420FB0);
  DestroyStringObject(&v62);
  v42 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "int64");
  v43 = sub_1405245D0();
  v42(a1, v43, &v62, "m_totalPrice", sub_140420FB0);
  DestroyStringObject(&v62);
  v44 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "int64");
  v45 = sub_1405245D0();
  v44(a1, v45, &v62, "m_discountedAmount", sub_140420FB0);
  DestroyStringObject(&v62);
  v46 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "f32");
  v47 = sub_140523F70();
  v46(a1, v47, &v62, "m_discountPercentage", sub_140520B40);
  DestroyStringObject(&v62);
  v48 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "bool");
  v49 = sub_1405246B0();
  v48(a1, v49, &v62, "m_showDiscount", sub_14033A260);
  DestroyStringObject(&v62);
  v50 = *(void (__fastcall **)(__int64, _QWORD, __int64, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  v51 = sub_144B467D0(&v62);
  v52 = sub_1449DD9F0();
  v50(a1, v52, v51, "m_attachments", sub_1449D0AF0);
  DestroyStringObject(&v62);
  v53 = *(void (__fastcall **)(__int64, _QWORD, __int64, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  v54 = sub_144B467D0(&v62);
  v55 = sub_1449DD9F0();
  v53(a1, v55, v54, "m_containerContents", sub_1449D0AF0);
  DestroyStringObject(&v62);
  v56 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, __int64 (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "uint8");
  v57 = sub_140523D40();
  v56(a1, v57, &v62, "m_itemSource", sub_140CC93E0);
  DestroyStringObject(&v62);
  v58 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "SInventoryId");
  v59 = sub_14033D640();
  v58(a1, v59, &v62, "m_inventoryId", sub_14056D1B0);
  DestroyStringObject(&v62);
  v60 = *(void (__fastcall **)(__int64, _QWORD, void **, const char *, void (__fastcall *)(__int64)))(*(_QWORD *)a1 + 32LL);
  CreateStringObjectFromString(&v62, "SInventoryId");
  v61 = sub_14033D640();
  v60(a1, v61, &v62, "m_itemInventoryId", sub_14056D1B0);
  DestroyStringObject(&v62);
}

// --- End Function: sub_1449E0F70 (0x1449E0F70) ---

// --- Function: sub_144B467D0 (0x144B467D0) ---
void **__fastcall sub_144B467D0(void **a1)
{
  __int64 v2; // rbx
  __int64 v3; // rax
  void *v5; // [rsp+30h] [rbp+8h] BYREF
  void *v6; // [rsp+38h] [rbp+10h] BYREF

  CreateStringObjectFromString(&v6, "CEntityComponentShopUIProvider::SItem");
  initializeEmptyStringStructure(&v5);
  v2 = sub_1403DD500((__int64)"std::vector<");
  v3 = sub_1403E2EC0(&v6);
  sub_1403E4500(&v5, v3 + v2);
  sub_140380E90(&v5, "std::vector<");
  sub_140380E40(&v5, (char **)&v6);
  sub_1403577C0(a1, (const void **)&v5);
  sub_140380E90(a1, ">");
  DestroyStringObject(&v5);
  DestroyStringObject(&v6);
  return a1;
}

// --- End Function: sub_144B467D0 (0x144B467D0) ---

// --- Function: sub_14739AF10 (0x14739AF10) ---
void __fastcall sub_14739AF10(const void *a1)
{
  if ( a1 )
  {
    if ( qword_14981D3D8 && pCZoneSystem && a1 == (const void *)pCZoneSystem )
    {
      __debugbreak();
    }
    if ( (unsigned __int64)a1 < qword_1497CE098 || (unsigned __int64)a1 >= qword_1497CE098 + 0x8000000000LL )
    {
      if ( (unsigned __int64)a1 >= qword_1497CE078 && (unsigned __int64)a1 < qword_1497CE078 + 0x200000000LL )
      {
        LogFatalError("Address %p was allocated by persistent malloc and cannot be freed!", a1);
      }
      sub_147397F30((__int64)a1);
    }
  }
}

// --- End Function: sub_14739AF10 (0x14739AF10) ---

// --- Function: sub_14739AFC0 (0x14739AFC0) ---
__int64 __fastcall sub_14739AFC0(unsigned __int64 n0x6400000, struct _exception *n0x10)
{
  char v4; // al
  __int64 v5; // rax
  __int64 result; // rax

  if ( n0x6400000 )
  {
    v4 = sub_147273B30();
    sub_140566BA0(v4);
    v5 = AK::MemoryMgr::StopProfileThreadUsage(n0x10);
    result = sub_1473986B0(v5 + n0x6400000, (unsigned __int64)n0x10);
    if ( result )
    {
      return result;
    }
    sub_14739A8D0(n0x6400000);
  }
  return 0LL;
}

// --- End Function: sub_14739AFC0 (0x14739AFC0) ---

// --- Function: memcpy (0x147E162BB) ---
// attributes: thunk
void *__cdecl memcpy(void *a1, const void *Src, size_t Size)
{
  return __imp_memcpy(a1, Src, Size);
}

// --- End Function: memcpy (0x147E162BB) ---

