// Decompiled code dump generated by Code Dumper (Callers/Callees/Refs)
// Start Functions:
//   - 0x14083B460 (sub_14083B460)
//   - 0x14083B480 (sub_14083B480)
//   - 0x142E01C20 (sub_142E01C20)
// Caller Depth: 0
// Callee/Ref Depth: 2
// Total Functions Found: 9
// ------------------------------------------------------------

// --- Function: free_memory_wrapper (0x1402A1E20) ---
// Wrapper function that forwards the memory deallocation request to
// `sub_14739AF10`.
void __fastcall free_memory_wrapper(const void *ptr_to_free)
{
  sub_14739AF10(ptr_to_free);
}

// --- End Function: free_memory_wrapper (0x1402A1E20) ---

// --- Function: sub_1402A1E30 (0x1402A1E30) ---
__int64 __fastcall sub_1402A1E30(unsigned __int64 n0x6400000)
{
  return sub_14739AFC0(n0x6400000, 0LL);
}

// --- End Function: sub_1402A1E30 (0x1402A1E30) ---

// --- Function: sub_14083B460 (0x14083B460) ---
__int64 __fastcall sub_14083B460(__int64 a1, __int64 (__fastcall ***a2)(_QWORD, __int64))
{
  __int64 result; // rax

  if ( a2 )
  {
    return (**a2)(a2, 1LL);
  }
  return result;
}

// --- End Function: sub_14083B460 (0x14083B460) ---

// --- Function: sub_14083B480 (0x14083B480) ---
__int64 __fastcall sub_14083B480(__int64 a1, __int64 (__fastcall ***a2)(_QWORD, __int64))
{
  __int64 result; // rax

  if ( a2 )
  {
    if ( *(a2 - 1) )
    {
      return (**a2)(a2, 3LL);
    }
    else
    {
      return free_memory_wrapper(a2 - 1);
    }
  }
  return result;
}

// --- End Function: sub_14083B480 (0x14083B480) ---

// --- Function: sub_142DCE010 (0x142DCE010) ---
__int64 __fastcall sub_142DCE010(__int64 a1)
{
  __int64 result; // rax

  *(_DWORD *)(a1 + 8) = 1065353216;
  *(_QWORD *)a1 = off_1483A3758;
  *(_DWORD *)(a1 + 12) = 1065353216;
  *(_QWORD *)(a1 + 64) = off_147F51C70;
  *(_DWORD *)(a1 + 16) = 1065353216;
  *(_DWORD *)(a1 + 20) = 1065353216;
  *(_DWORD *)(a1 + 24) = 1065353216;
  *(_DWORD *)(a1 + 28) = 1065353216;
  *(_DWORD *)(a1 + 32) = 1065353216;
  *(_DWORD *)(a1 + 36) = 1065353216;
  *(_DWORD *)(a1 + 40) = 1065353216;
  *(_DWORD *)(a1 + 44) = 1065353216;
  *(_DWORD *)(a1 + 48) = 1065353216;
  *(_DWORD *)(a1 + 52) = 1065353216;
  *(_DWORD *)(a1 + 56) = 1065353216;
  sub_142DC8690(a1 + 88);
  sub_145A3A920(a1 + 280);
  sub_145A3C010(a1 + 656);
  result = a1;
  *(_DWORD *)(a1 + 72) = 1065353216;
  *(_DWORD *)(a1 + 76) = 1065353216;
  *(_DWORD *)(a1 + 80) = 1065353216;
  return result;
}

// --- End Function: sub_142DCE010 (0x142DCE010) ---

// --- Function: sub_142DCFEB0 (0x142DCFEB0) ---
__int64 __fastcall sub_142DCFEB0(__int64 a1)
{
  __int64 result; // rax

  *(_DWORD *)(a1 + 12) = 1065353216;
  *(_DWORD *)(a1 + 8) = 0;
  *(_QWORD *)a1 = off_1483A38A8;
  *(_QWORD *)(a1 + 32) = 0LL;
  *(_DWORD *)(a1 + 16) = 1065353216;
  *(_DWORD *)(a1 + 20) = 1065353216;
  *(_QWORD *)(a1 + 24) = 1065353216LL;
  *(_DWORD *)(a1 + 40) = 1065353216;
  *(_DWORD *)(a1 + 44) = 1065353216;
  *(_DWORD *)(a1 + 48) = 1065353216;
  *(_DWORD *)(a1 + 52) = 1065353216;
  sub_142DCE010(a1 + 56);
  *(_DWORD *)(a1 + 856) = 1065353216;
  *(_QWORD *)(a1 + 848) = off_1483A3798;
  *(_QWORD *)(a1 + 880) = off_1483A37D8;
  *(_QWORD *)(a1 + 912) = off_1483A3818;
  *(_QWORD *)(a1 + 936) = off_1483A3860;
  result = a1;
  *(_DWORD *)(a1 + 860) = 1065353216;
  *(_DWORD *)(a1 + 864) = 1065353216;
  *(_DWORD *)(a1 + 868) = 1065353216;
  *(_QWORD *)(a1 + 872) = 1065353216LL;
  *(_DWORD *)(a1 + 888) = 1065353216;
  *(_DWORD *)(a1 + 892) = 1065353216;
  *(_DWORD *)(a1 + 896) = 1065353216;
  *(_BYTE *)(a1 + 900) = 0;
  *(_DWORD *)(a1 + 904) = 1065353216;
  *(_DWORD *)(a1 + 920) = 1065353216;
  *(_DWORD *)(a1 + 924) = 1065353216;
  *(_DWORD *)(a1 + 928) = 1065353216;
  *(_DWORD *)(a1 + 944) = 1065353216;
  *(_DWORD *)(a1 + 948) = 1065353216;
  *(_DWORD *)(a1 + 952) = 1065353216;
  *(_WORD *)(a1 + 960) = 0;
  return result;
}

// --- End Function: sub_142DCFEB0 (0x142DCFEB0) ---

// --- Function: sub_142E01C20 (0x142E01C20) ---
__int64 __fastcall sub_142E01C20(__int64 a1, unsigned __int64 a2)
{
  unsigned __int64 v2; // rbx
  __int64 v3; // rax
  __int64 v5; // rax
  bool v6; // cf
  unsigned __int64 n0x6400000; // rax
  _QWORD *v8; // rax
  _QWORD *v9; // rsi
  __int64 v10; // rdi

  v2 = a2;
  if ( !a2 )
  {
    v3 = sub_1402A1E30(0x3C8u);
    if ( v3 )
    {
      return sub_142DCFEB0(v3);
    }
    return 0;
  }
  v5 = 968 * a2;
  if ( !is_mul_ok(a2, 0x3C8u) )
  {
    v5 = -1;
  }
  v6 = __CFADD__(v5, 8);
  n0x6400000 = v5 + 8;
  if ( v6 )
  {
    n0x6400000 = -1;
  }
  v8 = (_QWORD *)sub_1402A1E30(n0x6400000);
  if ( !v8 )
  {
    return 0;
  }
  v9 = v8 + 1;
  v10 = (__int64)(v8 + 1);
  *v8 = v2;
  do
  {
    sub_142DCFEB0(v10);
    v10 += 968;
    --v2;
  }
  while ( v2 );
  return (__int64)v9;
}

// --- End Function: sub_142E01C20 (0x142E01C20) ---

// --- Function: sub_14739AF10 (0x14739AF10) ---
void __fastcall sub_14739AF10(const void *a1)
{
  if ( a1 )
  {
    if ( qword_14981D3D8 && pCZoneSystem && a1 == (const void *)pCZoneSystem )
    {
      __debugbreak();
    }
    if ( (unsigned __int64)a1 < qword_1497CE098 || (unsigned __int64)a1 >= qword_1497CE098 + 0x8000000000LL )
    {
      if ( (unsigned __int64)a1 >= qword_1497CE078 && (unsigned __int64)a1 < qword_1497CE078 + 0x200000000LL )
      {
        LogFatalError("Address %p was allocated by persistent malloc and cannot be freed!", a1);
      }
      sub_147397F30((__int64)a1);
    }
  }
}

// --- End Function: sub_14739AF10 (0x14739AF10) ---

// --- Function: sub_14739AFC0 (0x14739AFC0) ---
__int64 __fastcall sub_14739AFC0(unsigned __int64 n0x6400000, struct _exception *n0x10)
{
  char v4; // al
  __int64 v5; // rax
  __int64 result; // rax

  if ( n0x6400000 )
  {
    v4 = sub_147273B30();
    sub_140566BA0(v4);
    v5 = AK::MemoryMgr::StopProfileThreadUsage(n0x10);
    result = sub_1473986B0(v5 + n0x6400000, (unsigned __int64)n0x10);
    if ( result )
    {
      return result;
    }
    sub_14739A8D0(n0x6400000);
  }
  return 0LL;
}

// --- End Function: sub_14739AFC0 (0x14739AFC0) ---

