// Decompiled code dump generated by Code Dumper (Callers/Callees/Refs)
// Start Function: 0x145413200 (sub_145413200)
// Caller Depth: 1
// Callee/Ref Depth: 5
// Total Functions Found: 37
// ------------------------------------------------------------

// --- Function: sub_1402A24F0 (0x1402A24F0) ---
__int64 __fastcall sub_1402A24F0(__int64 a1)
{
  return a1;
}

// --- End Function: sub_1402A24F0 (0x1402A24F0) ---

// --- Function: sub_1402A2AD0 (0x1402A2AD0) ---
__int64 __fastcall sub_1402A2AD0(_QWORD *a1)
{
  void (__fastcall *n2)(__int64, _QWORD *); // rax
  __int64 result; // rax

  n2 = (void (__fastcall *)(__int64, _QWORD *))a1[1];
  if ( (unsigned __int64)n2 < 2 )
  {
    result = 0;
    *a1 = 0;
  }
  else
  {
    n2(2, a1);
    result = 0;
    a1[1] = 0;
    *a1 = 0;
  }
  return result;
}

// --- End Function: sub_1402A2AD0 (0x1402A2AD0) ---

// --- Function: sub_1402A2B80 (0x1402A2B80) ---
__int64 __fastcall sub_1402A2B80(__int64 a1, __int64 a2)
{
  return a2;
}

// --- End Function: sub_1402A2B80 (0x1402A2B80) ---

// --- Function: ??$?8$$CBU_EXCEPTION_RECORD@@$$CBU0@@std@@YA_NAEBV?$shared_ptr@$$CBU_EXCEPTION_RECORD@@@0@0@Z (0x1402B4B80) ---
bool __fastcall std::operator==<_EXCEPTION_RECORD const,_EXCEPTION_RECORD const>(_QWORD *a1, _QWORD *a2)
{
  return *a1 == *a2;
}

// --- End Function: ??$?8$$CBU_EXCEPTION_RECORD@@$$CBU0@@std@@YA_NAEBV?$shared_ptr@$$CBU_EXCEPTION_RECORD@@@0@0@Z (0x1402B4B80) ---

// --- Function: NtCurrentTeb_w (0x1402C6400) ---
__int64 sub_1402C6400()
{
  return *((_QWORD *)NtCurrentTeb()->ThreadLocalStoragePointer + (unsigned int)TlsIndex) + 784LL;
}

// --- End Function: NtCurrentTeb_w (0x1402C6400) ---

// --- Function: sub_1402D2710 (0x1402D2710) ---
__int64 __fastcall sub_1402D2710(__int64 a1, __int64 a2, __int64 a3, char a4)
{
  __int64 result; // rax
  signed __int64 v9; // rdx
  char v10; // [rsp+20h] [rbp-18h]

  result = NtCurrentTeb_w();
  if ( *(_DWORD *)(a1 + 16) == *(_DWORD *)(result + 24) )
  {
    ++*(_DWORD *)(a1 + 20);
  }
  else
  {
    v9 = _InterlockedIncrement64((volatile signed __int64 *)a1);
    if ( (v9 & 0x200000) != 0 )
    {
      v10 = a4;
      return sub_1403CB300(a1, v9, a2, a3, v10);
    }
  }
  return result;
}

// --- End Function: sub_1402D2710 (0x1402D2710) ---

// --- Function: sub_1402D2790 (0x1402D2790) ---
__int64 __fastcall sub_1402D2790(__int64 a1)
{
  __int64 result; // rax
  signed __int64 v3; // rdx

  result = NtCurrentTeb_w();
  if ( *(_DWORD *)(a1 + 16) == *(_DWORD *)(result + 24) && (result = *(unsigned int *)(a1 + 20), (_DWORD)result) )
  {
    result = (unsigned int)(result - 1);
    *(_DWORD *)(a1 + 20) = result;
  }
  else
  {
    v3 = _InterlockedDecrement64((volatile signed __int64 *)a1);
    if ( (v3 & 0x3FF) == 0 )
    {
      result = 0xFFFF0000FFC00000uLL;
      if ( (v3 & 0xFFFF0000FFC00000uLL) != 0 )
        return sub_1403CB820(a1);
    }
  }
  return result;
}

// --- End Function: sub_1402D2790 (0x1402D2790) ---

// --- Function: sub_1402DE3A0 (0x1402DE3A0) ---
void __fastcall sub_1402DE3A0(__int64 a1, __int64 a2, __int64 a3, char a4)
{
  int v8; // edi
  __int64 v9; // r8
  signed __int64 v10; // rax

  v8 = *(_DWORD *)(NtCurrentTeb_w() + 24);
  if ( *(_DWORD *)(a1 + 16) == v8 )
  {
    ++*(_DWORD *)(a1 + 20);
  }
  else
  {
    v9 = *(_QWORD *)(NtCurrentTeb_w() + 32);
    v10 = _InterlockedCompareExchange64((volatile signed __int64 *)a1, 0x200000, 0);
    if ( v10 )
      sub_1403DCD60(a1, v10, v9, a2, a3, a4);
    else
      *(_QWORD *)(a1 + 8) = v9;
    *(_DWORD *)(a1 + 16) = v8;
  }
}

// --- End Function: sub_1402DE3A0 (0x1402DE3A0) ---

// --- Function: sub_1402DE4A0 (0x1402DE4A0) ---
unsigned __int64 __fastcall sub_1402DE4A0(__int64 a1)
{
  int v1; // eax
  unsigned __int64 p_Source; // rax
  signed __int64 n0x200000; // rax

  v1 = *(_DWORD *)(a1 + 20);
  if ( v1 )
  {
    p_Source = (unsigned int)(v1 - 1);
    *(_DWORD *)(a1 + 20) = p_Source;
  }
  else
  {
    *(_DWORD *)(a1 + 16) = -1;
    n0x200000 = _InterlockedCompareExchange64((volatile signed __int64 *)a1, 0, 0x200000);
    if ( n0x200000 == 0x200000 )
    {
      p_Source = (unsigned __int64)&Source;
      *(_QWORD *)(a1 + 8) = &Source;
    }
    else
    {
      return sub_1403DD380(a1, n0x200000);
    }
  }
  return p_Source;
}

// --- End Function: sub_1402DE4A0 (0x1402DE4A0) ---

// --- Function: sub_14036A240 (0x14036A240) ---
__int64 __fastcall sub_14036A240(__int64 a1, char a2, __int64 a3)
{
  __int64 result; // rax

  *(_BYTE *)(a1 + 8) = a2;
  *(_QWORD *)a1 = 0;
  *(_QWORD *)(a1 + 24) = 0;
  *(_QWORD *)(a1 + 32) = 0;
  *(_QWORD *)(a1 + 40) = 0;
  *(_QWORD *)(a1 + 72) = 0;
  result = a1;
  *(_QWORD *)(a1 + 16) = a3;
  *(_DWORD *)(a1 + 80) = 1;
  *(_BYTE *)(a1 + 84) = 1;
  return result;
}

// --- End Function: sub_14036A240 (0x14036A240) ---

// --- Function: sub_1403C33A0 (0x1403C33A0) ---
__int64 __fastcall sub_1403C33A0(__int64 a1, unsigned int a2, __int64 a3, char a4)
{
  if ( a4 && *(_BYTE *)(NtCurrentTeb_w() + 28) && qword_149B4FDB8 )
    return sub_1403C3410(a1, a2, a3);
  else
    return sub_1403C3680(a1, a2, a3);
}

// --- End Function: sub_1403C33A0 (0x1403C33A0) ---

// --- Function: sub_1403C3410 (0x1403C3410) ---
__int64 __fastcall sub_1403C3410(__int64 a1, unsigned __int32 a2, const char *a3)
{
  __int64 v3; // r15
  __int64 v7; // rax
  __int64 v8; // rsi
  unsigned int v9; // r14d
  unsigned __int32 v10; // eax
  __int64 result; // rax
  int v12; // edx
  bool v13; // zf
  signed __int32 v14; // eax
  const ULONG_PTR *p_Source; // rdx
  unsigned __int32 v16; // ett
  const ULONG_PTR *p_Source_1; // rdx
  int n5632; // [rsp+30h] [rbp-79h] BYREF
  __int64 v19; // [rsp+34h] [rbp-75h]
  int n2; // [rsp+3Ch] [rbp-6Dh]
  unsigned __int64 v21; // [rsp+40h] [rbp-69h]
  unsigned __int64 v22; // [rsp+48h] [rbp-61h]
  __int64 v23; // [rsp+50h] [rbp-59h]
  __int64 v24; // [rsp+58h] [rbp-51h]
  int n5632_1; // [rsp+80h] [rbp-29h] BYREF
  __int64 v26; // [rsp+84h] [rbp-25h]
  int n2_1; // [rsp+8Ch] [rbp-1Dh]
  unsigned __int64 v28; // [rsp+90h] [rbp-19h]
  unsigned __int64 v29; // [rsp+98h] [rbp-11h]
  __int64 v30; // [rsp+A0h] [rbp-9h]
  __int64 v31; // [rsp+A8h] [rbp-1h]
  _BYTE v32[16]; // [rsp+D0h] [rbp+27h] BYREF
  char v33; // [rsp+118h] [rbp+6Fh] BYREF

  v3 = qword_149B4FCF8;
  v7 = NtCurrentTeb_w();
  v8 = *(_QWORD *)v7;
  v9 = *(_DWORD *)(*(_QWORD *)v7 + 284LL);
  (*(void (__fastcall **)(__int64, _BYTE *, char *))(*(_QWORD *)v3 + 248LL))(v3, v32, &v33);
  do
  {
    while ( 1 )
    {
      v10 = a2;
      if ( (a2 & 1) == 0 )
        break;
      v12 = v9 << 16;
      if ( (a2 & 0xFFFF0000) != 0 )
      {
        *(_DWORD *)(v8 + 292) = HIWORD(a2);
        v14 = _InterlockedCompareExchange((volatile signed __int32 *)a1, v12 | (unsigned __int16)a2, a2);
        v13 = a2 == v14;
        a2 = v14;
        if ( v13 )
        {
          n5632 = 5632;
          v19 = 1;
          n2 = 2;
          v22 = 0;
          v23 = 0;
          v24 = 0;
          v21 = __rdtsc();
          qword_149B4B870(
            &n5632,
            &word_149B3E374,
            "Wait For Critical Section",
            "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigCriticalSection.cpp",
            145);
          p_Source = &Source;
          HIWORD(n5632) = word_149B3E374;
          if ( *(_QWORD *)(a1 + 8) )
            p_Source = *(const ULONG_PTR **)(a1 + 8);
          qword_149B4B8B0("LockOwner: %s", p_Source);
          qword_149B4B8B0("Caller: %s", a3);
          (*(void (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v3 + 232LL))(v3, v9);
          a2 = *(_DWORD *)a1;
          v9 = *(_DWORD *)(v8 + 284);
          v22 = __rdtsc();
          qword_149B4B878(&n5632);
        }
      }
      else
      {
        *(_DWORD *)(v8 + 292) = -1;
        v16 = a2;
        a2 = _InterlockedCompareExchange((volatile signed __int32 *)a1, a2 | v12, a2);
        if ( v16 == a2 )
        {
          n5632_1 = 5632;
          v26 = 1;
          n2_1 = 2;
          v29 = 0;
          v30 = 0;
          v31 = 0;
          v28 = __rdtsc();
          qword_149B4B870(
            &n5632_1,
            &word_149B3E378,
            "Wait For Critical Section",
            "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigCriticalSection.cpp",
            178);
          p_Source_1 = &Source;
          HIWORD(n5632_1) = word_149B3E378;
          if ( *(_QWORD *)(a1 + 8) )
            p_Source_1 = *(const ULONG_PTR **)(a1 + 8);
          qword_149B4B8B0("LockOwner: %s", p_Source_1);
          qword_149B4B8B0("Caller: %s", a3);
          (*(void (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v3 + 232LL))(v3, v9);
          a2 = *(_DWORD *)a1;
          v9 = *(_DWORD *)(v8 + 284);
          v29 = __rdtsc();
          qword_149B4B878(&n5632_1);
        }
      }
    }
    a2 = _InterlockedCompareExchange((volatile signed __int32 *)a1, a2 | 1, a2);
  }
  while ( v10 != a2 );
  result = NtCurrentTeb_w();
  *(_QWORD *)(a1 + 8) = *(_QWORD *)(result + 32);
  return result;
}

// --- End Function: sub_1403C3410 (0x1403C3410) ---

// --- Function: sub_1403C3680 (0x1403C3680) ---
__int64 __fastcall sub_1403C3680(__int64 a1, signed __int32 a2, const char *a3)
{
  char v3; // r14
  signed __int32 v7; // ecx
  bool v8; // zf
  signed __int32 v9; // eax
  __int64 result; // rax
  const ULONG_PTR *p_Source; // rdx
  signed __int32 v12; // esi
  signed __int32 v13; // eax
  const ULONG_PTR *p_Source_1; // rdx
  int v15; // [rsp+28h] [rbp-79h]
  int v16; // [rsp+28h] [rbp-79h]
  signed __int32 v17; // [rsp+38h] [rbp-69h] BYREF
  signed __int32 v18[3]; // [rsp+3Ch] [rbp-65h] BYREF
  int n5632; // [rsp+48h] [rbp-59h] BYREF
  __int64 v20; // [rsp+4Ch] [rbp-55h]
  int n2; // [rsp+54h] [rbp-4Dh]
  unsigned __int64 v22; // [rsp+58h] [rbp-49h]
  unsigned __int64 v23; // [rsp+60h] [rbp-41h]
  __int64 v24; // [rsp+68h] [rbp-39h]
  __int64 v25; // [rsp+70h] [rbp-31h]
  int n5632_1; // [rsp+98h] [rbp-9h] BYREF
  __int64 v27; // [rsp+9Ch] [rbp-5h]
  int n2_1; // [rsp+A4h] [rbp+3h]
  unsigned __int64 v29; // [rsp+A8h] [rbp+7h]
  unsigned __int64 v30; // [rsp+B0h] [rbp+Fh]
  __int64 v31; // [rsp+B8h] [rbp+17h]
  __int64 v32; // [rsp+C0h] [rbp+1Fh]

  v3 = 0;
  do
  {
    while ( (a2 & 1) != 0 )
    {
      if ( v3 )
      {
        n5632 = 5632;
        v20 = 1;
        n2 = 2;
        v23 = 0;
        v24 = 0;
        v25 = 0;
        v22 = __rdtsc();
        qword_149B4B870(
          &n5632,
          &word_149B3E36C,
          "Wait For Critical Section",
          "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigCriticalSection.cpp",
          56);
        p_Source = &Source;
        HIWORD(n5632) = word_149B3E36C;
        if ( *(_QWORD *)(a1 + 8) )
          p_Source = *(const ULONG_PTR **)(a1 + 8);
        qword_149B4B8B0("LockOwner: %s", p_Source);
        qword_149B4B8B0("Caller: %s", a3);
        v17 = a2;
        qword_149B3B480(a1, &v17, 4, 0xFFFFFFFFLL, v15);
        a2 = *(_DWORD *)a1;
        v23 = __rdtsc();
        qword_149B4B878(&n5632);
      }
      else
      {
        v12 = a2 + 2;
        v13 = _InterlockedCompareExchange((volatile signed __int32 *)a1, a2 + 2, a2);
        v8 = a2 == v13;
        a2 = v13;
        if ( v8 )
        {
          v3 = 1;
          n5632_1 = 5632;
          v27 = 1;
          n2_1 = 2;
          v30 = 0;
          v31 = 0;
          v32 = 0;
          v29 = __rdtsc();
          qword_149B4B870(
            &n5632_1,
            &word_149B3E370,
            "Wait For Critical Section",
            "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigCriticalSection.cpp",
            80);
          p_Source_1 = &Source;
          HIWORD(n5632_1) = word_149B3E370;
          if ( *(_QWORD *)(a1 + 8) )
            p_Source_1 = *(const ULONG_PTR **)(a1 + 8);
          qword_149B4B8B0("LockOwner: %s", p_Source_1);
          qword_149B4B8B0("Caller: %s", a3);
          v18[0] = v12;
          qword_149B3B480(a1, v18, 4, 0xFFFFFFFFLL, v16);
          a2 = *(_DWORD *)a1;
          v30 = __rdtsc();
          qword_149B4B878(&n5632_1);
        }
      }
    }
    v7 = (a2 | 1) - 2;
    if ( !v3 )
      v7 = a2 | 1;
    v9 = _InterlockedCompareExchange((volatile signed __int32 *)a1, v7, a2);
    v8 = a2 == v9;
    a2 = v9;
  }
  while ( !v8 );
  result = NtCurrentTeb_w();
  *(_QWORD *)(a1 + 8) = *(_QWORD *)(result + 32);
  return result;
}

// --- End Function: sub_1403C3680 (0x1403C3680) ---

// --- Function: sub_1403CB300 (0x1403CB300) ---
__int64 __fastcall sub_1403CB300(__int64 a1, __int64 a2, __int64 a3, __int64 a4, char a5)
{
  if ( a5 && *(_BYTE *)(NtCurrentTeb_w() + 28) && qword_149B4FDB8 )
    return sub_1403CB380(a1, a2, a3, a4);
  else
    return sub_1403CB5B0(a1, a2, a3, a4);
}

// --- End Function: sub_1403CB300 (0x1403CB300) ---

// --- Function: sub_1403CB380 (0x1403CB380) ---
__int64 __fastcall sub_1403CB380(__int64 a1, signed __int64 a2, const char *a3, const char *a4)
{
  __int64 v4; // r14
  __int64 v9; // rax
  __int64 v10; // rsi
  unsigned int v11; // r15d
  __int64 result; // rax
  unsigned __int64 v13; // rdx
  bool v14; // zf
  __int16 v15; // ax
  const ULONG_PTR *p_Source; // rdx
  _BYTE v17[16]; // [rsp+30h] [rbp-29h] BYREF
  int n5632; // [rsp+40h] [rbp-19h] BYREF
  __int64 v19; // [rsp+44h] [rbp-15h]
  int n2; // [rsp+4Ch] [rbp-Dh]
  unsigned __int64 v21; // [rsp+50h] [rbp-9h]
  unsigned __int64 v22; // [rsp+58h] [rbp-1h]
  __int64 v23; // [rsp+60h] [rbp+7h]
  __int64 v24; // [rsp+68h] [rbp+Fh]
  char v25; // [rsp+C8h] [rbp+6Fh] BYREF

  v4 = qword_149B4FCF8;
  v9 = NtCurrentTeb_w();
  v10 = *(_QWORD *)v9;
  v11 = *(_DWORD *)(*(_QWORD *)v9 + 284LL);
  result = (*(__int64 (__fastcall **)(__int64, _BYTE *, char *))(*(_QWORD *)v4 + 248LL))(v4, v17, &v25);
  if ( (a2 & 0x200000) == 0 )
    return result;
  v13 = (unsigned __int64)v11 << 32;
  while ( (a2 & 0xFFFF00000000LL) != 0 )
  {
    *(_DWORD *)(v10 + 292) = WORD2(a2);
    result = _InterlockedCompareExchange64((volatile signed __int64 *)a1, v13 | a2 & 0xFFFF0000FFFFFFFFuLL, a2);
    v14 = a2 == result;
    a2 = result;
    if ( v14 )
    {
      n5632 = 5632;
      v22 = 0;
      v23 = 0;
      v24 = 0;
      v19 = 1;
      n2 = 2;
      v21 = __rdtsc();
      qword_149B4B870(
        &n5632,
        &word_149B3E384,
        "Wait For RLock",
        "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigRWLock.cpp",
        146);
      v15 = word_149B3E384;
      goto LABEL_10;
    }
LABEL_7:
    if ( (a2 & 0x200000) == 0 )
      return result;
  }
  *(_DWORD *)(v10 + 292) = -1;
  result = _InterlockedCompareExchange64((volatile signed __int64 *)a1, a2 | v13, a2);
  v14 = a2 == result;
  a2 = result;
  if ( !v14 )
    goto LABEL_7;
  n5632 = 5632;
  v22 = 0;
  v23 = 0;
  v24 = 0;
  v19 = 1;
  n2 = 2;
  v21 = __rdtsc();
  qword_149B4B870(
    &n5632,
    &word_149B3E388,
    "Wait For RLock",
    "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigRWLock.cpp",
    177);
  v15 = word_149B3E388;
LABEL_10:
  HIWORD(n5632) = v15;
  qword_149B4B8B0("Lock: %s", a4);
  p_Source = &Source;
  if ( *(_QWORD *)(a1 + 8) )
    p_Source = *(const ULONG_PTR **)(a1 + 8);
  qword_149B4B8B0("LockOwner: %s", p_Source);
  qword_149B4B8B0("Caller: %s", a3);
  (*(void (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v4 + 232LL))(v4, v11);
  v22 = __rdtsc();
  return qword_149B4B878(&n5632);
}

// --- End Function: sub_1403CB380 (0x1403CB380) ---

// --- Function: sub_1403CB5B0 (0x1403CB5B0) ---
__int64 __fastcall sub_1403CB5B0(__int64 a1, signed __int64 a2, const char *a3, const char *a4)
{
  signed __int64 v6; // rbx
  const ULONG_PTR *p_Source_1; // rdx
  int *p_n5632; // rcx
  int v10; // edi
  bool v11; // zf
  __int64 result; // rax
  const ULONG_PTR *p_Source; // rdx
  int v14; // [rsp+20h] [rbp-79h]
  int v15; // [rsp+20h] [rbp-79h]
  int v16; // [rsp+30h] [rbp-69h] BYREF
  _DWORD v17[3]; // [rsp+34h] [rbp-65h] BYREF
  int n5632_1; // [rsp+40h] [rbp-59h] BYREF
  __int64 v19; // [rsp+44h] [rbp-55h]
  int n2_1; // [rsp+4Ch] [rbp-4Dh]
  unsigned __int64 v21; // [rsp+50h] [rbp-49h]
  unsigned __int64 v22; // [rsp+58h] [rbp-41h]
  __int64 v23; // [rsp+60h] [rbp-39h]
  __int64 v24; // [rsp+68h] [rbp-31h]
  int n5632; // [rsp+90h] [rbp-9h] BYREF
  __int64 v26; // [rsp+94h] [rbp-5h]
  int n2; // [rsp+9Ch] [rbp+3h]
  unsigned __int64 v28; // [rsp+A0h] [rbp+7h]
  unsigned __int64 v29; // [rsp+A8h] [rbp+Fh]
  __int64 v30; // [rsp+B0h] [rbp+17h]
  __int64 v31; // [rsp+B8h] [rbp+1Fh]

  if ( (a2 & 0x200000) != 0 )
  {
    v6 = a2;
    while ( 1 )
    {
      if ( (v6 & 0xFFC00) != 0 )
        (*(void (__fastcall **)(__int64, __int64))(*(_QWORD *)qword_149B4FCF8 + 296LL))(qword_149B4FCF8, a1);
      if ( (v6 & 0x100000) != 0 )
        break;
      v10 = v6 | 0x100000;
      result = _InterlockedCompareExchange64((volatile signed __int64 *)a1, v6 | 0x100000, v6);
      v11 = v6 == result;
      v6 = result;
      if ( v11 )
      {
        n5632 = 5632;
        v26 = 1;
        n2 = 2;
        v29 = 0;
        v30 = 0;
        v31 = 0;
        v28 = __rdtsc();
        qword_149B4B870(
          &n5632,
          &word_149B3E380,
          "Wait For RLock",
          "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigRWLock.cpp",
          98);
        HIWORD(n5632) = word_149B3E380;
        qword_149B4B8B0("Lock: %s", a4);
        p_Source = &Source;
        if ( *(_QWORD *)(a1 + 8) )
          p_Source = *(const ULONG_PTR **)(a1 + 8);
        qword_149B4B8B0("LockOwner: %s", p_Source);
        qword_149B4B8B0("Caller: %s", a3);
        v17[0] = v10;
        qword_149B3B480(a1, v17, 4, 0xFFFFFFFFLL, v15);
        v6 = *(_QWORD *)a1;
        p_n5632 = &n5632;
        v29 = __rdtsc();
        goto LABEL_13;
      }
LABEL_14:
      if ( (v6 & 0x200000) == 0 )
        return result;
    }
    n5632_1 = 5632;
    v19 = 1;
    n2_1 = 2;
    v22 = 0;
    v23 = 0;
    v24 = 0;
    v21 = __rdtsc();
    qword_149B4B870(
      &n5632_1,
      &word_149B3E37C,
      "Wait For RLock",
      "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigRWLock.cpp",
      74);
    HIWORD(n5632_1) = word_149B3E37C;
    qword_149B4B8B0("Lock: %s", a4);
    p_Source_1 = &Source;
    if ( *(_QWORD *)(a1 + 8) )
      p_Source_1 = *(const ULONG_PTR **)(a1 + 8);
    qword_149B4B8B0("LockOwner: %s", p_Source_1);
    qword_149B4B8B0("Caller: %s", a3);
    v16 = v6;
    qword_149B3B480(a1, &v16, 4, 0xFFFFFFFFLL, v14);
    v6 = *(_QWORD *)a1;
    p_n5632 = &n5632_1;
    v22 = __rdtsc();
LABEL_13:
    result = qword_149B4B878(p_n5632);
    goto LABEL_14;
  }
  return result;
}

// --- End Function: sub_1403CB5B0 (0x1403CB5B0) ---

// --- Function: sub_1403CB820 (0x1403CB820) ---
__int64 __fastcall sub_1403CB820(volatile signed __int64 *a1, unsigned __int64 a2)
{
  signed __int64 v4; // rdx
  unsigned int v5; // r8d
  __int64 result; // rax
  unsigned __int64 v7; // rbx
  int v8; // [rsp+60h] [rbp+8h] BYREF
  int v9; // [rsp+68h] [rbp+10h] BYREF
  __int64 v10; // [rsp+70h] [rbp+18h] BYREF
  __int64 v11; // [rsp+78h] [rbp+20h] BYREF

  while ( 1 )
  {
    v4 = a2;
    if ( (a2 & 0xFFC00000) == 0 )
    {
      (*(void (__fastcall **)(__int64, __int64 *, int *))(*(_QWORD *)qword_149B4FCF8 + 248LL))(
        qword_149B4FCF8,
        &v10,
        &v8);
      v4 = a2 & 0xFFFFFFFFFFFFLL;
      v5 = *(_DWORD *)(((HIWORD(a2) & (unsigned int)(v8 - 1)) << 9) + v10 + 292);
      if ( v5 != -1 )
        v4 |= (unsigned __int64)v5 << 48;
    }
    result = _InterlockedCompareExchange64(a1, v4, a2);
    if ( a2 == result )
      break;
    if ( (result & 0x3FF) != 0 || (result & 0x200000) != 0 || (result & 0xFFFF0000FFC00000uLL) == 0 )
      return result;
    a2 = result;
  }
  if ( (a2 & 0xFFC00000) != 0 )
    return qword_149B3B488(a1);
  result = 0xFFFF000000000000uLL;
  if ( (a2 & 0xFFFF000000000000uLL) != 0 )
  {
    (*(void (__fastcall **)(__int64, __int64 *, int *))(*(_QWORD *)qword_149B4FCF8 + 248LL))(qword_149B4FCF8, &v11, &v9);
    v7 = HIWORD(a2);
    *(_DWORD *)(((unsigned __int64)((unsigned int)v7 & (v9 - 1)) << 9) + v11 + 284) = (unsigned __int16)(v7 + v9);
    return (*(__int64 (__fastcall **)(__int64, _QWORD))(*(_QWORD *)qword_149B4FCF8 + 216LL))(
             qword_149B4FCF8,
             (unsigned int)v7);
  }
  return result;
}

// --- End Function: sub_1403CB820 (0x1403CB820) ---

// --- Function: sub_1403DB1F0 (0x1403DB1F0) ---
const ULONG_PTR *__fastcall sub_1403DB1F0(__int64 a1, unsigned __int32 a2)
{
  signed __int32 v4; // ebx
  int v5; // edx
  signed __int32 v6; // eax
  const ULONG_PTR *p_Source; // rax
  int v8; // [rsp+50h] [rbp+8h] BYREF
  int v9; // [rsp+58h] [rbp+10h] BYREF
  __int64 v10; // [rsp+60h] [rbp+18h] BYREF
  __int64 v11; // [rsp+68h] [rbp+20h] BYREF

  while ( 1 )
  {
    v4 = a2 & 0xFFFFFFFE;
    if ( (a2 & 0xFFFE) == 0 && (a2 & 0xFFFF0000) != 0 )
    {
      (*(void (__fastcall **)(__int64, __int64 *, int *))(*(_QWORD *)qword_149B4FCF8 + 248LL))(
        qword_149B4FCF8,
        &v10,
        &v9);
      v4 = (unsigned __int16)v4;
      v5 = *(_DWORD *)(((((unsigned __int64)a2 >> 16) & (unsigned int)(v9 - 1)) << 9) + v10 + 292);
      if ( v5 != -1 )
        v4 = (v5 << 16) | (unsigned __int16)v4;
    }
    v6 = _InterlockedCompareExchange((volatile signed __int32 *)a1, v4, a2);
    if ( a2 == v6 )
      break;
    a2 = v6;
  }
  if ( (a2 & 0xFFFE) != 0 )
  {
    qword_149B3B488(a1);
  }
  else if ( (a2 & 0xFFFF0000) != 0 )
  {
    (*(void (__fastcall **)(__int64, __int64 *, int *))(*(_QWORD *)qword_149B4FCF8 + 248LL))(qword_149B4FCF8, &v11, &v8);
    *(_DWORD *)(((HIWORD(a2) & (unsigned __int64)(unsigned int)(v8 - 1)) << 9) + v11 + 284) = (unsigned __int16)(HIWORD(a2) + v8);
    (*(void (__fastcall **)(__int64))(*(_QWORD *)qword_149B4FCF8 + 216LL))(qword_149B4FCF8);
  }
  p_Source = &Source;
  *(_QWORD *)(a1 + 8) = &Source;
  return p_Source;
}

// --- End Function: sub_1403DB1F0 (0x1403DB1F0) ---

// --- Function: sub_1403DCD60 (0x1403DCD60) ---
__int64 __fastcall sub_1403DCD60(int a1, int a2, int a3, int a4, __int64 a5, char a6)
{
  if ( a6 && *(_BYTE *)(NtCurrentTeb_w() + 28) && qword_149B4FDB8 )
    return sub_1403DCDF0(a1, a2, a3, a4, a5);
  else
    return sub_1403DD0B0(a1, a2, a3, a4, a5);
}

// --- End Function: sub_1403DCD60 (0x1403DCD60) ---

// --- Function: sub_1403DCDF0 (0x1403DCDF0) ---
__int64 __fastcall sub_1403DCDF0(__int64 a1, unsigned __int64 a2, __int64 a3, const char *a4, const char *a5)
{
  __int64 v5; // r15
  __int64 v9; // rax
  __int64 v10; // rsi
  unsigned int v11; // r14d
  const char *v12; // r13
  bool v13; // zf
  signed __int64 v14; // rax
  __int64 result; // rax
  unsigned __int64 v16; // rdx
  signed __int64 v17; // rax
  const ULONG_PTR *p_Source; // rdx
  signed __int64 v19; // rax
  const ULONG_PTR *p_Source_1; // rdx
  int n5632; // [rsp+30h] [rbp-91h] BYREF
  __int64 v22; // [rsp+34h] [rbp-8Dh]
  int n2; // [rsp+3Ch] [rbp-85h]
  unsigned __int64 v24; // [rsp+40h] [rbp-81h]
  unsigned __int64 v25; // [rsp+48h] [rbp-79h]
  __int64 v26; // [rsp+50h] [rbp-71h]
  __int64 v27; // [rsp+58h] [rbp-69h]
  int n5632_1; // [rsp+80h] [rbp-41h] BYREF
  __int64 v29; // [rsp+84h] [rbp-3Dh]
  int n2_1; // [rsp+8Ch] [rbp-35h]
  unsigned __int64 v31; // [rsp+90h] [rbp-31h]
  unsigned __int64 v32; // [rsp+98h] [rbp-29h]
  __int64 v33; // [rsp+A0h] [rbp-21h]
  __int64 v34; // [rsp+A8h] [rbp-19h]
  _BYTE v35[64]; // [rsp+D0h] [rbp+Fh] BYREF
  char v36; // [rsp+120h] [rbp+5Fh] BYREF
  __int64 v37; // [rsp+130h] [rbp+6Fh]

  v37 = a3;
  v5 = qword_149B4FCF8;
  v9 = NtCurrentTeb_w();
  v10 = *(_QWORD *)v9;
  v11 = *(_DWORD *)(*(_QWORD *)v9 + 284LL);
  (*(void (__fastcall **)(__int64, _BYTE *, char *))(*(_QWORD *)v5 + 248LL))(v5, v35, &v36);
  v12 = a5;
  do
  {
    while ( (a2 & 0x2003FF) != 0 )
    {
      v16 = (unsigned __int64)v11 << 48;
      if ( (a2 & 0xFFFF000000000000uLL) != 0 )
      {
        *(_DWORD *)(v10 + 292) = HIWORD(a2);
        v17 = _InterlockedCompareExchange64((volatile signed __int64 *)a1, v16 | a2 & 0xFFFFFFFFFFFFLL, a2);
        v13 = a2 == v17;
        a2 = v17;
        if ( v13 )
        {
          n5632 = 5632;
          v22 = 1;
          n2 = 2;
          v25 = 0;
          v26 = 0;
          v27 = 0;
          v24 = __rdtsc();
          qword_149B4B870(
            &n5632,
            &word_149B3E394,
            "Wait For WLock",
            "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigRWLock.cpp",
            397);
          HIWORD(n5632) = word_149B3E394;
          qword_149B4B8B0("Lock: %s", v12);
          p_Source = &Source;
          if ( *(_QWORD *)(a1 + 8) )
            p_Source = *(const ULONG_PTR **)(a1 + 8);
          qword_149B4B8B0("LockOwner: %s", p_Source);
          qword_149B4B8B0("Caller: %s", a4);
          (*(void (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v5 + 232LL))(v5, v11);
          a2 = *(_QWORD *)a1;
          v11 = *(_DWORD *)(v10 + 284);
          v25 = __rdtsc();
          qword_149B4B878(&n5632);
        }
      }
      else
      {
        *(_DWORD *)(v10 + 292) = -1;
        v19 = _InterlockedCompareExchange64((volatile signed __int64 *)a1, a2 | v16, a2);
        v13 = a2 == v19;
        a2 = v19;
        if ( v13 )
        {
          n5632_1 = 5632;
          v29 = 1;
          n2_1 = 2;
          v32 = 0;
          v33 = 0;
          v34 = 0;
          v31 = __rdtsc();
          qword_149B4B870(
            &n5632_1,
            &word_149B3E398,
            "Wait For WLock",
            "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigRWLock.cpp",
            430);
          HIWORD(n5632_1) = word_149B3E398;
          qword_149B4B8B0("Lock: %s", v12);
          p_Source_1 = &Source;
          if ( *(_QWORD *)(a1 + 8) )
            p_Source_1 = *(const ULONG_PTR **)(a1 + 8);
          qword_149B4B8B0("LockOwner: %s", p_Source_1);
          qword_149B4B8B0("Caller: %s", a4);
          (*(void (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v5 + 232LL))(v5, v11);
          a2 = *(_QWORD *)a1;
          v11 = *(_DWORD *)(v10 + 284);
          v32 = __rdtsc();
          qword_149B4B878(&n5632_1);
        }
      }
    }
    v14 = _InterlockedCompareExchange64((volatile signed __int64 *)a1, a2 | 0x200000, a2);
    v13 = a2 == v14;
    a2 = v14;
  }
  while ( !v13 );
  result = v37;
  *(_QWORD *)(a1 + 8) = v37;
  return result;
}

// --- End Function: sub_1403DCDF0 (0x1403DCDF0) ---

// --- Function: sub_1403DD0B0 (0x1403DD0B0) ---
signed __int64 __fastcall sub_1403DD0B0(__int64 a1, signed __int64 a2, __int64 a3, const char *a4, const char *a5)
{
  char v5; // r14
  signed __int64 v9; // rcx
  bool v10; // zf
  signed __int64 result; // rax
  const ULONG_PTR *p_Source; // rdx
  int v13; // esi
  signed __int64 v14; // rax
  const ULONG_PTR *p_Source_1; // rdx
  int v16; // [rsp+28h] [rbp-91h]
  int v17; // [rsp+28h] [rbp-91h]
  int v18; // [rsp+38h] [rbp-81h] BYREF
  _DWORD v19[3]; // [rsp+3Ch] [rbp-7Dh] BYREF
  int n5632; // [rsp+48h] [rbp-71h] BYREF
  __int64 v21; // [rsp+4Ch] [rbp-6Dh]
  int n2; // [rsp+54h] [rbp-65h]
  unsigned __int64 v23; // [rsp+58h] [rbp-61h]
  unsigned __int64 v24; // [rsp+60h] [rbp-59h]
  __int64 v25; // [rsp+68h] [rbp-51h]
  __int64 v26; // [rsp+70h] [rbp-49h]
  int n5632_1; // [rsp+98h] [rbp-21h] BYREF
  __int64 v28; // [rsp+9Ch] [rbp-1Dh]
  int n2_1; // [rsp+A4h] [rbp-15h]
  unsigned __int64 v30; // [rsp+A8h] [rbp-11h]
  unsigned __int64 v31; // [rsp+B0h] [rbp-9h]
  __int64 v32; // [rsp+B8h] [rbp-1h]
  __int64 v33; // [rsp+C0h] [rbp+7h]

  v5 = 0;
  do
  {
    while ( 1 )
    {
      if ( (a2 & 0xFFC00) != 0 )
        (*(void (__fastcall **)(__int64, __int64))(*(_QWORD *)qword_149B4FCF8 + 296LL))(qword_149B4FCF8, a1);
      if ( (a2 & 0x2003FF) == 0 )
        break;
      if ( v5 )
      {
        n5632 = 5632;
        v21 = 1;
        n2 = 2;
        v24 = 0;
        v25 = 0;
        v26 = 0;
        v23 = __rdtsc();
        qword_149B4B870(
          &n5632,
          &word_149B3E38C,
          "Wait For WLock",
          "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigRWLock.cpp",
          323);
        HIWORD(n5632) = word_149B3E38C;
        qword_149B4B8B0("Lock: %s", a5);
        p_Source = &Source;
        if ( *(_QWORD *)(a1 + 8) )
          p_Source = *(const ULONG_PTR **)(a1 + 8);
        qword_149B4B8B0("LockOwner: %s", p_Source);
        qword_149B4B8B0("Caller: %s", a4);
        v18 = a2;
        qword_149B3B480(a1, &v18, 4, 0xFFFFFFFFLL, v16);
        a2 = *(_QWORD *)a1;
        v24 = __rdtsc();
        qword_149B4B878(&n5632);
      }
      else
      {
        v13 = a2 + 0x400000;
        v14 = _InterlockedCompareExchange64((volatile signed __int64 *)a1, a2 + 0x400000, a2);
        v10 = a2 == v14;
        a2 = v14;
        if ( v10 )
        {
          v5 = 1;
          n5632_1 = 5632;
          v28 = 1;
          n2_1 = 2;
          v31 = 0;
          v32 = 0;
          v33 = 0;
          v30 = __rdtsc();
          qword_149B4B870(
            &n5632_1,
            &word_149B3E390,
            "Wait For WLock",
            "W:\\p4-src\\CryEngine\\Code\\CryEngine\\CryCommon\\Multithreading/CigRWLock.cpp",
            349);
          HIWORD(n5632_1) = word_149B3E390;
          qword_149B4B8B0("Lock: %s", a5);
          p_Source_1 = &Source;
          if ( *(_QWORD *)(a1 + 8) )
            p_Source_1 = *(const ULONG_PTR **)(a1 + 8);
          qword_149B4B8B0("LockOwner: %s", p_Source_1);
          qword_149B4B8B0("Caller: %s", a4);
          v19[0] = v13;
          qword_149B3B480(a1, v19, 4, 0xFFFFFFFFLL, v17);
          a2 = *(_QWORD *)a1;
          v31 = __rdtsc();
          qword_149B4B878(&n5632_1);
        }
      }
    }
    v9 = (a2 | 0x200000) - 0x400000;
    if ( !v5 )
      v9 = a2 | 0x200000;
    result = _InterlockedCompareExchange64((volatile signed __int64 *)a1, v9, a2);
    v10 = a2 == result;
    a2 = result;
  }
  while ( !v10 );
  *(_QWORD *)(a1 + 8) = a3;
  return result;
}

// --- End Function: sub_1403DD0B0 (0x1403DD0B0) ---

// --- Function: sub_1403DD380 (0x1403DD380) ---
const ULONG_PTR *__fastcall sub_1403DD380(__int64 a1, unsigned __int64 a2)
{
  signed __int64 v4; // rdi
  unsigned int v5; // edx
  signed __int64 v6; // rax
  __int64 v7; // rdi
  __int64 v8; // r8
  int v9; // ecx
  __int64 v10; // r8
  unsigned __int64 v11; // rbx
  const ULONG_PTR *p_Source; // rax
  int v13; // [rsp+70h] [rbp+8h] BYREF
  int v14; // [rsp+78h] [rbp+10h] BYREF
  __int64 v15; // [rsp+80h] [rbp+18h] BYREF
  __int64 v16; // [rsp+88h] [rbp+20h] BYREF

  while ( 1 )
  {
    v4 = a2 & 0xFFFFFFFFFFD003FFuLL;
    if ( (a2 & 0xFFFF00100000LL) != 0 )
    {
      v4 = a2 & 0xFFFF0000FFC003FFuLL;
    }
    else if ( (a2 & 0xFFC003FF) == 0 && (a2 & 0xFFFF000000000000uLL) != 0 )
    {
      (*(void (__fastcall **)(__int64, __int64 *, int *))(*(_QWORD *)qword_149B4FCF8 + 248LL))(
        qword_149B4FCF8,
        &v16,
        &v14);
      v4 = a2 & 0xFFFFFFD003FFLL;
      v5 = *(_DWORD *)(((HIWORD(a2) & (unsigned int)(v14 - 1)) << 9) + v16 + 292);
      if ( v5 != -1 )
        v4 |= (unsigned __int64)v5 << 48;
    }
    v6 = _InterlockedCompareExchange64((volatile signed __int64 *)a1, v4, a2);
    if ( a2 == v6 )
      break;
    a2 = v6;
  }
  if ( (a2 & 0x3FF) != 0 )
  {
    if ( (a2 & 0x100000) != 0 )
      qword_149B3B490(a1);
    if ( (a2 & 0xFFFF00000000LL) != 0 )
    {
      v7 = qword_149B4FCF8;
      (*(void (__fastcall **)(__int64, __int64 *, int *))(*(_QWORD *)qword_149B4FCF8 + 248LL))(
        qword_149B4FCF8,
        &v15,
        &v13);
      v8 = v15 + ((WORD2(a2) & (unsigned __int64)(unsigned int)(v13 - 1)) << 9);
      LODWORD(a2) = *(_DWORD *)(v8 + 292);
      *(_DWORD *)(v8 + 284) = (unsigned __int16)(WORD2(a2) + v13);
      (*(void (__fastcall **)(__int64))(*(_QWORD *)v7 + 216LL))(v7);
      while ( (_DWORD)a2 != -1 )
      {
        v9 = (unsigned __int16)(a2 + v13);
        v10 = v15 + ((unsigned __int64)((unsigned int)a2 & (v13 - 1)) << 9);
        LODWORD(a2) = *(_DWORD *)(v10 + 292);
        *(_DWORD *)(v10 + 284) = v9;
        (*(void (__fastcall **)(__int64))(*(_QWORD *)v7 + 216LL))(v7);
      }
    }
  }
  else if ( (a2 & 0xFFC00000) != 0 )
  {
    qword_149B3B488(a1);
  }
  else if ( (a2 & 0xFFFF000000000000uLL) != 0 )
  {
    (*(void (__fastcall **)(__int64, __int64 *, int *))(*(_QWORD *)qword_149B4FCF8 + 248LL))(
      qword_149B4FCF8,
      &v15,
      &v13);
    v11 = HIWORD(a2);
    *(_DWORD *)(((unsigned __int64)((unsigned int)v11 & (v13 - 1)) << 9) + v15 + 284) = (unsigned __int16)(v11 + v13);
    (*(void (__fastcall **)(__int64, _QWORD))(*(_QWORD *)qword_149B4FCF8 + 216LL))(qword_149B4FCF8, (unsigned int)v11);
  }
  p_Source = &Source;
  *(_QWORD *)(a1 + 8) = &Source;
  return p_Source;
}

// --- End Function: sub_1403DD380 (0x1403DD380) ---

// --- Function: sub_14088A820 (0x14088A820) ---
char __fastcall sub_14088A820(__int64 a1)
{
  if ( *(_QWORD *)a1 )
    return (*(__int64 (__fastcall **)(__int64, _QWORD, _QWORD))(*(_QWORD *)qword_149B4FCF8 + 144LL))(
             qword_149B4FCF8,
             *(_QWORD *)a1,
             *(unsigned int *)(a1 + 8));
  else
    return 0;
}

// --- End Function: sub_14088A820 (0x14088A820) ---

// --- Function: sub_1414B39A0 (0x1414B39A0) ---
char __fastcall sub_1414B39A0(__int64 *a1)
{
  __int64 v1; // rbx
  int v3; // esi
  unsigned int v4; // eax
  char v5; // di
  int v6; // eax
  unsigned __int32 v8; // eax

  v1 = *a1;
  if ( !*a1 )
    return 1;
  v3 = *(_DWORD *)(NtCurrentTeb_w() + 24);
  if ( *(_DWORD *)(v1 + 16) == v3 )
  {
    ++*(_DWORD *)(v1 + 20);
  }
  else
  {
    v4 = _InterlockedCompareExchange((volatile signed __int32 *)v1, 1, 0);
    if ( v4 )
      sub_1403C33A0(v1, v4, (__int64)"CFutureHandle::IsFinished", 1);
    else
      *(_QWORD *)(v1 + 8) = *(_QWORD *)(NtCurrentTeb_w() + 32);
    *(_DWORD *)(v1 + 16) = v3;
  }
  v5 = *(_BYTE *)(*a1 + 56);
  v6 = *(_DWORD *)(v1 + 20);
  if ( v6 )
  {
    *(_DWORD *)(v1 + 20) = v6 - 1;
    return v5;
  }
  else
  {
    *(_DWORD *)(v1 + 16) = -1;
    v8 = _InterlockedCompareExchange((volatile signed __int32 *)v1, 0, 1);
    if ( v8 == 1 )
      *(_QWORD *)(v1 + 8) = &Source;
    else
      sub_1403DB1F0(v1, v8);
    return v5;
  }
}

// --- End Function: sub_1414B39A0 (0x1414B39A0) ---

// --- Function: sub_142C0AB10 (0x142C0AB10) ---
_BOOL8 __fastcall sub_142C0AB10(_QWORD *a1)
{
  return *a1 == a1[1];
}

// --- End Function: sub_142C0AB10 (0x142C0AB10) ---

// --- Function: sub_1453D2D50 (0x1453D2D50) ---
__int64 __fastcall sub_1453D2D50(__int64 a1, __int64 a2)
{
  sub_1453D3590(a1, a2);
  return a1;
}

// --- End Function: sub_1453D2D50 (0x1453D2D50) ---

// --- Function: sub_1453D2D80 (0x1453D2D80) ---
__int64 __fastcall sub_1453D2D80(__int64 a1, _BYTE *dst)
{
  __int64 v2; // rax
  __int64 result; // rax
  _BYTE dst_[40]; // [rsp+30h] [rbp-28h] BYREF

  qmemcpy(dst_, dst, 0x10u);
  sub_1453D2D50(a1, (__int64)dst_);
  if ( !qword_149E5AF40 )
  {
    v2 = sub_1402A24F0((__int64)&qword_149B4FBE0);
    (*(void (__fastcall **)(_QWORD, __int64 *))(**(_QWORD **)(v2 + 280) + 176LL))(
      *(_QWORD *)(v2 + 280),
      &qword_149E5AF40);
  }
  result = a1;
  *(_QWORD *)(a1 + 48) = qword_149E5AF40;
  return result;
}

// --- End Function: sub_1453D2D80 (0x1453D2D80) ---

// --- Function: sub_1453D3590 (0x1453D3590) ---
_QWORD *__fastcall sub_1453D3590(_QWORD *a1, const void *src)
{
  _QWORD *result; // rax

  sub_1402A2AD0(a1);
  qmemcpy((void *)sub_1402A2B80(16, (__int64)(a1 + 2)), src, 0x10u);
  *a1 = sub_14540B9B0;
  result = a1;
  a1[1] = sub_14540D330;
  return result;
}

// --- End Function: sub_1453D3590 (0x1453D3590) ---

// --- Function: ??$?8$$CBU_EXCEPTION_RECORD@@$$CBU0@@std@@YA_NAEBV?$shared_pt_w (0x1453FBD20) ---
bool __fastcall sub_1453FBD20(_QWORD *a1, _QWORD *a2)
{
  return !std::operator==<_EXCEPTION_RECORD const,_EXCEPTION_RECORD const>(a1, a2);
}

// --- End Function: ??$?8$$CBU_EXCEPTION_RECORD@@$$CBU0@@std@@YA_NAEBV?$shared_pt_w (0x1453FBD20) ---

// --- Function: sub_145403240 (0x145403240) ---
unsigned __int64 __fastcall sub_145403240(_QWORD *a1)
{
  __int64 v1; // rax
  __int64 v2; // rax
  __int64 v3; // rax
  __int64 v4; // rax
  __int64 v5; // rax
  __int64 v6; // r9
  __int64 v7; // rax
  unsigned __int64 result; // rax
  _BYTE v9[4]; // [rsp+42h] [rbp-616h] BYREF
  unsigned __int16 v10; // [rsp+46h] [rbp-612h]
  __int64 v11; // [rsp+48h] [rbp-610h] BYREF
  _QWORD *v12; // [rsp+50h] [rbp-608h]
  BOOL v13; // [rsp+58h] [rbp-600h]
  BOOL v14; // [rsp+5Ch] [rbp-5FCh]
  BOOL v15; // [rsp+60h] [rbp-5F8h]
  __int64 v16; // [rsp+68h] [rbp-5F0h]
  __int64 v17; // [rsp+70h] [rbp-5E8h]
  _BYTE v18[8]; // [rsp+78h] [rbp-5E0h] BYREF
  __int64 v19; // [rsp+80h] [rbp-5D8h]
  __int64 v20; // [rsp+88h] [rbp-5D0h]
  __int64 v21; // [rsp+90h] [rbp-5C8h]
  unsigned __int8 v22; // [rsp+98h] [rbp-5C0h]
  __int64 v23; // [rsp+A0h] [rbp-5B8h]
  __int64 *v24; // [rsp+A8h] [rbp-5B0h]
  __int64 v25; // [rsp+B0h] [rbp-5A8h]
  __int64 v26; // [rsp+B8h] [rbp-5A0h]
  __int64 v27; // [rsp+C0h] [rbp-598h]
  _QWORD *v28; // [rsp+C8h] [rbp-590h]
  __int64 v29; // [rsp+D0h] [rbp-588h]
  __int64 v30; // [rsp+D8h] [rbp-580h]
  __int64 v31; // [rsp+E0h] [rbp-578h]
  __int64 v32; // [rsp+E8h] [rbp-570h]
  __int64 v33; // [rsp+F0h] [rbp-568h]
  __int64 v34; // [rsp+F8h] [rbp-560h]
  __int64 v35; // [rsp+100h] [rbp-558h]
  __int64 v36; // [rsp+108h] [rbp-550h]
  __int64 v37; // [rsp+110h] [rbp-548h]
  _BYTE *v38; // [rsp+118h] [rbp-540h]
  __int64 (__fastcall ***v39)(_QWORD); // [rsp+120h] [rbp-538h]
  __int64 v40; // [rsp+128h] [rbp-530h]
  __int64 v41; // [rsp+130h] [rbp-528h]
  __int64 v42; // [rsp+138h] [rbp-520h]
  __int64 *v43; // [rsp+140h] [rbp-518h]
  __int64 v44; // [rsp+148h] [rbp-510h]
  __int64 v45; // [rsp+150h] [rbp-508h]
  void (__fastcall *v46)(__int64, __int64, __int64 *); // [rsp+158h] [rbp-500h]
  __int64 v47; // [rsp+160h] [rbp-4F8h]
  __int64 v48; // [rsp+168h] [rbp-4F0h]
  __int64 v49; // [rsp+170h] [rbp-4E8h]
  __int64 v50; // [rsp+178h] [rbp-4E0h]
  const char *p_SEAPlayerLoadoutSnapshots; // [rsp+180h] [rbp-4D8h]
  __int64 v52; // [rsp+188h] [rbp-4D0h]
  __int64 v53; // [rsp+190h] [rbp-4C8h]
  __int64 v54; // [rsp+198h] [rbp-4C0h]
  __int64 v55; // [rsp+1A0h] [rbp-4B8h]
  __int64 v56; // [rsp+1A8h] [rbp-4B0h]
  __int64 v57; // [rsp+1B0h] [rbp-4A8h]
  __int64 (__fastcall *v58)(__int64, __int64); // [rsp+1B8h] [rbp-4A0h]
  __int64 v59; // [rsp+1C0h] [rbp-498h]
  __int64 (__fastcall *v60)(__int64, __int64); // [rsp+1C8h] [rbp-490h]
  __int64 (__fastcall *v61)(__int64, _BYTE *); // [rsp+1D0h] [rbp-488h]
  __int64 v62; // [rsp+1D8h] [rbp-480h]
  __int64 v63; // [rsp+1E0h] [rbp-478h]
  const char *v64; // [rsp+1E8h] [rbp-470h]
  __int64 v65; // [rsp+1F0h] [rbp-468h]
  char *v66; // [rsp+1F8h] [rbp-460h]
  _QWORD v67[2]; // [rsp+200h] [rbp-458h] BYREF
  __int64 v68; // [rsp+210h] [rbp-448h]
  __int64 v69; // [rsp+218h] [rbp-440h]
  __int64 v70; // [rsp+220h] [rbp-438h]
  __int64 v71; // [rsp+228h] [rbp-430h]
  __int64 v72; // [rsp+230h] [rbp-428h] BYREF
  __int64 v73; // [rsp+238h] [rbp-420h]
  __int64 v74; // [rsp+240h] [rbp-418h]
  _BYTE *v75; // [rsp+248h] [rbp-410h]
  __int64 v76; // [rsp+250h] [rbp-408h]
  _QWORD *v77; // [rsp+258h] [rbp-400h]
  void (__fastcall *v78)(__int64, _BYTE *); // [rsp+260h] [rbp-3F8h]
  _BYTE *v79; // [rsp+268h] [rbp-3F0h]
  _BYTE v80[8]; // [rsp+270h] [rbp-3E8h] BYREF
  __int64 (__fastcall *v81)(__int64, _BYTE *); // [rsp+278h] [rbp-3E0h]
  __int64 v82; // [rsp+280h] [rbp-3D8h]
  _BYTE *v83; // [rsp+288h] [rbp-3D0h]
  _QWORD *v84; // [rsp+290h] [rbp-3C8h]
  _BYTE *v85; // [rsp+298h] [rbp-3C0h]
  __int64 v86; // [rsp+2A0h] [rbp-3B8h]
  __int64 v87; // [rsp+2A8h] [rbp-3B0h]
  __int64 v88; // [rsp+2B0h] [rbp-3A8h]
  _BYTE v89[16]; // [rsp+2B8h] [rbp-3A0h] BYREF
  _BYTE v90[16]; // [rsp+2C8h] [rbp-390h] BYREF
  _BYTE v91[24]; // [rsp+2D8h] [rbp-380h] BYREF
  ULONG_PTR Parameter[4]; // [rsp+2F0h] [rbp-368h] BYREF
  __int64 v93; // [rsp+310h] [rbp-348h]
  __int64 v94; // [rsp+318h] [rbp-340h] BYREF
  __int64 v95; // [rsp+320h] [rbp-338h]
  _QWORD v96[3]; // [rsp+330h] [rbp-328h] BYREF
  _BYTE v97[16]; // [rsp+348h] [rbp-310h] BYREF
  _BYTE *v98; // [rsp+358h] [rbp-300h]
  __int64 v99; // [rsp+360h] [rbp-2F8h]
  char v100; // [rsp+368h] [rbp-2F0h] BYREF
  __int64 v101; // [rsp+370h] [rbp-2E8h]
  _BYTE v102[16]; // [rsp+378h] [rbp-2E0h] BYREF
  _BYTE v103[16]; // [rsp+388h] [rbp-2D0h] BYREF
  _QWORD v104[3]; // [rsp+398h] [rbp-2C0h] BYREF
  _QWORD v105[3]; // [rsp+3B0h] [rbp-2A8h] BYREF
  __int64 (__fastcall *p_p_sub_140AB6CD0[3])(); // [rsp+3C8h] [rbp-290h] BYREF
  _BYTE v107[32]; // [rsp+3E0h] [rbp-278h] BYREF
  _BYTE v108[24]; // [rsp+400h] [rbp-258h] BYREF
  _BYTE v109[56]; // [rsp+418h] [rbp-240h] BYREF
  _QWORD v110[2]; // [rsp+450h] [rbp-208h] BYREF
  _BYTE v111[40]; // [rsp+460h] [rbp-1F8h] BYREF
  _BYTE v112[56]; // [rsp+488h] [rbp-1D0h] BYREF
  _BYTE v113[256]; // [rsp+4C0h] [rbp-198h] BYREF
  _BYTE v114[16]; // [rsp+5C0h] [rbp-98h] BYREF
  __int64 v115; // [rsp+5D0h] [rbp-88h]
  _BYTE v116[16]; // [rsp+5D8h] [rbp-80h] BYREF
  __int64 v117; // [rsp+5E8h] [rbp-70h]
  _BYTE v118[16]; // [rsp+5F0h] [rbp-68h] BYREF
  _BYTE v119[64]; // [rsp+600h] [rbp-58h] BYREF

  v88 = *a1 + 8LL;
  v21 = v88;
  v22 = 1;
  v44 = v88;
  sub_1402DE3A0(
    v88,
    (__int64)"CFrontendEntitlements::FetchAllEntitlements::<lambda_1>::operator ()",
    (__int64)"m_accessLock",
    1);
  sub_145462040(*a1 + 56LL);
  unknown_libname_472(&v94);
  v23 = sub_1402C7230();
  v19 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v23 + 576LL))(v23);
  v46 = *(void (__fastcall **)(__int64, __int64, __int64 *))(*(_QWORD *)v19 + 272LL);
  v45 = sub_142343640();
  v46(v19, v45, &v94);
  sub_1426FC500(v91);
  v24 = &v94;
  sub_14381D0B0(v91, (v95 - v94) >> 3);
  v43 = &v94;
  v16 = v94;
  v47 = v95;
  while ( v16 != v47 )
  {
    v48 = v16;
    v1 = sub_1402A2660(v16);
    sub_140425520(v19, v114, v1);
    v49 = v115;
    v13 = v115 != 0;
    if ( v115 )
    {
      v50 = v115;
      if ( *(_DWORD *)(v115 + 8) != -1 )
        v99 = sub_142E9B490(v91, v114);
    }
    v16 += 8;
  }
  sub_142EB6EF0(v90, v9);
  v25 = sub_1402C7230();
  v52 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v25 + 576LL))(v25);
  p_SEAPlayerLoadoutSnapshots = "SEAPlayerLoadoutSnapshots";
  sub_142B98510(v52, v116, "SEAPlayerLoadoutSnapshots", "EAPlayerLoadoutSnapshots");
  v53 = v117;
  v14 = v117 != 0;
  if ( v117 )
  {
    v54 = v117;
    v55 = v117;
    v26 = sub_143F22C90(v117, 20);
    if ( v26 )
    {
      v27 = *(_QWORD *)(v26 + 8);
      if ( v27 )
      {
        sub_140459A70(v108);
        sub_1405B1FF0(v27, (unsigned int)v108, 0, 0, 0, 0);
        sub_1432DE3A0(Parameter);
        _StarEngineModule__((ULONG_PTR)Parameter);
        sub_1453DB600(Parameter, v109);
        while ( 1 )
        {
          v15 = v93 == 0;
          if ( !v93 )
            break;
          v2 = sub_143DD5C60(Parameter);
          sub_1402FAA80(v105, v2);
          sub_145464980(Parameter);
          v28 = v105;
          v17 = v105[0];
          v56 = v105[1];
          while ( v17 != v56 )
          {
            v35 = v17;
            v29 = *(_QWORD *)(sub_1402A24F0((__int64)&qword_149B4FBE0) + 160);
            v30 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v29 + 192LL))(v29);
            v58 = *(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)v30 + 32LL);
            v57 = sub_1402A2660(v35 + 72);
            v11 = v58(v30, v57);
            if ( v11 )
            {
              v31 = *(_QWORD *)(sub_1402A24F0((__int64)&qword_149B4FBE0) + 152);
              v60 = *(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)v31 + 632LL);
              v59 = v11;
              v32 = v60(v31, v11);
              if ( v32 )
              {
                sub_1453EC6E0(v90, v102, &v11);
                if ( v102[8] )
                {
                  v61 = *(__int64 (__fastcall **)(__int64, _BYTE *))(*(_QWORD *)v11 + 16LL);
                  v3 = v61(v11, v118);
                  sub_1402C4680(v119, v3);
                  v62 = *a1;
                  sub_145416950(v62, v67);
                  v63 = a1[1];
                  v68 = v63;
                  v69 = v11;
                  v66 = &v100;
                  sub_14035B3E0(&v72);
                  v65 = v4;
                  v64 = (const char *)AK::WriteBytesMem::Bytes((AK::WriteBytesMem *)v119);
                  v5 = sub_1403A9130(v65, "urn:sc:playerloadout:entitlement::%s", v64);
                  v70 = sub_14035B160(v66, v5);
                  v67[1] = v67[0];
                  v71 = v67[0];
                  LOBYTE(v6) = 8;
                  sub_1453F1A10(v113, v67[0], v70, v6, v69, v32, v68);
                  sub_140370D10(&v72);
                  v10 = *(_WORD *)sub_1404B2370(v18);
                  v33 = sub_1405B3ED0(v11, v10);
                  if ( v33 )
                  {
                    v34 = *(_QWORD *)(v33 + 24);
                    if ( v34 )
                      sub_1405B1FF0(v34, (unsigned int)v113, 0, 0, 0, 0);
                  }
                  v73 = *a1 + 56LL;
                  sub_1453EBCF0(v73, v113);
                  sub_144A29030(v113);
                  sub_1402B18C0(v119);
                }
              }
            }
            _StarEngineModule__((ULONG_PTR)Parameter);
            sub_1453DB600(Parameter, v35);
            v17 += 136;
          }
          sub_1403E0FB0(v105);
        }
        sub_1453F7D50(Parameter);
        sub_140465A50(v108);
      }
    }
  }
  sub_142BAC4A0(v89);
  v36 = *(_QWORD *)(sub_1402A24F0((__int64)&qword_149B4FBE0) + 160);
  v37 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v36 + 192LL))(v36);
  v78 = *(void (__fastcall **)(__int64, _BYTE *))(*(_QWORD *)v37 + 112LL);
  v76 = sub_1402A24F0((__int64)v80);
  v74 = *a1;
  v96[0] = v74;
  v96[1] = a1[1];
  v96[2] = v89;
  v75 = v97;
  sub_1453EEA40(v97, v90);
  v98 = v91;
  v77 = v96;
  sub_1453D1ED0(v103, v96, v76);
  v78(v37, v103);
  v38 = v97;
  v79 = v97;
  sub_142EA21A0(v97, v97);
  sub_1402A2B70(v80);
  v39 = *(__int64 (__fastcall ****)(_QWORD))(sub_1402A24F0((__int64)&qword_149B4FBE0) + 392);
  v40 = (**v39)(v39);
  v20 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v40 + 216LL))(v40);
  v9[1] = 0;
  v9[2] = 0;
  if ( v20 )
  {
    v81 = *(__int64 (__fastcall **)(__int64, _BYTE *))(*(_QWORD *)v20 + 8LL);
    v86 = v81(v20, v107);
    v12 = v110;
    v82 = *a1;
    v110[0] = v82;
    v110[1] = a1[1];
    v83 = v111;
    sub_14282BD80(v111, v91);
    v84 = v12 + 5;
    sub_1453EEA10(v12 + 5, v89);
    v85 = v112;
    v7 = sub_1453ED9D0(v112, v12);
    sub_1453D2B20(p_p_sub_140AB6CD0, v7);
    sub_1453F7490(v12);
    v87 = sub_140B29070(v86, v104, p_p_sub_140AB6CD0);
    sub_1403798D0(*a1 + 160LL, v87);
    std::shared_ptr<std::vector<char>>::~shared_ptr<std::vector<char>>((std::shared_ptr<std::vector<char> > *)v104);
    sub_1402A2AD0(p_p_sub_140AB6CD0);
    sub_140370B50(v107);
  }
  else
  {
    v41 = v101;
    v41 = *(_QWORD *)(*a1 + 64LL);
    v42 = v104[2];
    v42 = *(_QWORD *)(*a1 + 56LL);
    sub_1453ECF40(v42, v41, v9[3]);
    sub_145412110(*a1);
    sub_14542D8E0(*a1);
  }
  sub_142EC45C0(v89);
  sub_142EC4590(v90);
  sub_14277CC40(v91);
  result = sub_1404634D0(&v94);
  if ( v21 )
  {
    result = v22;
    if ( v22 )
      return sub_1402DE4A0(v21);
  }
  return result;
}

// --- End Function: sub_145403240 (0x145403240) ---

// --- Function: sub_14540B9B0 (0x14540B9B0) ---
unsigned __int64 __fastcall sub_14540B9B0(__int64 a1)
{
  return sub_145403240((_QWORD *)(a1 + 16));
}

// --- End Function: sub_14540B9B0 (0x14540B9B0) ---

// --- Function: sub_14540D330 (0x14540D330) ---
unsigned __int64 (__fastcall **__fastcall sub_14540D330(
        int n2,
        unsigned __int64 (__fastcall **a2)(__int64 a1),
        unsigned __int64 (__fastcall **a3)(__int64 a1)))(__int64 a1)
{
  unsigned __int64 (__fastcall **result)(__int64); // rax

  if ( n2 )
  {
    if ( n2 == 1 )
    {
      result = a3;
      if ( *a3 )
      {
        if ( a3[1] == (unsigned __int64 (__fastcall *)(__int64))1 )
        {
          *a2 = *a3;
          a2[1] = (unsigned __int64 (__fastcall *)(__int64))1;
        }
        else
        {
          qmemcpy((void *)sub_1402A2B80(16, (__int64)(a2 + 2)), a3 + 2, 0x10u);
          *a2 = *a3;
          a2[1] = a3[1];
        }
        *a3 = 0;
        result = a3;
        a3[1] = 0;
      }
    }
    else if ( n2 == 2 )
    {
      *a2 = 0;
      result = a2;
      a2[1] = 0;
    }
    else
    {
      return 0;
    }
  }
  else
  {
    result = a3;
    if ( *a3 )
    {
      if ( a3[1] == (unsigned __int64 (__fastcall *)(__int64))1 )
      {
        *a2 = *a3;
        result = a2;
        a2[1] = (unsigned __int64 (__fastcall *)(__int64))1;
      }
      else
      {
        qmemcpy((void *)sub_1402A2B80(16, (__int64)(a2 + 2)), a3 + 2, 0x10u);
        *a2 = sub_14540B9B0;
        result = a2;
        a2[1] = (unsigned __int64 (__fastcall *)(__int64))sub_14540D330;
      }
    }
  }
  return result;
}

// --- End Function: sub_14540D330 (0x14540D330) ---

// --- Function: sub_145413200 (0x145413200) ---
__int64 __fastcall sub_145413200(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 result; // rax
  __int64 v5; // rdx
  __int64 v6; // [rsp+20h] [rbp-D8h]
  __int64 v7; // [rsp+30h] [rbp-C8h]
  __int64 v8; // [rsp+38h] [rbp-C0h]
  __int64 v9; // [rsp+50h] [rbp-A8h]
  _QWORD src_[2]; // [rsp+60h] [rbp-98h] BYREF
  _BYTE dst[16]; // [rsp+70h] [rbp-88h] BYREF
  _QWORD v12[3]; // [rsp+80h] [rbp-78h] BYREF
  _BYTE v13[96]; // [rsp+98h] [rbp-60h] BYREF

  v6 = a1 + 8;
  LOBYTE(a4) = 1;
  sub_1402DE3A0(a1 + 8, "CFrontendEntitlements::FetchAllEntitlements", "m_accessLock", a4);
  result = (unsigned __int8)sub_142C0AB10(a1 + 56);
  if ( (_BYTE)result )
  {
    result = (unsigned __int8)sub_145426FF0(a1);
    if ( !(_BYTE)result )
    {
      v7 = *(_QWORD *)(sub_1402A24F0(&qword_149B4FBE0) + 96);
      v9 = *(_QWORD *)(*(__int64 (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v7 + 56LL))(v7, 0);
      LOBYTE(v5) = 79;
      sub_14036A240(v12, v5, "CFrontendEntitlements::FetchAllEntitlements");
      v12[0] = a1 + 176;
      src_[0] = a1;
      src_[1] = v9;
      qmemcpy(dst, src_, sizeof(dst));
      sub_1453D2D80(v13, dst);
      v8 = *(_QWORD *)(sub_1402A24F0(&qword_149B4FBE0) + 280);
      (*(void (__fastcall **)(__int64, _QWORD *))(*(_QWORD *)v8 + 136LL))(v8, v12);
      result = sub_1402A2AD0(v13);
    }
  }
  if ( v6 )
    return sub_1402DE4A0(v6);
  return result;
}

// --- End Function: sub_145413200 (0x145413200) ---

// --- Function: sub_1454133A0 (0x1454133A0) ---
__int64 __fastcall sub_1454133A0(__int64 a1, __int64 a2)
{
  __int64 v2; // rdx
  __int64 v3; // r8
  __int64 v4; // r9
  __int64 v6; // [rsp+28h] [rbp-A0h]
  __int64 v7; // [rsp+38h] [rbp-90h]
  __int64 v8; // [rsp+68h] [rbp-60h]
  _BYTE v9[24]; // [rsp+80h] [rbp-48h] BYREF
  _BYTE v10[32]; // [rsp+98h] [rbp-30h] BYREF
  __int64 v11; // [rsp+B8h] [rbp-10h]

  v7 = a1 + 8;
  sub_1402DE3A0(a1 + 8, (__int64)"CFrontendEntitlements::FetchAndQueryAllItemEntitlements", (__int64)"m_accessLock", 1);
  sub_145413200(a1, v2, v3, v4);
  if ( (unsigned __int8)sub_145426FF0(a1) )
  {
    sub_1453F6200(v10);
    sub_1427049D0(v10, a2);
    v10[29] = 1;
    _StarEngineModule__(a1 + 104);
    sub_1453DB7D0(a1 + 104, v10);
    sub_142D11710(a1 + 104);
    sub_142718D20(v10);
  }
  else
  {
    sub_1426FC570(v9);
    sub_145466D80(v9, (*(_QWORD *)(a1 + 64) - *(_QWORD *)(a1 + 56)) / 248LL);
    v6 = *(_QWORD *)(a1 + 56);
    v8 = *(_QWORD *)(a1 + 64);
    while ( v6 != v8 )
    {
      if ( !*(_QWORD *)(v6 + 208) )
        v11 = sub_1453DC2D0(v9, v6);
      v6 += 248;
    }
    if ( *(_QWORD *)(a2 + 8) == 1 )
      (*(void (__fastcall **)(_BYTE *))a2)(v9);
    else
      (*(void (__fastcall **)(__int64, _BYTE *))a2)(a2, v9);
    sub_14545F350(v9);
  }
  if ( v7 )
    sub_1402DE4A0(v7);
  return sub_142718D20(a2);
}

// --- End Function: sub_1454133A0 (0x1454133A0) ---

// --- Function: sub_145413600 (0x145413600) ---
__int64 __fastcall sub_145413600(__int64 a1, __int64 a2, unsigned int a3)
{
  __int64 v3; // rdx
  __int64 v4; // r8
  __int64 v5; // r9
  __int64 v7; // [rsp+28h] [rbp-A0h]
  __int64 v8; // [rsp+40h] [rbp-88h]
  __int64 v9; // [rsp+68h] [rbp-60h]
  _BYTE v10[24]; // [rsp+80h] [rbp-48h] BYREF
  _BYTE v11[24]; // [rsp+98h] [rbp-30h] BYREF
  unsigned int v12; // [rsp+B0h] [rbp-18h]
  char v13; // [rsp+B4h] [rbp-14h]
  char v14; // [rsp+B6h] [rbp-12h]
  __int64 v15; // [rsp+B8h] [rbp-10h]

  v8 = a1 + 8;
  sub_1402DE3A0(
    a1 + 8,
    (__int64)"CFrontendEntitlements::FetchAndQueryAllVehicleEntitlements",
    (__int64)"m_accessLock",
    1);
  sub_145413200(a1, v3, v4, v5);
  if ( (unsigned __int8)sub_145426FF0(a1) )
  {
    sub_1453F6200(v11);
    sub_1427049D0(v11, a2);
    v12 = a3;
    v14 = 1;
    v13 = 1;
    _StarEngineModule__(a1 + 104);
    sub_1453DB7D0(a1 + 104, v11);
    sub_142D11710(a1 + 104);
    sub_142718D20(v11);
  }
  else
  {
    sub_1426FC570(v10);
    sub_145466D80(v10, (*(_QWORD *)(a1 + 64) - *(_QWORD *)(a1 + 56)) / 248LL);
    v7 = *(_QWORD *)(a1 + 56);
    v9 = *(_QWORD *)(a1 + 64);
    while ( v7 != v9 )
    {
      if ( (unsigned __int8)sub_1441E9C10(a3, *(_QWORD *)(v7 + 216)) && *(_QWORD *)(v7 + 208) )
        v15 = sub_1453DC2D0(v10, v7);
      v7 += 248;
    }
    if ( *(_QWORD *)(a2 + 8) == 1 )
      (*(void (__fastcall **)(_BYTE *))a2)(v10);
    else
      (*(void (__fastcall **)(__int64, _BYTE *))a2)(a2, v10);
    sub_14545F350(v10);
  }
  if ( v8 )
    sub_1402DE4A0(v8);
  return sub_142718D20(a2);
}

// --- End Function: sub_145413600 (0x145413600) ---

// --- Function: sub_145426FF0 (0x145426FF0) ---
_BOOL8 __fastcall sub_145426FF0(__int64 *a1)
{
  bool v2; // [rsp+24h] [rbp-34h]
  __int64 v3; // [rsp+38h] [rbp-20h]

  v3 = (__int64)(a1 + 1);
  sub_1402D2710((__int64)(a1 + 1), (__int64)"CFrontendEntitlements::IsRunningAsyncJobs", (__int64)"m_accessLock", 1);
  v2 = !sub_1414B39A0(a1 + 18)
    || !sub_1414B39A0(a1 + 20)
    || sub_14088A820((__int64)(a1 + 22))
    || std::operator==<_EXCEPTION_RECORD const,_EXCEPTION_RECORD const>(a1 + 24, qword_149E5A868);
  sub_1402D2790(v3);
  return v2;
}

// --- End Function: sub_145426FF0 (0x145426FF0) ---

// --- Function: sub_145441740 (0x145441740) ---
__int64 __fastcall sub_145441740(__int64 a1, int a2)
{
  __int64 v2; // rax
  __int64 v3; // rdx
  __int64 v4; // r8
  __int64 v5; // r9
  __int64 v6; // rax
  __int64 v7; // rax
  __int64 result; // rax
  char v9[8]; // [rsp+28h] [rbp-20h] BYREF
  __int64 v10; // [rsp+30h] [rbp-18h]
  __int64 v11; // [rsp+38h] [rbp-10h]

  if ( a2 != 1 )
    return sub_1454164A0(a1 + 496);
  v10 = sub_1402A24F0((__int64)&qword_149B4FBE0);
  if ( !*(_BYTE *)(v10 + 1526)
    && sub_1464E7930(qword_149E7E438)
    && ((v2 = sub_1464E7930(qword_149E7E438), (unsigned __int8)sub_146485260(v2))
     || (v6 = sub_1464E7930(qword_149E7E438), (unsigned int)sub_146481D90(v6) == -3)) )
  {
    sub_145413200(a1 + 496, v3, v4, v5);
  }
  else
  {
    sub_1454164A0(a1 + 496);
  }
  if ( !sub_144D1CB20() )
    sub_144CA44A0();
  v11 = a1 + 272;
  v7 = sub_14035C4A0(v9, 1);
  sub_1453D5500(v11, v7);
  result = a1;
  *(_DWORD *)(a1 + 1084) = 1;
  return result;
}

// --- End Function: sub_145441740 (0x145441740) ---

