// Decompiled code dump generated by Code Dumper (Callers/Callees/Refs)
// Start Function: 0x14723E730 (sub_14723E730)
// Caller Depth: 0
// Callee/Ref Depth: 2
// Total Functions Found: 33
// ------------------------------------------------------------

// --- Function: LogTraceConditional (0x1402C30B0) ---
// Logs a formatted message with level 3 if global logging flags `qword_14981D3D8`
// and `Parameter_3` are enabled and the global logger object `qword_14981D2D0` is
// available. Calls the virtual function at offset +8 of the logger object.
void LogTraceConditional(const char *format_string, ...)
{
  va_list va; // [rsp+38h] [rbp+10h] BYREF

  va_start(va, format_string);
  if ( qword_149A143C8 && qword_149A142B0 )
  {
    if ( qword_149A142C0 )
      (*(void (__fastcall **)(__int64, __int64, const char *, __int64 *))(*(_QWORD *)qword_149A142C0 + 8LL))(
        qword_149A142C0,
        3,
        format_string,
        (__int64 *)va);
  }
}

// --- End Function: LogTraceConditional (0x1402C30B0) ---

// --- Function: NtCurrentTeb_w (0x1402C8360) ---
__int64 sub_1402C8360()
{
  return *((_QWORD *)NtCurrentTeb()->ThreadLocalStoragePointer + (unsigned int)TlsIndex) + 0x310LL;
}

// --- End Function: NtCurrentTeb_w (0x1402C8360) ---

// --- Function: sprintf (0x1402FB850) ---
int sprintf(char *Dest, const char *Format, ...)
{
  __int64 *v4; // rax
  int result; // eax
  va_list va; // [rsp+60h] [rbp+18h] BYREF

  va_start(va, Format);
  v4 = sub_1402A6A10();
  result = _stdio_common_vsprintf(*v4 | 1, Dest, 0xFFFFFFFFFFFFFFFFuLL, Format, 0, va);
  if ( result < 0 )
    return 0xFFFFFFFF;
  return result;
}

// --- End Function: sprintf (0x1402FB850) ---

// --- Function: sub_1402FB9F0 (0x1402FB9F0) ---
char *__fastcall sub_1402FB9F0(__int64 *a1, _BYTE *a2, char *a3)
{
  char *v3; // r14
  __int64 v4; // rax
  unsigned __int64 allocSize; // rbx
  unsigned __int64 v9; // rcx
  unsigned __int64 v10; // r15
  unsigned __int64 v11; // rdx
  unsigned __int64 allocSize_1; // rcx
  __int64 v13; // rax
  __int64 v14; // rdi
  char *v15; // r14
  void *v16; // rcx
  __int64 v17; // r8
  const void *v18; // rdx
  size_t Size; // r8

  v3 = &a2[-*a1];
  v4 = a1[1] - *a1;
  allocSize = 0x7FFFFFFFFFFFFFFFLL;
  if ( v4 == 0x7FFFFFFFFFFFFFFFLL )
    unknown_libname_10();
  v9 = a1[2] - *a1;
  v10 = v4 + 1;
  v11 = v9 >> 1;
  if ( v9 <= 0x7FFFFFFFFFFFFFFFLL - (v9 >> 1) )
  {
    allocSize = v4 + 1;
    if ( v11 + v9 >= v10 )
      allocSize = v11 + v9;
    if ( allocSize < 0x1000 )
    {
      if ( allocSize )
        v14 = sub_1402A63D0(allocSize);
      else
        v14 = 0;
      goto LABEL_15;
    }
    allocSize_1 = allocSize + 0x27;
    if ( allocSize + 0x27 < allocSize )
      sub_1402E2610();
  }
  else
  {
    allocSize_1 = 0x8000000000000026uLL;
  }
  v13 = sub_1402A63D0(allocSize_1);
  if ( !v13 )
    invalid_parameter_noinfo_noreturn();
  v14 = (v13 + 0x27) & 0xFFFFFFFFFFFFFFE0uLL;
  *(_QWORD *)(v14 - 8) = v13;
LABEL_15:
  v15 = &v3[v14];
  v16 = (void *)v14;
  *v15 = *a3;
  v17 = a1[1];
  v18 = (const void *)*a1;
  if ( a2 == (_BYTE *)v17 )
  {
    Size = v17 - (_QWORD)v18;
  }
  else
  {
    memmove((void *)v14, v18, a2 - (_BYTE *)v18);
    v16 = v15 + 1;
    Size = a1[1] - (_QWORD)a2;
    v18 = a2;
  }
  memmove(v16, v18, Size);
  std::vector<signed char>::_Change_array(a1, v14, v10, allocSize);
  return v15;
}

// --- End Function: sub_1402FB9F0 (0x1402FB9F0) ---

// --- Function: is_valid_handle_typeA (0x140310230) ---
// Validates a packed handle/flags value pointed to by `packed_handle_ptr`.
// Extracts the handle (lower 48 bits) and flags (upper 16 bits). Retrieves
// metadata for the handle using `get_handle_metadata`. Checks if the metadata type
// (at offset +4) is 4, or if it's 2 and specific thread conditions are met (TEB
// data exists or `check_handle_state_and_access` passes). Also verifies
// consistency between metadata flags (at offset +2) and the input flags.
bool __fastcall is_valid_handle_typeA(__int64 *a1)
{
  __int64 v1; // rbx
  __int64 v3; // rax
  __int16 n4; // cx

  v1 = *a1;
  if ( !*a1 )
    return 0;
  v3 = sub_1403B6A80(v1 & 0xFFFFFFFFFFFFLL);
  n4 = *(_WORD *)(v3 + 4);
  if ( n4 == 4 || *(_WORD *)(v3 + 2) != (HIWORD(v1) & 0xFFF) )
    return 0;
  if ( n4 != 2 || *(_QWORD *)NtCurrentTeb_w() )
    return check_handle_access_by_state(a1) != 0;
  return 1;
}

// --- End Function: is_valid_handle_typeA (0x140310230) ---

// --- Function: is_valid_handle_typeB (0x1403102C0) ---
// Validates a packed handle (QWORD containing a pointer in the lower 48 bits and
// flags in the upper 16 bits).  Calculates the pointer to the handle's metadata,
// potentially adjusting based on high flag bits (0xF000) using `map_flag_to_mask`.
// Checks if the lower 12 bits of the handle flags match the flags stored in the
// metadata (at offset +2).  If the metadata type (at offset +4) is 2 and certain
// thread state flags are set (checked via TLS offset +37 or
// `is_thread_flag_57_or_38_set`), the handle is considered valid.  Otherwise,
// delegates the validation to `check_handle_access_by_state_extended`.
bool __fastcall is_valid_handle_typeB(unsigned __int64 *a1)
{
  unsigned __int64 v1; // r9
  __int64 v3; // r10
  unsigned __int64 v4; // r9
  __int64 v5; // rax
  __int64 v6; // r10
  __int64 v7; // rbx
  bool v8; // al

  v1 = *a1;
  if ( !*a1 )
    return 0;
  v3 = v1 & 0xFFFFFFFFFFFFLL;
  v4 = HIWORD(v1);
  if ( (v4 & 0xF000) != 0 )
  {
    v5 = map_flag_to_mask(0x2000u);
    v7 = v6 & ~(v5 - 1);
  }
  else
  {
    v7 = v3 - 6;
  }
  if ( *(_WORD *)(v7 + 2) != (v4 & 0xFFF) )
    return 0;
  if ( *(_BYTE *)(NtCurrentTeb_w() + 0x25) || (v8 = is_thread_flag_57_or_38_set()) )
    v8 = 1;
  return *(_WORD *)(v7 + 4) == 2 && v8 || (unsigned __int8)sub_140393CF0(a1) != 0;
}

// --- End Function: is_valid_handle_typeB (0x1403102C0) ---

// --- Function: check_handle_access_by_state (0x140321630) ---
// Checks access permissions for the provided packed handle. Retrieves handle
// metadata using `get_handle_metadata`. Validates access based on the state field
// (metadata + 4): - State 0: Returns false (invalid). - State 1: Checks if the
// handle's payload exists in a thread-local list using
// `check_thread_list_contains_value`. - State 2: Returns true if specific thread
// flags are set (`get_thread_specific_data_offset_784() + 37` or
// `check_thread_flag_57_or_38`), otherwise validates access using
// `validate_access_with_virtual_calls` on the payload. - State 3: Checks thread
// state and compares the payload value against a constant using
// `check_thread_state_and_value_not_equal`. - Other states: Return false.
char __fastcall check_handle_access_by_state(_QWORD *a1)
{
  __int64 v1; // rbx
  __int64 v2; // rax
  __int64 v3; // rax
  __int64 payload_ptr_state2; // rax
  __int64 payload_ptr_state1; // rax

  v1 = *a1 & 0xFFFFFFFFFFFFLL;
  v2 = sub_1403B6A80(v1);
  if ( !*(_WORD *)(v2 + 4) )
    return 0;
  if ( *(_WORD *)(v2 + 4) == 1 )
  {
    payload_ptr_state1 = sub_1403B2980(v1);
    return check_thread_list_contains_value(payload_ptr_state1);
  }
  if ( *(_WORD *)(v2 + 4) != 2 )
  {
    if ( *(_WORD *)(v2 + 4) == 3 )
    {
      v3 = sub_1403B2980(v1);
      return sub_140393B10(v3);
    }
    return 0;
  }
  if ( *(_BYTE *)(NtCurrentTeb_w() + 0x25) || is_thread_flag_57_or_38_set() )
    return 1;
  payload_ptr_state2 = sub_1403B2980(v1);
  return validate_access_with_virtual_calls(payload_ptr_state2);
}

// --- End Function: check_handle_access_by_state (0x140321630) ---

// --- Function: sub_1403B6A80 (0x1403B6A80) ---
__int64 __fastcall sub_1403B6A80(__int64 a1)
{
  return (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(*(_QWORD *)qword_149A14290 + 296LL))(
           qword_149A14290,
           a1,
           0);
}

// --- End Function: sub_1403B6A80 (0x1403B6A80) ---

// --- Function: sub_1404006B0 (0x1404006B0) ---
__m128 __fastcall sub_1404006B0(__int64 a1)
{
  __int128 n0x3BDB0DD8_1; // xmm0
  __int128 n0x3BDB0DD8; // kr00_16
  __m128 result; // xmm0

  n0x3BDB0DD8 = 0x3BDB0DD8u;
  *(float *)&n0x3BDB0DD8 = 0.0066849999 / (float)(tanf(*(float *)(a1 + 0xF0) * 0.5) * *(float *)(a1 + 0x334));
  n0x3BDB0DD8_1 = n0x3BDB0DD8;
  __asm { vminss  xmm0, xmm0, cs:dword_1480F3BDC }
  return result;
}

// --- End Function: sub_1404006B0 (0x1404006B0) ---

// --- Function: sub_140405A10 (0x140405A10) ---
double *__fastcall sub_140405A10(double *a1, double *a2, double a3, _DWORD *a4)
{
  double v5; // xmm3_8
  double v8; // xmm2_8
  double v9; // xmm0_8
  int v12; // edx
  __int64 n2; // rcx
  double v14; // xmm1_8
  double v15; // xmm3_8
  __int64 v16; // rax
  double v19; // xmm2_8

  _XMM0 = *(_OWORD *)a2;
  v5 = *a2 * *a2;
  __asm { vunpckhpd xmm0, xmm0, xmm0 }
  v8 = *(double *)&_XMM0 * a2[1];
  v9 = a2[2] * a2[2];
  v12 = 0;
  if ( v5 <= v8 )
  {
    n2 = (unsigned int)(v8 <= v9) + 1;
  }
  else
  {
    n2 = 2;
    if ( v5 > v9 )
      n2 = 0;
  }
  v14 = a2[n2];
  v15 = a3 / COERCE_DOUBLE(*(_QWORD *)&v14 & 0x7FFFFFFFFFFFFFFFLL);
  LOBYTE(v12) = v14 <= 0.0;
  v16 = (unsigned int)(v12 + 2 * n2);
  *a4 = v16;
  _XMM0 = *(unsigned __int64 *)&a2[dword_1480F3DE0[2 * v16]];
  __asm { vcvtpd2ps xmm0, xmm0 }
  v19 = *(float *)&_XMM0 * v15;
  _XMM0 = *(unsigned __int64 *)&a2[dword_1480F3DE0[2 * (unsigned int)v16 + 1]];
  __asm { vcvtpd2ps xmm0, xmm0 }
  *a1 = v19;
  a1[1] = *(float *)&_XMM0 * v15;
  return a1;
}

// --- End Function: sub_140405A10 (0x140405A10) ---

// --- Function: sub_140406130 (0x140406130) ---
float __fastcall sub_140406130(__int64 a1)
{
  return *(float *)(a1 + 0x338);
}

// --- End Function: sub_140406130 (0x140406130) ---

// --- Function: sub_140598C00 (0x140598C00) ---
_QWORD *__fastcall sub_140598C00(_QWORD *a1, _QWORD *a2, _QWORD *a3)
{
  *a2 = *a1 - *a3;
  return a2;
}

// --- End Function: sub_140598C00 (0x140598C00) ---

// --- Function: sub_140598DA0 (0x140598DA0) ---
__m128 sub_140598DA0()
{
  __int128 v3; // kr00_16

  _XMM0 = 0;
  __asm { vcvtsi2sd xmm0, xmm0, qword ptr [rcx] }
  *((_QWORD *)&v3 + 1) = *((_QWORD *)&_XMM0 + 1);
  *(double *)&v3 = *(double *)&_XMM0 * 0.0000001;
  return (__m128)v3;
}

// --- End Function: sub_140598DA0 (0x140598DA0) ---

// --- Function: ??$sprintf_s@$0CA@@@YAHAEAY0CA@DPEBDZZ (0x1408AABE0) ---
int sprintf_s<32>(char (*_Buffer)[32], const char *_Format, ...)
{
  __int64 *v4; // rax
  int result; // eax
  va_list va; // [rsp+60h] [rbp+18h] BYREF

  va_start(va, _Format);
  v4 = sub_1402A6A10();
  result = _stdio_common_vsprintf_s(*v4, (char *)_Buffer, 0x20u, _Format, 0, va);
  if ( result < 0 )
    return 0xFFFFFFFF;
  return result;
}

// --- End Function: ??$sprintf_s@$0CA@@@YAHAEAY0CA@DPEBDZZ (0x1408AABE0) ---

// --- Function: sub_14723E730 (0x14723E730) ---
__int64 __fastcall sub_14723E730(unsigned __int64 *pCameraState)
{
  __int64 n5; // rax
  __int64 v3; // rcx
  __int64 n5_1; // rdx
  unsigned int v5; // r15d
  int n5_2; // r12d
  int n5_3; // esi
  float v8; // xmm9_4
  unsigned int v9; // edi
  unsigned int v10; // ebx
  __int128 v15; // kr00_16
  __int64 v17; // rdx
  float v18; // xmm8_4
  double v19; // xmm0_8
  double v20; // xmm0_8
  _LocaleUpdate *v21; // rbx
  float v22; // xmm6_4
  double v23; // xmm0_8
  unsigned __int8 n0x25; // al
  unsigned __int64 n0x25_1; // rcx
  int n0x40A; // edx
  bool v29; // bl
  __int64 v30; // rdx
  unsigned int v31; // r14d
  __int64 v32; // rax
  unsigned __int8 v33; // cf
  unsigned int v34; // eax
  bool v35; // sf
  int n2_1; // eax
  int n2; // r8d
  unsigned int n5_4; // edi
  unsigned int v39; // eax
  unsigned int v40; // eax
  __int64 v41; // r8
  unsigned int v42; // esi
  __int64 v43; // rcx
  unsigned int v44; // eax
  unsigned int v45; // eax
  __int64 v46; // r8
  __int64 v47; // rax
  __int64 v48; // rax
  __int64 v49; // rbx
  int v50; // esi
  int v51; // r14d
  unsigned __int8 v52; // al
  const char *v53; // rbx
  int v54; // edi
  __int64 v55; // rax
  double v56; // xmm0_8
  unsigned __int8 n3_1; // dl
  unsigned int v58; // eax
  unsigned int v59; // eax
  unsigned int v60; // ecx
  __int64 v61; // rax
  __int64 v62; // r8
  __int64 v63; // rbx
  __int64 v64; // r8
  __int64 v65; // rax
  double v66; // xmm7_8
  double v67; // xmm8_8
  double v68; // xmm0_8
  float v69; // xmm6_4
  float v70; // xmm2_4
  unsigned int v71; // eax
  int v72; // ebx
  double v73; // xmm0_8
  float v74; // xmm7_4
  float v75; // kr00_4
  int v76; // eax
  __int64 *v77; // rbx
  __int64 v78; // rbx
  double v79; // xmm0_8
  float v80; // xmm6_4
  unsigned __int64 n3_2; // rdx
  __int64 v82; // rcx
  unsigned int v83; // eax
  unsigned int v84; // eax
  unsigned int v85; // ecx
  struct tm *Tm; // rax
  char *v87; // rbx
  double v88; // xmm0_8
  __int64 v89; // rcx
  unsigned int v90; // eax
  unsigned int v91; // eax
  unsigned int v92; // ecx
  struct tm *Tm_1; // rax
  char *v94; // rbx
  double v95; // xmm0_8
  unsigned int v96; // eax
  unsigned int v97; // eax
  __int64 v98; // r8
  unsigned int v99; // eax
  unsigned int v100; // eax
  __int64 v101; // r8
  __int64 v102; // r8
  int v103; // ecx
  __int64 v104; // rax
  __int64 v105; // rdi
  __int64 (__fastcall *v106)(__int64, _QWORD); // rbx
  unsigned int v107; // eax
  unsigned int v108; // ebx
  __int64 v109; // rax
  __int64 v110; // rax
  const char *v111; // rbx
  double v112; // xmm0_8
  double v113; // xmm0_8
  __int64 v114; // r8
  __int64 v115; // rcx
  int v116; // r8d
  __int64 v117; // rcx
  unsigned int v118; // eax
  int v119; // eax
  bool v120; // [rsp+90h] [rbp-80h]
  unsigned __int8 v121; // [rsp+91h] [rbp-7Fh]
  char v122; // [rsp+92h] [rbp-7Eh]
  char v123; // [rsp+93h] [rbp-7Dh]
  __time64_t Time[2]; // [rsp+98h] [rbp-78h] BYREF
  char v125; // [rsp+A8h] [rbp-68h]
  double v126[2]; // [rsp+B0h] [rbp-60h] BYREF
  char v127; // [rsp+C0h] [rbp-50h]
  float v128; // [rsp+C8h] [rbp-48h] BYREF
  float v129; // [rsp+CCh] [rbp-44h]
  float v130; // [rsp+D0h] [rbp-40h]
  char v131[4]; // [rsp+D4h] [rbp-3Ch] BYREF
  float v132[2]; // [rsp+D8h] [rbp-38h] BYREF
  unsigned __int8 n3; // [rsp+E0h] [rbp-30h]
  __int128 v134; // [rsp+E8h] [rbp-28h] BYREF

  n5 = (unsigned int)n5_0;
  if ( (n5_0 & 1) != 0 )
  {
    v3 = qword_1514B8780;
  }
  else
  {
    n5_0 |= 1u;
    v3 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)qword_1514B80A8 + 0xC0LL))(
           qword_1514B80A8,
           "r_DisplayInfo");
    qword_1514B8780 = v3;
    n5 = (unsigned int)n5_0;
  }
  if ( (n5 & 2) != 0 )
  {
    n5_1 = ::n5_1;
  }
  else
  {
    n5_0 = n5 | 2;
    n5 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)qword_1514B80A8 + 0xC0LL))(
           qword_1514B80A8,
           "r_DisplaySessionInfo");
    v3 = qword_1514B8780;
    n5_1 = n5;
    ::n5_1 = n5;
  }
  v5 = 0;
  if ( v3 )
  {
    n5 = (*(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)v3 + 0x10LL))(v3, n5_1);
    n5_1 = ::n5_1;
    n5_2 = n5;
  }
  else
  {
    n5_2 = 0;
  }
  if ( n5_1 )
  {
    n5 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)n5_1 + 0x10LL))(n5_1);
    n5_3 = n5;
    if ( (_DWORD)n5 )
      goto LABEL_15;
  }
  else
  {
    n5_3 = 0;
  }
  if ( !n5_2 )
    goto LABEL_130;
LABEL_15:
  n5 = BYTE1(qword_149A147E6);
  if ( !BYTE1(qword_149A147E6) )
  {
    if ( !BYTE2(qword_149A147E6) )
      goto LABEL_19;
    if ( !BYTE1(qword_149A147E6) )
      goto LABEL_130;
  }
  if ( !byte_149A147E4 )
  {
LABEL_130:
    ::n5 = n5_2;
    return n5;
  }
LABEL_19:
  v8 = 5.0;
  if ( n5_3 > 0 && !(_BYTE)qword_149A147E6 )
  {
    n5 = (*(__int64 (__fastcall **)(__int64, __time64_t *))(*(_QWORD *)qword_149A142B0 + 0x6D8LL))(
           qword_149A142B0,
           Time);
    if ( (_DWORD)n5 != 0xFFFFFFFF )
    {
      v9 = (*(__int64 (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x178LL))(qword_149A142E8);
      v10 = (*(__int64 (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x180LL))(qword_149A142E8);
      _XMM2 = 0x80000000;
      __asm
      {
        vandnps xmm3, xmm3, xmm1
        vroundps xmm0, xmm3, 0
      }
      v15 = _XMM3;
      *(float *)&v15 = *(float *)&_XMM3 - *(float *)&_XMM0;
      _XMM3 = v15;
      __asm { vcmpeqss xmm3, xmm3, dword ptr cs:xmmword_1480DD730 }
      LOBYTE(v17) = 1;
      v18 = (float)(COERCE_FLOAT(
                      COERCE_UNSIGNED_INT(COERCE_FLOAT(_XMM3 & 0x3F800000) + *(float *)&_XMM0)
                    | COERCE_UNSIGNED_INT((float)((float)(int)v10 * 0.27759999) / (float)SLODWORD(Time[0])) & 0x80000000)
                  * 0.5)
          * (float)SLODWORD(Time[0]);
      (*(void (__fastcall **)(_LocaleUpdate *, __int64, _QWORD, _QWORD, unsigned int, int))(*(_QWORD *)qword_149A142E8
                                                                                          + 0x6B0LL))(
        qword_149A142E8,
        v17,
        v9,
        v10,
        0xD01502F9,
        0x501502F9);
      (*(void (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x138LL))(qword_149A142E8);
      n5 = (*(__int64 (__fastcall **)(_LocaleUpdate *, _QWORD, _QWORD, _QWORD, unsigned int, int))(*(_QWORD *)qword_149A142E8
                                                                                                 + 0x6B0LL))(
             qword_149A142E8,
             0,
             v9,
             v10,
             0xD01502F9,
             0x501502F9);
      v8 = v18 + 10.0;
    }
  }
  if ( n5_2 )
  {
    v19 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
    v129 = *(float *)&v19 * -10.0;
    v20 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
    v21 = qword_149A142E8;
    v130 = *(float *)&v20 * 13.0;
    v22 = (float)(*(int (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x178LL))(qword_149A142E8);
    v23 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)v21 + 0x208LL))(v21);
    v128 = v22 - (float)(*(float *)&v23 * v8);
    (*(void (__fastcall **)(__int64, _QWORD))(*(_QWORD *)qword_1514B8090 + 0x38LL))(qword_1514B8090, 0);
    _XMM0 = sub_140598DA0();
    __asm { vcvtsd2ss xmm1, xmm0, xmm0 }
    v132[0] = *(float *)&_XMM1;
    v132[1] = (*(float (__fastcall **)(__int64, float *, char *))(*(_QWORD *)qword_1514B8090 + 0xA0LL))(
                qword_1514B8090,
                v132,
                v131);
    n0x25 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A142B0 + 0x190LL))(qword_149A142B0);
    n0x25_1 = n0x25;
    n3 = n0x25;
    if ( n0x25 != 0x25 && n0x25 > 0x21u && n0x25 < 0x29u || (v122 = 0, n0x25 == 2) )
      v122 = 1;
    if ( n0x25 > 0xAu || (n0x40A = 0x40A, v121 = 1, !_bittest(&n0x40A, n0x25)) )
      v121 = 0;
    v29 = n0x25 == 0x30;
    v120 = n0x25 == 0x30;
    if ( n0x25 > 0x25u || (v30 = 0x203FE23A20LL, v123 = 1, !_bittest64(&v30, n0x25)) )
      v123 = 0;
    v31 = 0xFFFFFFFE;
    if ( n0x25 > 0x30u || (v32 = 0x1000008000420LL, v33 = _bittest64(&v32, n0x25_1), v34 = 0, !v33) )
      v34 = 0xFFFFFFFE;
    v35 = (int)(n5_2 + v34) < 0;
    n2_1 = n5_2 + v34;
    n2 = 0;
    if ( !v35 )
      n2 = n2_1;
    display_camera_and_location_info(pCameraState, (__int64)&v128, n2);
    n5_4 = 0;
    if ( n5_2 >= 0 )
      n5_4 = n5_2;
    LODWORD(Time[0]) = n5_4;
    sub_14723FD80(pCameraState);
    if ( n3 == 3 || (v39 = 0xFFFFFFFE, n3 == 0x30) )
      v39 = 0;
    v35 = (int)(n5_2 + v39) < 0;
    v40 = n5_2 + v39;
    v41 = 0;
    if ( !v35 )
      v41 = v40;
    sub_14723F920(pCameraState, &v128, v41, v29);
    v42 = 0xFFFFFFFF;
    if ( n3 > 0x30u || (v43 = 0x1000028004000LL, v44 = 0, !_bittest64(&v43, n3)) )
      v44 = 0xFFFFFFFF;
    v35 = (int)(n5_2 + v44) < 0;
    v45 = n5_2 + v44;
    v46 = 0;
    if ( !v35 )
      v46 = v45;
    sub_147241BE0(pCameraState, &v128, v46);
    if ( n5_4 )
    {
      if ( !byte_149A14490 )
      {
        v47 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14288 + 0xA0LL))(qword_149A14288);
        v48 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v47 + 0x360LL))(v47);
        if ( v48 )
        {
          if ( (*(unsigned __int8 (__fastcall **)(__int64))(*(_QWORD *)v48 + 0x30LL))(v48) )
          {
            v49 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14200 + 0x40LL))(qword_149A14200);
            v50 = *(_DWORD *)(v49 + 0x1C);
            v51 = *(_DWORD *)(v49 + 0x18);
            v52 = (*(__int64 (**)(void))(*(_QWORD *)qword_149A14288 + 0x320LL))();
            v53 = *(const char **)(v49 + 0x20);
            v54 = v52;
            v55 = *(_QWORD *)qword_149A142E8;
            v134 = xmmword_1480E1F40;
            v56 = (*(double (__fastcall **)(_LocaleUpdate *))(v55 + 0x208))(qword_149A142E8);
            v129 = v129 + v130;
            sub_147242670(
              (__int64)pCameraState,
              v128,
              v129,
              *(float *)&v56 * 1.1,
              &v134,
              (__int64)"Server: %s, restarts %u, pop. [shard %u, srv %u]",
              v53,
              v54,
              v51,
              v50);
            n5_4 = Time[0];
            v42 = 0xFFFFFFFF;
            v31 = 0xFFFFFFFE;
          }
        }
      }
    }
    n3_1 = n3;
    if ( n3 == 0xE || (v58 = 0xFFFFFFFF, n3 == 0x30) )
      v58 = 0;
    v35 = (int)(n5_2 + v58) < 0;
    v59 = n5_2 + v58;
    v60 = 0;
    if ( !v35 )
      v60 = v59;
    if ( v60 && !byte_149A14490 )
    {
      v61 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14200 + 0x40LL))(qword_149A14200);
      v63 = *(_QWORD *)(v61 + 0x38);
      if ( v63 != *(_QWORD *)(v61 + 0x40) )
      {
        (*(void (__fastcall **)(__int64, double *, __int64, __int64))(*(_QWORD *)qword_149A14200 + 0x120LL))(
          qword_149A14200,
          v126,
          v62,
          1);
        (*(void (__fastcall **)(__int64, __time64_t *, __int64, __int64))(*(_QWORD *)qword_149A14200 + 0x120LL))(
          qword_149A14200,
          Time,
          v64,
          1);
        v65 = *(_QWORD *)qword_149A142E8;
        v66 = *(float *)(v63 + 0x20);
        v67 = *(float *)(v63 + 8);
        v134 = xmmword_1480E1F40;
        v68 = (*(double (**)(void))(v65 + 0x208))();
        v69 = *(float *)&v68 * 1.1;
        v70 = (*(float (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8) * 2.0;
        v129 = (float)(v130 - v70) + v129;
        sub_147242670(
          (__int64)pCameraState,
          v128,
          v129,
          v69,
          &v134,
          (__int64)"Net: ping %3.1fms, loss %3.1f%% BwIn %3.3f%s%cps, BwOut %3.3f%s%cps",
          v67,
          v66,
          v126[0],
          *(const char **)&v126[1],
          v127,
          *(double *)Time,
          (const char *)Time[1],
          v125);
      }
      n3_1 = n3;
    }
    if ( n3_1 == 0xE || (v71 = 0xFFFFFFFF, n3_1 == 0x30) )
      v71 = 0;
    v72 = v71 + n5_2;
    Time[0] = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14200 + 0x40LL))(qword_149A14200);
    (*(void (__fastcall **)(__int64, __int128 *))(*(_QWORD *)qword_149A14200 + 0x38LL))(qword_149A14200, &v134);
    v73 = (*(double (__fastcall **)(__int64, _QWORD))(*(_QWORD *)qword_149A14250 + 0xC0LL))(qword_149A14250, v134);
    v74 = *(float *)&v73 * 1000.0;
    v75 = *((float *)&v134 + 2) * 1000.0;
    v76 = 0;
    if ( v72 >= 0 )
      v76 = v72;
    if ( v76 )
    {
      v77 = (__int64 *)Time[0];
      *(_OWORD *)Time = xmmword_1480E1F40;
      v78 = *v77;
      v79 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v80 = *(float *)&v79 * 1.1;
      *(float *)&v79 = (*(float (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v129 = (float)(v130 - (float)(*(float *)&v79 * 2.0)) + v129;
      sub_147242670(
        (__int64)pCameraState,
        v128,
        v129,
        v80,
        (__int128 *)Time,
        (__int64)"RL: entities: %zu, tick: %.2fms, MTSync: %.2fms",
        v78,
        v74,
        v75);
    }
    n3_2 = n3;
    if ( n3 > 0x30u || (v82 = 0x1000028004020LL, v83 = 0, !_bittest64(&v82, n3)) )
      v83 = 0xFFFFFFFF;
    v35 = (int)(n5_2 + v83) < 0;
    v84 = n5_2 + v83;
    v85 = 0;
    if ( !v35 )
      v85 = v84;
    if ( v85 && byte_149A147E5 )
    {
      Time[0] = *(_QWORD *)(*(__int64 (__fastcall **)(__int64, _QWORD))(*(_QWORD *)qword_149A14250 + 0x38LL))(
                             qword_149A14250,
                             0)
              / 0x989680LL;
      Tm = gmtime64(Time);
      v87 = asctime(Tm);
      v134 = xmmword_1480E1F40;
      v88 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v129 = v129 + v130;
      sub_147242670((__int64)pCameraState, v128, v129, *(float *)&v88 * 1.1, &v134, (__int64)"ServerTime: %s", v87);
      n3_2 = n3;
    }
    if ( (unsigned __int8)n3_2 > 0x30u || (v89 = 0x1000008004020LL, v90 = 0, !_bittest64(&v89, n3_2)) )
      v90 = 0xFFFFFFFF;
    v35 = (int)(n5_2 + v90) < 0;
    v91 = n5_2 + v90;
    v92 = 0;
    if ( !v35 )
      v92 = v91;
    if ( v92 && byte_149A147E5 )
    {
      Time[0] = *(_QWORD *)(*(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)qword_149A14250 + 0x38LL))(
                             qword_149A14250,
                             4)
              / 0x989680LL;
      Tm_1 = gmtime64(Time);
      v94 = asctime(Tm_1);
      v134 = xmmword_1480E1F40;
      v95 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v129 = v129 + v130;
      sub_147242670((__int64)pCameraState, v128, v129, *(float *)&v95 * 1.1, &v134, (__int64)"UniverseTime: %s", v94);
      LOBYTE(n3_2) = n3;
    }
    if ( v121 || (v96 = 0xFFFFFFFE, (_BYTE)n3_2 == 0xE) )
      v96 = 0;
    v35 = (int)(n5_2 + v96) < 0;
    v97 = n5_2 + v96;
    v98 = 0;
    if ( !v35 )
      v98 = v97;
    sub_147240A10(pCameraState, &v128, v98, v120);
    if ( n3 == 0x30 || v122 || (v99 = 0xFFFFFFFE, v121) )
      v99 = 0;
    v35 = (int)(n5_2 + v99) < 0;
    v100 = n5_2 + v99;
    v101 = 0;
    if ( !v35 )
      v101 = v100;
    sub_147241610(pCameraState, &v128, v101, v120);
    sub_147241840(pCameraState, &v128, n5_4);
    v102 = 0;
    v103 = n5_2 + 2 * (v121 - 1);
    if ( v103 >= 0 )
      v102 = (unsigned int)v103;
    sub_1472404F0(pCameraState, &v128, v102);
    Time[0] = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14288 + 0x90LL))(qword_149A14288);
    v104 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14288 + 0xA0LL))(qword_149A14288);
    v105 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v104 + 0x1D0LL))(v104);
    v106 = *(__int64 (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v105 + 0x60LL);
    v107 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14288 + 0x88LL))(qword_149A14288);
    v108 = v106(v105, v107);
    if ( v108 )
    {
      v109 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14288 + 0xA0LL))(qword_149A14288);
      v110 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v109 + 0x1D0LL))(v109);
      v111 = (const char *)(*(__int64 (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v110 + 0x20LL))(v110, v108);
      v134 = xmmword_1480E1F40;
      v112 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v129 = v129 + v130;
      sub_147242670(
        (__int64)pCameraState,
        v128,
        v129,
        *(float *)&v112 * 1.1,
        &v134,
        (__int64)"Current player location : %s  (LZ : %s)",
        (const char *)Time[0],
        v111);
    }
    else
    {
      v134 = xmmword_1480E1F40;
      v113 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v129 = v129 + v130;
      sub_147242670(
        (__int64)pCameraState,
        v128,
        v129,
        *(float *)&v113 * 1.1,
        &v134,
        (__int64)"Current player location : %s",
        (const char *)Time[0]);
    }
    if ( n3 == 0x30 || n3 == 0x1B )
      v42 = 0;
    v114 = 0;
    if ( (int)(v42 + n5_2) >= 0 )
      v114 = v42 + n5_2;
    sub_147240DB0(pCameraState, &v128, v114);
    if ( n3 <= 0x30u )
    {
      v115 = 0x1000400000400LL;
      if ( _bittest64(&v115, n3) )
        v31 = 0;
    }
    v116 = 0;
    if ( (int)(v31 + n5_2) >= 0 )
      v116 = v31 + n5_2;
    sub_147240FB0(pCameraState, &v128, v116);
    if ( n3 <= 0x30u && (v117 = 0x1000200004100LL, _bittest64(&v117, n3)) || (v118 = 0xFFFFFFFC, v123) )
      v118 = 0;
    v119 = n5_2 + v118;
    if ( v119 >= 0 )
      v5 = v119;
    sub_1472406B0(pCameraState, &v128, v5, v120);
    if ( n5_2 < 0 || n5_2 == 5 )
      (*(void (__fastcall **)(__int64, _QWORD))(*(_QWORD *)qword_1514B8780 + 0x30LL))(
        qword_1514B8780,
        (unsigned int)::n5);
    n5 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A141F0 + 0x5A0LL))(qword_149A141F0);
    if ( n5 )
      n5 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)n5 + 0x160LL))(n5);
    if ( qword_149A142B8 )
      n5 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A142B8 + 0xB8LL))(qword_149A142B8);
  }
  ::n5 = n5_2;
  return n5;
}

// --- End Function: sub_14723E730 (0x14723E730) ---

// --- Function: display_camera_and_location_info (0x14723F4E0) ---
// Calculates and displays camera orientation, parameters, and relative position to
// nearby locations/zones.  This function reads camera orientation and position
// data from the structure pointed to by pCameraState. It calculates the camera's
// pitch, yaw, and roll angles in degrees. If displayMode is non-zero, it iterates
// through a list of locations/zones obtained from a global iterator source
// (`qword_14981D208`). For each location, it calculates the relative position (X,
// Y, Z) from the camera and formats it into strings (converting large distances to
// kilometers). If displayMode is 2 or greater, it also retrieves and formats
// detailed camera parameters (FOV, Focal Length, F-Stop) for the first location in
// the list. It then calls sub_14709B430 to display the formatted strings (camera
// direction, parameters, zone name, relative position) at screen coordinates
// specified and updated via pDisplayPos.  Parameters:  a1 (pCameraState): Pointer
// to a structure containing camera state (orientation, position, FOV, etc.).  a2
// (pDisplayPos): Pointer to a structure holding screen coordinates {float x, float
// y, float y_increment} for text display.  n2 (displayMode): Integer flag
// controlling display; 0 = off, 1 = basic info, >=2 = detailed info.  Return
// Value:  void
void __fastcall display_camera_and_location_info(unsigned __int64 *pCameraState, __int64 a2, int n2)
{
  unsigned __int64 *v4; // rdi
  float v21; // xmm9_4
  float v22; // xmm0_4
  float v23; // xmm11_4
  float v25; // xmm0_4
  int v26; // edx
  float v27; // xmm13_4
  double v28; // xmm0_8
  __int64 v29; // rbx
  __int64 i; // r15
  double v31; // xmm2_8
  const char *p_%.4fkm; // rdx
  double v33; // xmm2_8
  const char *p_%.4fkm_1; // rdx
  double v35; // xmm2_8
  const char *p_%.4fkm_2; // rdx
  double v37; // kr00_8
  float v38; // xmm0_4
  double v39; // xmm3_8
  __int64 v40; // rdx
  __int64 v41; // r8
  __int64 v42; // rdx
  __int64 v43; // r8
  const char *p_Unknown; // rax
  _QWORD v45[3]; // [rsp+50h] [rbp-1A8h] BYREF
  double v46; // [rsp+68h] [rbp-190h] BYREF
  double v47; // [rsp+70h] [rbp-188h]
  double v48; // [rsp+78h] [rbp-180h]
  char Buffer[192]; // [rsp+80h] [rbp-178h] BYREF

  if ( n2 )
  {
    v4 = pCameraState + 0x9A;
    _XMM0 = pCameraState[0xA2];
    _XMM7 = pCameraState[0x9E];
    _XMM8 = pCameraState[0x9F];
    _XMM10 = pCameraState[0x9B];
    _XMM11 = pCameraState[0xA3];
    _XMM12 = pCameraState[0xA4];
    __asm { vcvtpd2ps xmm0, xmm0 }
    _XMM1 = _XMM0 ^ 0x80000000;
    LODWORD(_XMM0) = 0xBF800000;
    __asm
    {
      vminss  xmm2, xmm1, xmm3
      vmaxss  xmm4, xmm2, xmm0
    }
    __asm
    {
      vcvtpd2ps xmm10, xmm10
      vcvtpd2ps xmm7, xmm7
      vcvtpd2ps xmm11, xmm11
      vcvtpd2ps xmm12, xmm12
    }
    if ( *(float *)&_XMM4 >= -1.0 )
      __asm { vminss  xmm0, xmm4, xmm3; X }
    v21 = asinf(*(float *)&_XMM0);
    if ( fabs(COERCE_FLOAT(LODWORD(v21) & 0x7FFFFFFF) - 1.5707964) >= 0.0099999998 )
    {
      v22 = atan2f(*(float *)&_XMM11, *(float *)&_XMM12);
      _XMM8 = *v4;
    }
    else
    {
      v22 = 0.0;
      LODWORD(_XMM7) = _XMM10 ^ 0x80000000;
    }
    v23 = v22 * 57.295776;
    __asm { vcvtsd2ss xmm1, xmm8, xmm8; X }
    v25 = atan2f(*(float *)&_XMM7, *(float *)&_XMM1);
    v26 = *((_DWORD *)v4 + 0x2A);
    v45[0] = v4[3];
    v27 = v25 * 57.295776;
    v28 = *((double *)v4 + 7);
    v45[2] = v4[0xB];
    *(double *)&v45[1] = v28;
    if ( v26 != 0xFFFFFFFF )
    {
      v29 = (*(__int64 (**)(void))(*(_QWORD *)qword_149A141F8 + 0x68LL))();
      for ( i = v29; v29; v29 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v29 + 8LL))(v29) )
      {
        (*(void (__fastcall **)(__int64, double *, _QWORD *))(*(_QWORD *)v29 + 0xF8LL))(v29, &v46, v45);
        memset(Buffer, 0, sizeof(Buffer));
        v31 = v46;
        if ( COERCE_DOUBLE(*(_QWORD *)&v46 & 0x7FFFFFFFFFFFFFFFLL) >= 10000.0 )
          v31 = v46 * 0.001;
        p_%.4fkm = "%.2fm";
        if ( COERCE_DOUBLE(*(_QWORD *)&v46 & 0x7FFFFFFFFFFFFFFFLL) >= 10000.0 )
          p_%.4fkm = "%.4fkm";
        sprintf(Buffer, p_%.4fkm, v31);
        v33 = v47;
        if ( COERCE_DOUBLE(*(_QWORD *)&v47 & 0x7FFFFFFFFFFFFFFFLL) >= 10000.0 )
          v33 = v47 * 0.001;
        p_%.4fkm_1 = "%.2fm";
        if ( COERCE_DOUBLE(*(_QWORD *)&v47 & 0x7FFFFFFFFFFFFFFFLL) >= 10000.0 )
          p_%.4fkm_1 = "%.4fkm";
        sprintf(&Buffer[0x40], p_%.4fkm_1, v33);
        v35 = v48;
        if ( COERCE_DOUBLE(*(_QWORD *)&v48 & 0x7FFFFFFFFFFFFFFFLL) >= 10000.0 )
          v35 = v48 * 0.001;
        p_%.4fkm_2 = "%.2fm";
        if ( COERCE_DOUBLE(*(_QWORD *)&v48 & 0x7FFFFFFFFFFFFFFFLL) >= 10000.0 )
          p_%.4fkm_2 = "%.4fkm";
        sprintf(&Buffer[0x80], p_%.4fkm_2, v35);
        if ( n2 >= 2 && v29 == i )
        {
          v37 = sub_1404006B0(v4).m128_f32[0];
          v38 = sub_140406130(v4).m128_f32[0];
          v39 = (float)(*((float *)v4 + 0x3C) * 57.295776);
          v40 = (unsigned int)(int)v23;
          LODWORD(v40) = *(_DWORD *)a2;
          *(float *)&v41 = *(float *)(a2 + 4) + *(float *)(a2 + 8);
          *(float *)(a2 + 4) = *(float *)&v41;
          sub_147242710(
            pCameraState,
            v40,
            v41,
            "CamDir: %3d %3d %4d FOV: %.0f Focal: %.2f FStop: %.1f",
            (int)v23,
            (int)(float)(v21 * 57.295776),
            (int)v27,
            v39,
            v38,
            v37);
        }
        if ( (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v29 + 0x1F0LL))(v29) )
          p_Unknown = (const char *)(*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v29 + 0x1F0LL))(v29);
        else
          p_Unknown = "Unknown";
        *(float *)&v43 = *(float *)(a2 + 4) + *(float *)(a2 + 8);
        LODWORD(v42) = *(_DWORD *)a2;
        *(float *)(a2 + 4) = *(float *)&v43;
        sub_147242710(pCameraState, v42, v43, "Zone: %s Pos: %s %s %s", p_Unknown, Buffer, &Buffer[0x40], &Buffer[0x80]);
      }
    }
  }
}

// --- End Function: display_camera_and_location_info (0x14723F4E0) ---

// --- Function: sub_14723F920 (0x14723F920) ---
void __fastcall sub_14723F920(unsigned __int64 *pCameraState, float *a2, int n2, char a4)
{
  __int128 v4; // xmm6
  __int128 v5; // xmm7
  __int128 v6; // xmm8
  __int128 v7; // xmm9
  __int128 v8; // xmm10
  __int128 v9; // xmm11
  __int128 v10; // xmm12
  __int64 v15; // rcx
  unsigned __int64 n0x46; // rbx
  float v17; // xmm0_4
  __int64 v18; // rax
  unsigned int v19; // ecx
  unsigned int v20; // r8d
  unsigned int v21; // r9d
  unsigned int v22; // r10d
  unsigned int v23; // r11d
  unsigned int v24; // edx
  float v25; // xmm1_4
  float v26; // xmm12_4
  float v27; // kr00_4
  float v28; // xmm5_4
  float v29; // kr00_4
  float v30; // xmm4_4
  float v31; // kr00_4
  float v32; // xmm9_4
  float v33; // kr00_4
  float v34; // xmm8_4
  float v35; // kr00_4
  float v36; // xmm7_4
  float v37; // kr00_4
  float v38; // kr00_4
  bool v39; // al
  double v40; // xmm11_8
  double v41; // xmm6_8
  double v42; // xmm7_8
  double v43; // xmm8_8
  double v44; // xmm9_8
  double v45; // xmm10_8
  double v46; // xmm12_8
  __int128 v47; // xmm0
  double v48; // xmm0_8
  float v49; // kr00_4
  float v50; // xmm1_4
  float *v51; // rdi
  __int128 v52; // [rsp+70h] [rbp-C8h] BYREF
  float v53[8]; // [rsp+80h] [rbp-B8h] BYREF
  __int128 v54; // [rsp+B0h] [rbp-88h]
  __int128 v55; // [rsp+C0h] [rbp-78h]
  __int128 v56; // [rsp+D0h] [rbp-68h]
  __int128 v57; // [rsp+E0h] [rbp-58h]
  __int128 v58; // [rsp+F0h] [rbp-48h]
  __int128 v59; // [rsp+100h] [rbp-38h]
  __int128 v60; // [rsp+110h] [rbp-28h]

  v59 = v5;
  v58 = v6;
  v57 = v7;
  v54 = v10;
  if ( (dword_1514B85D8 & 1) != 0 )
  {
    v15 = qword_1514B85D0;
  }
  else
  {
    dword_1514B85D8 |= 1u;
    v15 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)qword_1514B80A8 + 0xC0LL))(
            qword_1514B80A8,
            "r_DisplayInfo");
    qword_1514B85D0 = v15;
  }
  n0x46 = 0;
  if ( v15 && (*(unsigned int (__fastcall **)(__int64))(*(_QWORD *)v15 + 0x10LL))(v15) == 5 )
  {
    dword_1499C19AC = 0;
    dword_1499C19B4 = 0;
    dword_1499C19BC = 0;
    dword_1499C19C4 = 0;
    dword_1499C19CC = 0;
    dword_1499C19D4 = 0;
    dword_1499C19DC = 0;
  }
  v17 = (*(float (__fastcall **)(__int64))(*(_QWORD *)qword_1514B8090 + 0x98LL))(qword_1514B8090);
  if ( v17 < *(float *)&dword_1499C19A8 )
    v18 = (unsigned int)dword_1499C19AC;
  else
    v18 = (unsigned int)++dword_1499C19AC;
  v19 = dword_1499C19B4;
  if ( v17 >= *(float *)&dword_1499C19B0 )
    v19 = ++dword_1499C19B4;
  v20 = dword_1499C19BC;
  if ( v17 >= *(float *)&dword_1499C19B8 )
    v20 = ++dword_1499C19BC;
  v21 = dword_1499C19C4;
  if ( v17 >= *(float *)&dword_1499C19C0 )
    v21 = ++dword_1499C19C4;
  v22 = dword_1499C19CC;
  if ( v17 >= *(float *)&dword_1499C19C8 )
    v22 = ++dword_1499C19CC;
  v23 = dword_1499C19D4;
  if ( v17 >= *(float *)&dword_1499C19D0 )
    v23 = ++dword_1499C19D4;
  v24 = dword_1499C19DC;
  if ( v17 >= *(float *)&dword_1499C19D8 )
    v24 = ++dword_1499C19DC;
  v25 = (float)v18;
  v26 = (float)((float)(1.0 / v25) * v25) * 100.0;
  v27 = (float)v19;
  v28 = (float)(v27 * (float)(1.0 / v25)) * 100.0;
  v29 = (float)v20;
  v30 = (float)(v29 * (float)(1.0 / v25)) * 100.0;
  v31 = (float)v21;
  v32 = (float)(v31 * (float)(1.0 / v25)) * 100.0;
  v33 = (float)v22;
  v34 = (float)(v33 * (float)(1.0 / v25)) * 100.0;
  v35 = (float)v23;
  v36 = (float)(v35 * (float)(1.0 / v25)) * 100.0;
  v37 = (float)v24;
  v38 = (float)(v37 * (float)(1.0 / v25)) * 100.0;
  v53[6] = v38;
  v53[0] = v26;
  v53[1] = v28;
  v53[2] = v30;
  v53[3] = v32;
  v53[4] = v34;
  v53[5] = v36;
  v39 = v26 < 95.0 || v28 < 80.0 || v30 < 50.0;
  if ( n2 >= 2 || v39 && a4 )
  {
    v60 = v4;
    v56 = v8;
    v55 = v9;
    v40 = v28;
    v41 = v38;
    v42 = v36;
    v43 = v34;
    v44 = v32;
    v45 = v30;
    v46 = v26;
    if ( v39 )
      v47 = xmmword_148116840;
    else
      v47 = xmmword_148BCE370;
    v52 = v47;
    v48 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
    v49 = a2[2] + a2[1];
    v50 = *a2;
    a2[1] = v49;
    sub_147242670(
      (__int64)pCameraState,
      v50,
      v49,
      *(float *)&v48 * 1.1,
      &v52,
      (__int64)"[%3.1f|%3.1f|%3.1f|%3.1f|%3.1f|%3.1f|%3.1f]",
      v46,
      v40,
      v45,
      v44,
      v43,
      v42,
      v41);
  }
  if ( qword_1514B85D0
    && (*(unsigned int (__fastcall **)(__int64))(*(_QWORD *)qword_1514B85D0 + 0x10LL))(qword_1514B85D0) == 0xFFFFFFFD )
  {
    LogTraceConditional("Frame rate histogram after %u frames:", dword_1499C19AC);
    v51 = v53;
    do
    {
      LogTraceConditional("  %2zu+ fps bucket: %.2f%%", n0x46, *v51);
      n0x46 += 0xALL;
      ++v51;
    }
    while ( n0x46 < 0x46 );
  }
}

// --- End Function: sub_14723F920 (0x14723F920) ---

// --- Function: sub_14723FD80 (0x14723FD80) ---
double __fastcall sub_14723FD80(unsigned __int64 *pCameraState, __int64 a2, int n2)
{
  __int128 v3; // xmm0
  __int128 v4; // xmm6
  __int128 v5; // xmm7
  __int128 v6; // xmm8
  __int128 v7; // xmm9
  __int128 v8; // xmm10
  __int128 v9; // xmm11
  __int128 v10; // xmm12
  char v15; // cl
  char *v16; // rdx
  __m128 *v19; // rax
  __int64 *v20; // rcx
  __int64 n7; // rdx
  __m128 v23; // xmm9
  __m128 v26; // xmm5
  __m128 v27; // xmm6
  __m128 v28; // xmm0
  __m128 v51; // xmm1
  __m128 v52; // kr00_16
  __m128 v53; // xmm5
  __m128 v54; // xmm4
  __m128 v55; // xmm2
  __m128 v56; // xmm1
  __m128 v57; // xmm1
  __m128 v60; // kr00_16
  float v61; // xmm2_4
  float v62; // xmm1_4
  float v63; // xmm2_4
  float v64; // xmm1_4
  float v65; // xmm6_4
  float v68; // xmm0_4
  double v69; // xmm7_8
  double v70; // xmm6_8
  double v71; // xmm8_8
  double v72; // xmm9_8
  double v74; // xmm0_8
  float v75; // xmm3_4
  float v76; // kr00_4
  float v77; // xmm1_4
  double v78; // xmm0_8
  float v79; // xmm3_4
  float v80; // kr00_4
  float v81; // xmm1_4
  int v82; // edx
  int v83; // ecx
  int v84; // eax
  int v85; // esi
  int v86; // eax
  _QWORD *v87; // rax
  int v89; // xmm3_4
  float v90; // xmm1_4
  float v91; // kr00_4
  const char *v92; // rax
  __int64 v93; // r8
  __int64 v94; // rdx
  __int64 v95; // rdx
  __int64 v96; // r8
  char v98[8]; // [rsp+50h] [rbp-A8h] BYREF
  _QWORD v99[17]; // [rsp+58h] [rbp-A0h] BYREF
  char v100; // [rsp+100h] [rbp+8h] BYREF
  char v101; // [rsp+110h] [rbp+18h] BYREF

  *(_OWORD *)&v99[0xF] = v4;
  *(_OWORD *)&v99[0xD] = v5;
  *(_OWORD *)&v99[0xB] = v6;
  *(double *)&v3 = (*(double (__fastcall **)(__int64))(*(_QWORD *)qword_1514B8090 + 0x98LL))(qword_1514B8090);
  _XMM8 = v3;
  (*(void (__fastcall **)(__int64, char *))(*(_QWORD *)qword_1514B8090 + 0x70LL))(qword_1514B8090, &v100);
  if ( (int)*(float *)&v3 >= 0 )
  {
    v15 = 0xFF;
    if ( (int)*(float *)&v3 < 0xFF )
      v15 = (int)*(float *)&v3;
  }
  else
  {
    v15 = 0;
  }
  v16 = (char *)pCameraState[0x86];
  v101 = v15;
  if ( v16 == (char *)pCameraState[0x87] )
  {
    sub_1402FB9F0((__int64 *)pCameraState + 0x85, v16, &v101);
  }
  else
  {
    *v16 = v15;
    ++pCameraState[0x86];
  }
  __asm { vminss  xmm0, xmm8, cs:dword_1483D3A40 }
  *(_OWORD *)&v99[9] = v7;
  *((float *)qword_1514B84B0 + ++dword_1514B85A4 % 0x3C) = *(float *)&_XMM0;
  if ( ++dword_1514B85A0 > 0x3C )
  {
    _XMM2 = xmmword_148BCE3B0;
    *(_OWORD *)&v99[7] = v8;
    v19 = (__m128 *)qword_1514B84C0;
    *(_OWORD *)&v99[5] = v9;
    v20 = qword_1514B84C0;
    *(_OWORD *)&v99[3] = v10;
    n7 = 7;
    _XMM4 = xmmword_148BCE3B0;
    v23 = 0;
    _XMM1 = 0;
    _XMM3 = 0;
    v26 = 0;
    v27 = 0;
    do
    {
      v28 = *((__m128 *)v20 + 0xFFFFFFFF);
      v20 += 4;
      __asm
      {
        vminps  xmm2, xmm2, xmm0
        vmaxps  xmm1, xmm1, xmm0
      }
      v27 = _mm_add_ps(v28, v27);
      __asm
      {
        vminps  xmm4, xmm4, xmm0
        vmaxps  xmm3, xmm3, xmm0
      }
      v26 = _mm_add_ps(*((__m128 *)v20 + 0xFFFFFFFE), v26);
      --n7;
    }
    while ( n7 );
    _XMM12 = (unsigned int)dword_1514B8590;
    __asm
    {
      vmaxps  xmm1, xmm1, xmm3
      vmovhlps xmm0, xmm1, xmm1
      vmaxps  xmm3, xmm0, xmm1
      vminps  xmm1, xmm2, xmm4
    }
    _XMM4 = (unsigned int)dword_1514B859C;
    _XMM7 = _mm_add_ps(v26, v27);
    _XMM5 = (unsigned int)dword_1514B8598;
    _XMM6 = (unsigned int)dword_1514B8594;
    _mm_shuffle_ps(_XMM3, _XMM3, 0xF5);
    __asm
    {
      vmaxss  xmm3, xmm3, xmm0
      vmovhlps xmm0, xmm1, xmm1
      vminps  xmm2, xmm0, xmm1
    }
    _mm_shuffle_ps(_XMM2, _XMM2, 0xF5);
    __asm
    {
      vminss  xmm2, xmm2, xmm0
      vminss  xmm0, xmm12, xmm2
      vminss  xmm2, xmm6, xmm0
      vminss  xmm0, xmm5, xmm2
      vminss  xmm10, xmm4, xmm0
      vmaxss  xmm1, xmm12, xmm3
      vmaxss  xmm3, xmm6, xmm1
      vmaxss  xmm1, xmm5, xmm3
      vmaxss  xmm11, xmm4, xmm1
      vmovhlps xmm0, xmm7, xmm7
    }
    v51 = _mm_add_ps(_XMM0, _XMM7);
    v52 = (__m128)(unsigned int)dword_1514B8590;
    v52.m128_f32[0] = (float)((float)((float)(*(float *)&dword_1514B8590
                                            + (float)(v51.m128_f32[0] + _mm_shuffle_ps(v51, v51, 0xF5).m128_f32[0]))
                                    + *(float *)&dword_1514B8594)
                            + (float)(*(float *)&dword_1514B859C + *(float *)&dword_1514B8598))
                    * 0.016666668;
    v53 = v52;
    v54 = _mm_shuffle_ps(v53, v53, 0);
    v55 = 0;
    do
    {
      v56 = _mm_sub_ps(v19[0xFFFFFFFFLL], v54);
      v23 = _mm_add_ps(_mm_mul_ps(v56, v56), v23);
      v57 = _mm_sub_ps(*v19, v54);
      v19 += 2;
      v55 = _mm_add_ps(_mm_mul_ps(v57, v57), v55);
    }
    while ( (__int64)v19 < (__int64)&dword_1514B85A0 );
    _XMM1 = _mm_add_ps(v23, v55);
    __asm { vmovhlps xmm0, xmm1, xmm1 }
    v60 = _mm_add_ps(_XMM0, _XMM1);
    *((float *)pCameraState + 0x274) = (float)(fsqrt(
                                                 (float)((float)((float)((float)(v60.m128_f32[0]
                                                                               + _mm_shuffle_ps(v60, v60, 0xF5).m128_f32[0])
                                                                       + (float)((float)(*(float *)&dword_1514B8590
                                                                                       - v53.m128_f32[0])
                                                                               * (float)(*(float *)&dword_1514B8590
                                                                                       - v53.m128_f32[0])))
                                                               + (float)((float)(*(float *)&dword_1514B8594
                                                                               - v53.m128_f32[0])
                                                                       * (float)(*(float *)&dword_1514B8594
                                                                               - v53.m128_f32[0])))
                                                       + (float)((float)(*(float *)&dword_1514B8598 - v53.m128_f32[0])
                                                               * (float)(*(float *)&dword_1514B8598 - v53.m128_f32[0])))
                                               + (float)((float)(*(float *)&dword_1514B859C - v53.m128_f32[0])
                                                       * (float)(*(float *)&dword_1514B859C - v53.m128_f32[0])))
                                             * *(float *)(a2 + 0x14))
                                     + (float)((float)(1.0 - *(float *)(a2 + 0x14)) * *((float *)pCameraState + 0x274));
    if ( *(_DWORD *)(a2 + 0xC) )
    {
      *((float *)pCameraState + 0x273) = (float)((float)(1.0 - *(float *)(a2 + 0x14)) * *((float *)pCameraState + 0x273))
                                       + (float)(*(float *)&_XMM8 * *(float *)(a2 + 0x14));
      v61 = (float)(1.0 - *(float *)(a2 + 0x14)) * *((float *)pCameraState + 0x276);
      v62 = *(float *)&_XMM8 * *(float *)(a2 + 0x14);
      *((float *)pCameraState + 0x276) = v61 + v62;
      if ( *(float *)&_XMM8 <= (float)(v61 + v62) )
      {
        *((float *)pCameraState + 0x276) = *(float *)&_XMM8;
        *((float *)pCameraState + 0x275) = *(float *)&_XMM8;
      }
      v63 = (float)(1.0 - *(float *)(a2 + 0x14)) * *((float *)pCameraState + 0x278);
      v64 = *(float *)&_XMM8 * *(float *)(a2 + 0x14);
      *((float *)pCameraState + 0x278) = v63 + v64;
      if ( *(float *)&_XMM8 >= (float)(v63 + v64) )
      {
        *((float *)pCameraState + 0x278) = *(float *)&_XMM8;
        *((float *)pCameraState + 0x277) = *(float *)&_XMM8;
      }
    }
    else
    {
      *((float *)pCameraState + 0x276) = *(float *)&_XMM10;
      *((float *)pCameraState + 0x275) = *(float *)&_XMM10;
      *((float *)pCameraState + 0x278) = *(float *)&_XMM11;
      *((float *)pCameraState + 0x277) = *(float *)&_XMM11;
      *((float *)pCameraState + 0x273) = v53.m128_f32[0];
    }
    v65 = *(float *)(a2 + 0x14);
    _XMM0 = sub_140598DA0();
    __asm { vcvtsd2ss xmm1, xmm0, xmm0 }
    *((float *)pCameraState + 0x272) = (float)((float)(1.0 - v65) * *((float *)pCameraState + 0x272))
                                     + (float)(*(float *)&_XMM1 * v65);
  }
  v68 = *((float *)pCameraState + 0x273);
  v69 = v68;
  v70 = (float)(*((float *)pCameraState + 0x272) * 1000.0);
  if ( n2 < 2 )
  {
    if ( v68 >= 30.0 )
      _XMM0 = (__m128)xmmword_148BCE370;
    else
      _XMM0 = (__m128)xmmword_148116840;
    *(__m128 *)v99 = _XMM0;
    v78 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
    v79 = *(float *)&v78 * 1.25;
    _XMM0.m128_u64[0] = *(unsigned int *)(a2 + 8);
    v80 = _XMM0.m128_f32[0] + *(float *)(a2 + 4);
    v81 = *(float *)a2;
    *(float *)(a2 + 4) = v80;
    sub_147242670((__int64)pCameraState, v81, v80, v79, (__int128 *)v99, (__int64)"FPS %2.1f - %2.1fms", v69, v70);
  }
  else
  {
    v71 = *((float *)pCameraState + 0x277);
    v72 = *((float *)pCameraState + 0x275);
    if ( v68 >= 30.0 )
      _XMM0 = (__m128)xmmword_148BCE370;
    else
      _XMM0 = (__m128)xmmword_148116840;
    *(__m128 *)v99 = _XMM0;
    v74 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
    v75 = *(float *)&v74 * 1.25;
    _XMM0.m128_u64[0] = *(unsigned int *)(a2 + 8);
    v76 = _XMM0.m128_f32[0] + *(float *)(a2 + 4);
    v77 = *(float *)a2;
    *(float *)(a2 + 4) = v76;
    sub_147242670(
      (__int64)pCameraState,
      v77,
      v76,
      v75,
      (__int128 *)v99,
      (__int64)"FPS %2.1f [%2.0f..%2.0f], - %2.1fms",
      v69,
      v72,
      v71,
      v70);
  }
  v82 = *(_DWORD *)(qword_1514B80B8 + 0x260);
  if ( v82 )
  {
    if ( (dword_1514B85BC & 1) == 0 )
    {
      v83 = *(_DWORD *)(qword_1514B80B8 + 0x7C);
      dword_1514B85BC |= 1u;
      dword_1514B85B8 = v82 + v83;
    }
    v84 = (*(__int64 (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x538LL))(qword_149A142E8);
    v85 = v84;
    if ( v84 >= *(_DWORD *)(qword_1514B80B8 + 0x7C) )
    {
      if ( v84 == *(_DWORD *)(qword_1514B80B8 + 0x7C) )
        qword_1514B85B0 = *(_QWORD *)(*(__int64 (__fastcall **)(__int64, char *))(*(_QWORD *)qword_149A14250 + 0x48LL))(
                                       qword_149A14250,
                                       v98);
      v86 = dword_1514B85B8;
      if ( v85 == dword_1514B85B8 )
      {
        v87 = (_QWORD *)(*(__int64 (__fastcall **)(__int64, char *))(*(_QWORD *)qword_149A14250 + 0x48LL))(
                          qword_149A14250,
                          v98);
        sub_140598C00(v87, v99, &qword_1514B85B0);
        _XMM0 = sub_140598DA0();
        __asm { vcvtsd2ss xmm2, xmm0, xmm0 }
        v86 = dword_1514B85B8;
        *(float *)&v89 = (float)*(int *)(qword_1514B80B8 + 0x260) / *(float *)&_XMM2;
        dword_1514B85A8 = v89;
      }
      else
      {
        v89 = dword_1514B85A8;
      }
      if ( v85 >= v86 )
      {
        v90 = *(float *)a2;
        *(_OWORD *)v99 = xmmword_148116840;
        v91 = *(float *)(a2 + 8) + *(float *)(a2 + 4);
        *(float *)(a2 + 4) = v91;
        sub_147242670(
          (__int64)pCameraState,
          v90,
          v91,
          2.0,
          (__int128 *)v99,
          (__int64)"Startup AVG FPS: %.2f",
          *(float *)&v89);
        _XMM0.m128_u64[0] = *(unsigned int *)(a2 + 4);
        *(float *)(a2 + 4) = _XMM0.m128_f32[0] + *(float *)(a2 + 8);
      }
    }
  }
  if ( n2 >= 2 )
  {
    v92 = (const char *)(*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A142B0 + 0x6C8LL))(qword_149A142B0);
    *(float *)&v93 = *(float *)(a2 + 8) + *(float *)(a2 + 4);
    LODWORD(v94) = *(_DWORD *)a2;
    *(float *)(a2 + 4) = *(float *)&v93;
    *(double *)_XMM0.m128_u64 = sub_147242710(pCameraState, v94, v93, "Session: %s", v92);
    if ( (*(unsigned __int8 (__fastcall **)(__int64))(*(_QWORD *)qword_149A142B0 + 0x6E0LL))(qword_149A142B0) )
    {
      *(float *)&v96 = *(float *)(a2 + 8) + *(float *)(a2 + 4);
      LODWORD(v95) = *(_DWORD *)a2;
      *(float *)(a2 + 4) = *(float *)&v96;
      *(double *)_XMM0.m128_u64 = sub_147242710(pCameraState, v95, v96, "   ShardId: %s", &byte_149A149F7);
    }
  }
  return *(double *)_XMM0.m128_u64;
}

// --- End Function: sub_14723FD80 (0x14723FD80) ---

// --- Function: sub_1472404F0 (0x1472404F0) ---
void __fastcall sub_1472404F0(unsigned __int64 *pCameraState, float *a2, int a3)
{
  __int64 v5; // rax
  __int64 v6; // rdi
  __int64 v7; // rsi
  void (__fastcall *v8)(__int64, __int64, __int64); // rbx
  __int64 v9; // rdi
  void (__fastcall *v10)(__int64, __int64, __int64); // rbx
  __int64 v11; // rdi
  void (__fastcall *v12)(__int64, __int64, __int64); // rbx
  unsigned __int64 v13; // rax
  int v14; // esi
  unsigned __int64 v15; // rdi
  __int128 v16; // xmm0
  double v17; // xmm0_8
  float v18; // kr00_4
  float v19; // xmm1_4
  __int128 v20; // [rsp+40h] [rbp-18h] BYREF

  if ( a3 )
  {
    v5 = (*(__int64 (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x8F8LL))(qword_149A142E8);
    v6 = qword_149A142F0;
    v7 = v5;
    v8 = *(void (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)qword_149A142F0 + 0x1E0LL);
    v8(qword_149A142F0, 2, 0xFFFFFFFFLL);
    v8(v6, 1, 0xFFFFFFFFLL);
    v9 = qword_149A142F0;
    v10 = *(void (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)qword_149A142F0 + 0x1E0LL);
    v10(qword_149A142F0, 5, 0xFFFFFFFFLL);
    v10(v9, 4, 0xFFFFFFFFLL);
    v10(v9, 3, 0xFFFFFFFFLL);
    v11 = qword_149A142F0;
    v12 = *(void (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)qword_149A142F0 + 0x1E0LL);
    v12(qword_149A142F0, 8, 0xFFFFFFFFLL);
    v12(v11, 7, 0xFFFFFFFFLL);
    v12(v11, 6, 0xFFFFFFFFLL);
    v13 = (*(__int64 (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)qword_149A142F0 + 0x1E0LL))(
            qword_149A142F0,
            0xFFFFFFFFLL,
            0xFFFFFFFFLL);
    v14 = *(_DWORD *)(v7 + 0xB8);
    v15 = v13 >> 0x14;
    if ( (int)(5 * (v13 >> 0x14)) / 4 < v14 )
      v16 = xmmword_1480E1F40;
    else
      v16 = xmmword_148116840;
    v20 = v16;
    v17 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
    v18 = a2[2] + a2[1];
    v19 = *a2;
    a2[1] = v18;
    sub_147242670(
      (__int64)pCameraState,
      v19,
      v18,
      *(float *)&v17 * 1.1,
      &v20,
      (__int64)"GPU Mem Total: %4dmb / %4umb",
      v15,
      v14);
  }
}

// --- End Function: sub_1472404F0 (0x1472404F0) ---

// --- Function: sub_1472406B0 (0x1472406B0) ---
char __fastcall sub_1472406B0(unsigned __int64 *pCameraState, float *a2, int a3, char a4)
{
  __int128 v4; // xmm6
  _UNKNOWN **v5; // rax
  char v6; // bp
  int v7; // esi
  unsigned __int64 *pCameraState_1; // r14
  __int64 v10; // rax
  int v11; // r12d
  int v12; // r15d
  int v13; // r14d
  int v14; // ebp
  int v15; // esi
  int v16; // edi
  int v17; // ebx
  double v18; // xmm0_8
  float v19; // xmm1_4
  float v20; // kr00_4
  int v21; // edi
  int v22; // ebx
  double v23; // xmm0_8
  float v24; // xmm2_4
  __int64 v25; // rdi
  double (__fastcall *v26)(__int64, _QWORD); // rbx
  __int64 v27; // rax
  unsigned int v28; // eax
  double v29; // xmm0_8
  double v30; // xmm7_8
  __int128 v31; // xmm0
  double v32; // xmm0_8
  float v33; // xmm6_4
  float v34; // kr00_4
  float v35; // xmm1_4
  int v37; // [rsp+50h] [rbp-88h]
  __int128 v38[3]; // [rsp+70h] [rbp-68h] BYREF
  _UNKNOWN *retaddr; // [rsp+D8h] [rbp+0h] BYREF

  v5 = &retaddr;
  v38[2] = v4;
  v6 = a4;
  v7 = a3;
  pCameraState_1 = pCameraState;
  if ( a3 )
  {
    v10 = (*(__int64 (**)(void))(*(_QWORD *)qword_149A142B0 + 0x258LL))();
    v11 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v10 + 0x80LL))(v10);
    v12 = *(_DWORD *)((*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14200 + 0x40LL))(qword_149A14200) + 8);
    v13 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14290 + 0x2B0LL))(qword_149A14290);
    v14 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14290 + 0x2B8LL))(qword_149A14290);
    v15 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14290 + 0x250LL))(qword_149A14290);
    v16 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14290 + 0x258LL))(qword_149A14290);
    v17 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14290 + 0x260LL))(qword_149A14290);
    v38[0] = xmmword_1480E1F40;
    v18 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
    v19 = *a2;
    v37 = v13;
    pCameraState_1 = pCameraState;
    v20 = a2[1] + a2[2];
    a2[1] = v20;
    sub_147242670(
      (__int64)pCameraState,
      v19,
      v20,
      *(float *)&v18 * 1.1,
      v38,
      (__int64)"Entities: %i, PS: %i, QdBatches: %i, LB: %u, QdFinalize: %u, Net-DeferredFinalize: %u, QdSOC: %i",
      v17,
      v16,
      v15,
      v14,
      v37,
      v12,
      v11);
    v21 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14290 + 0x270LL))(qword_149A14290);
    v22 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14290 + 0x268LL))(qword_149A14290);
    v38[0] = xmmword_1480E1F40;
    v23 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
    v24 = a2[2] + a2[1];
    a2[1] = v24;
    LOBYTE(v5) = sub_147242670(
                   (__int64)pCameraState,
                   *a2,
                   v24,
                   *(float *)&v23 * 1.1,
                   v38,
                   (__int64)"Component updates: %7d, Events handled: %7d",
                   v22,
                   v21);
    v7 = a3;
    v6 = a4;
  }
  if ( qword_149A14288 )
  {
    v5 = (_UNKNOWN **)(*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14288 + 0xA0LL))(qword_149A14288);
    if ( v5 )
    {
      v25 = qword_149A14250;
      v26 = *(double (__fastcall **)(__int64, _QWORD))(*(_QWORD *)qword_149A14250 + 0xC0LL);
      v27 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A14288 + 0xA0LL))(qword_149A14288);
      v28 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v27 + 0x3B8LL))(v27);
      v29 = v26(v25, v28);
      LOBYTE(v5) = (float)(*(float *)&v29 * 1000.0) > 5.0;
      if ( v7 || (float)(*(float *)&v29 * 1000.0) > 5.0 && v6 )
      {
        v30 = (float)(*(float *)&v29 * 1000.0);
        if ( (float)(*(float *)&v29 * 1000.0) <= 5.0 )
          v31 = xmmword_1480E1F40;
        else
          v31 = xmmword_148116840;
        v38[0] = v31;
        v32 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
        v33 = *(float *)&v32 * 1.1;
        *(float *)&v32 = (*(float (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
        v34 = (float)(a2[2] - (float)(*(float *)&v32 + *(float *)&v32)) + a2[1];
        v35 = *a2;
        a2[1] = v34;
        LOBYTE(v5) = sub_147242670((__int64)pCameraState_1, v35, v34, v33, v38, (__int64)"Game: %.2fms", v30);
      }
    }
  }
  return (char)v5;
}

// --- End Function: sub_1472406B0 (0x1472406B0) ---

// --- Function: sub_147240A10 (0x147240A10) ---
__int64 __fastcall sub_147240A10(unsigned __int64 *pCameraState, float *a2, int a3, char a4)
{
  __int64 v8; // rax
  __int64 result; // rax
  bool v10; // dl
  float v11; // xmm0_4
  float v12; // kr00_4
  double v13; // xmm7_8
  float v14; // xmm0_4
  float v15; // kr00_4
  double v16; // xmm6_8
  __int128 v17; // xmm0
  double v18; // xmm0_8
  float v19; // kr00_4
  float v20; // xmm1_4
  float v21; // kr00_4
  double v22; // xmm8_8
  float v23; // xmm1_4
  float v24; // xmm0_4
  double v25; // xmm10_8
  double v26; // xmm9_8
  float v27; // xmm0_4
  float v28; // kr00_4
  double v29; // xmm7_8
  float v30; // xmm0_4
  float v31; // kr00_4
  double v32; // xmm6_8
  __int128 v33; // xmm0
  double v34; // xmm0_8
  float v35; // kr00_4
  float v36; // xmm1_4
  __int128 v37; // [rsp+60h] [rbp-A0h] BYREF
  __int64 v38; // [rsp+70h] [rbp-90h] BYREF
  __int64 v39; // [rsp+78h] [rbp-88h]
  __int64 v40; // [rsp+80h] [rbp-80h]
  __int64 v41; // [rsp+88h] [rbp-78h]
  __int64 v42; // [rsp+90h] [rbp-70h]
  __int64 v43; // [rsp+98h] [rbp-68h]
  __int64 v44; // [rsp+A0h] [rbp-60h]
  __m256 v45; // [rsp+A8h] [rbp-58h]
  __m256 v46; // [rsp+C8h] [rbp-38h]
  __m256 v47; // [rsp+E8h] [rbp-18h]
  __int64 *v48; // [rsp+108h] [rbp+8h]
  __int128 v49; // [rsp+110h] [rbp+10h]
  __int64 v50; // [rsp+120h] [rbp+20h]
  __int64 v51; // [rsp+128h] [rbp+28h]

  v45 = (__m256)0LL;
  v46 = (__m256)0LL;
  v47 = (__m256)0LL;
  v49 = 0;
  v38 = 0;
  v39 = 0;
  v40 = 0;
  v41 = 0;
  v42 = 0;
  v43 = 0;
  v44 = 0;
  v48 = 0;
  v50 = 0;
  v51 = 0;
  __asm { vzeroupper }
  v8 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)qword_149A142B0 + 0x268LL))(qword_149A142B0);
  result = (*(__int64 (__fastcall **)(__int64, __int64 *))(*(_QWORD *)v8 + 0x10LL))(v8, &v38);
  if ( qword_149A14288 )
  {
    if ( !(_BYTE)qword_149A147E6 || BYTE3(qword_149A147E6) )
      goto LABEL_4;
LABEL_12:
    v10 = 0;
    goto LABEL_5;
  }
  if ( (_BYTE)qword_149A147E6 )
    goto LABEL_12;
LABEL_4:
  result = 0x280000000LL;
  v10 = (unsigned __int64)v39 > 0x280000000LL;
LABEL_5:
  if ( a3 || v10 && a4 )
  {
    if ( v48 )
    {
      v21 = (float)v48[0xA];
      v22 = (float)(v21 * 9.3132257e-10);
      v23 = (float)*v48;
      v24 = (float)v48[1];
      v25 = (float)(v24 * 9.3132257e-10);
      v26 = (float)(v23 * 9.3132257e-10);
      if ( v39 < 0 )
      {
        v28 = (float)(v39 & 1 | ((unsigned __int64)v39 >> 1));
        v27 = v28 + v28;
      }
      else
      {
        v27 = (float)v39;
      }
      v29 = (float)(v27 * 9.3132257e-10);
      if ( v40 < 0 )
      {
        v31 = (float)(v40 & 1 | ((unsigned __int64)v40 >> 1));
        v30 = v31 + v31;
      }
      else
      {
        v30 = (float)v40;
      }
      v32 = (float)(v30 * 9.3132257e-10);
      if ( v10 )
        v33 = xmmword_148116840;
      else
        v33 = xmmword_1480E1F40;
      v37 = v33;
      v34 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v35 = a2[2] + a2[1];
      v36 = *a2;
      a2[1] = v35;
      return sub_147242670(
               (__int64)pCameraState,
               v36,
               v35,
               *(float *)&v34 * 1.25,
               &v37,
               (__int64)"Working Set (OS): %5.2f GiB Committed (OS): %5.2f GiB Allocated (Tracked): %5.2f GiB Requested ("
                        "Tracked): %5.2f GiB Committed (Tracked): %5.2f GiB",
               v32,
               v29,
               v25,
               v26,
               v22);
    }
    else
    {
      if ( v39 < 0 )
      {
        v12 = (float)(v39 & 1 | ((unsigned __int64)v39 >> 1));
        v11 = v12 + v12;
      }
      else
      {
        v11 = (float)v39;
      }
      v13 = (float)(v11 * 9.3132257e-10);
      if ( v40 < 0 )
      {
        v15 = (float)(v40 & 1 | ((unsigned __int64)v40 >> 1));
        v14 = v15 + v15;
      }
      else
      {
        v14 = (float)v40;
      }
      v16 = (float)(v14 * 9.3132257e-10);
      if ( v10 )
        v17 = xmmword_148116840;
      else
        v17 = xmmword_1480E1F40;
      v37 = v17;
      v18 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v19 = a2[2] + a2[1];
      v20 = *a2;
      a2[1] = v19;
      return sub_147242670(
               (__int64)pCameraState,
               v20,
               v19,
               *(float *)&v18 * 1.25,
               &v37,
               (__int64)"Working Set (OS): %5.2f GiB Committed (OS): %5.2f GiB",
               v16,
               v13);
    }
  }
  return result;
}

// --- End Function: sub_147240A10 (0x147240A10) ---

// --- Function: sub_147240DB0 (0x147240DB0) ---
void __fastcall sub_147240DB0(unsigned __int64 *pCameraState, float *a2, int a3)
{
  unsigned __int64 v5; // rbx
  __int64 (__fastcall *v6)(unsigned __int64, __int128 *, __int16 *); // rdi
  __int16 n0xFFFF; // ax
  __int64 v8; // rbx
  __int64 v9; // rax
  __int16 n4; // dx
  __int64 v11; // rbx
  _QWORD *v12; // rax
  const char *v13; // rbx
  double v14; // xmm0_8
  float v15; // kr00_4
  float v16; // xmm1_4
  __int16 n0xFFFF_1; // [rsp+40h] [rbp-48h] BYREF
  _BYTE v18[6]; // [rsp+42h] [rbp-46h] BYREF
  unsigned __int64 v19; // [rsp+48h] [rbp-40h] BYREF
  __int128 v20; // [rsp+50h] [rbp-38h] BYREF

  if ( a3 )
  {
    (*(void (__fastcall **)(__int64, unsigned __int64 *))(*(_QWORD *)qword_149A14288 + 0x80LL))(qword_149A14288, &v19);
    if ( is_valid_handle_typeB(&v19) )
    {
      v5 = v19 & 0xFFFFFFFFFFFFLL;
      v6 = *(__int64 (__fastcall **)(unsigned __int64, __int128 *, __int16 *))(*(_QWORD *)(v19 & 0xFFFFFFFFFFFFLL)
                                                                             + 0x340LL);
      n0xFFFF = n0xFFFF_32;
      if ( n0xFFFF_32 == (__int16)0xFFFF )
      {
        n0xFFFF = *(_WORD *)(*(__int64 (__fastcall **)(__int64, _BYTE *, const char *))(*(_QWORD *)qword_149A14298
                                                                                      + 0x10LL))(
                              qword_149A14298,
                              v18,
                              "ISCPlayerMissionLog");
        n0xFFFF_32 = n0xFFFF;
      }
      n0xFFFF_1 = n0xFFFF;
      v8 = *(_QWORD *)v6(v5, &v20, &n0xFFFF_1);
      *(_QWORD *)&v20 = v8;
      if ( v8 )
      {
        v9 = sub_1403B6A80(v8 & 0xFFFFFFFFFFFFLL);
        n4 = *(_WORD *)(v9 + 4);
        if ( n4 != 4
          && *(_WORD *)(v9 + 2) == (HIWORD(v8) & 0xFFF)
          && (n4 == 2 && !*(_QWORD *)NtCurrentTeb_w() || check_handle_access_by_state(&v20)) )
        {
          v11 = v8 & 0xFFFFFFFFFFFFLL;
          v12 = (_QWORD *)(*(__int64 (__fastcall **)(__int64, __int128 *))(*(_QWORD *)v11 + 0x588LL))(v11, &v20);
          if ( *v12 || v12[1] )
          {
            v13 = (const char *)(*(__int64 (__fastcall **)(__int64, const ULONG_PTR *))(*(_QWORD *)v11 + 0x580LL))(
                                  v11,
                                  &Source);
            v20 = xmmword_1480E1F40;
            v14 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
            v15 = a2[2] + a2[1];
            v16 = *a2;
            a2[1] = v15;
            sub_147242670(
              (__int64)pCameraState,
              v16,
              v15,
              *(float *)&v14 * 1.1,
              &v20,
              (__int64)"Tracked mission : %s",
              v13);
          }
        }
      }
    }
  }
}

// --- End Function: sub_147240DB0 (0x147240DB0) ---

// --- Function: sub_147240FB0 (0x147240FB0) ---
__int64 *__fastcall sub_147240FB0(double *pCameraState, float *a2, int a3)
{
  __int128 v3; // xmm7
  __int128 v4; // xmm8
  __int64 *result; // rax
  int n5; // r15d
  unsigned __int64 v9; // rbx
  __int64 v10; // rax
  __int16 n4; // cx
  unsigned __int64 v12; // rcx
  const char *p_(working); // rdi
  const char *v14; // rbx
  double v15; // xmm0_8
  float v16; // xmm1_4
  float v17; // kr00_4
  __int64 *v18; // rbx
  double v19; // xmm0_8
  double v20; // xmm1_8
  double v21; // xmm2_8
  __int64 v22; // rax
  double v23; // xmm0_8
  float v24; // xmm2_4
  float v25; // xmm1_4
  double v26; // xmm0_8
  __int64 v27; // rdi
  __int64 (__fastcall *v28)(__int64, __int128 *, double *, __int64, int); // r12
  unsigned __int64 v29; // rbx
  __int64 v30; // rax
  __int16 n4_1; // cx
  __int64 v32; // r9
  double *v33; // rax
  double v34; // xmm8_8
  __int128 v35; // xmm0
  double v36; // xmm2_8
  double v37; // xmm3_8
  __int64 v38; // rax
  __int128 v39; // kr00_16
  float v49; // xmm1_4
  int n5_2; // edi
  const char *v56; // rbx
  double v57; // xmm0_8
  float v58; // xmm2_4
  float v59; // xmm1_4
  double v60; // xmm0_8
  float v61; // kr00_4
  float v62; // xmm1_4
  int v63; // [rsp+28h] [rbp-E0h]
  double v64; // [rsp+38h] [rbp-D0h]
  __int128 v65; // [rsp+38h] [rbp-D0h]
  __int128 v66; // [rsp+40h] [rbp-C8h]
  unsigned __int64 v67; // [rsp+58h] [rbp-B0h] BYREF
  __int128 v68; // [rsp+68h] [rbp-A0h] BYREF
  double v69; // [rsp+78h] [rbp-90h]
  double v70; // [rsp+88h] [rbp-80h] BYREF
  __int128 v71; // [rsp+90h] [rbp-78h]
  __int64 v72; // [rsp+A0h] [rbp-68h] BYREF
  unsigned __int64 v73; // [rsp+A8h] [rbp-60h] BYREF
  __int128 v74; // [rsp+B0h] [rbp-58h] BYREF
  _QWORD v75[4]; // [rsp+C0h] [rbp-48h] BYREF
  __int128 v76; // [rsp+E8h] [rbp-20h]
  __int128 v77; // [rsp+F8h] [rbp-10h]
  _UNKNOWN *retaddr; // [rsp+140h] [rbp+38h] BYREF
  int n5_1; // [rsp+160h] [rbp+58h] BYREF

  result = (__int64 *)&retaddr;
  if ( qword_149A14398 && a3 )
  {
    (*(void (__fastcall **)(__int64, __int64 *))(*(_QWORD *)qword_149A14398 + 0x668LL))(qword_149A14398, &v72);
    (*(void (__fastcall **)(__int64, unsigned __int64 *, __int64))(*(_QWORD *)qword_149A14398 + 0x2D0LL))(
      qword_149A14398,
      &v67,
      v72);
    n5 = 0;
    if ( v67
      && (v9 = HIWORD(v67), v10 = sub_1403B6A80(v67 & 0xFFFFFFFFFFFFLL), n4 = *(_WORD *)(v10 + 4), n4 != 4)
      && *(_WORD *)(v10 + 2) == (v9 & 0xFFF)
      && (n4 == 2 && !*(_QWORD *)NtCurrentTeb_w() || check_handle_access_by_state(&v67)) )
    {
      v12 = *(_QWORD *)((v67 & 0xFFFFFFFFFFFFLL) + 8);
    }
    else
    {
      v12 = 0;
    }
    v73 = v12;
    if ( v72 && is_valid_handle_typeA((__int64 *)&v67) && is_valid_handle_typeB(&v73) )
    {
      p_(working) = (const char *)&Source;
      if ( (*(unsigned __int8 (**)(void))(*(_QWORD *)qword_149A14398 + 0x2E8LL))() )
        p_(working) = "(working)";
      v14 = (const char *)(*(__int64 (__fastcall **)(unsigned __int64))(*(_QWORD *)(v73 & 0xFFFFFFFFFFFFLL) + 0x70LL))(v73 & 0xFFFFFFFFFFFFLL);
      v68 = xmmword_1480E1F40;
      v15 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v16 = *a2;
      v17 = a2[1] + a2[2];
      a2[1] = v17;
      sub_147242670(
        (__int64)pCameraState,
        v16,
        v17,
        *(float *)&v15 * 1.25,
        &v68,
        (__int64)"Planet:%s %s",
        v14,
        p_(working));
      result = (__int64 *)(*(__int64 (__fastcall **)(__int64))(*(_QWORD *)(*(_QWORD *)((v67 & 0xFFFFFFFFFFFFLL) + 8)
                                                                         & 0xFFFFFFFFFFFFLL)
                                                             + 0x668LL))(*(_QWORD *)((v67 & 0xFFFFFFFFFFFFLL) + 8) & 0xFFFFFFFFFFFFLL);
      v18 = result;
      v19 = pCameraState[0x9D];
      v20 = pCameraState[0xA1];
      v21 = pCameraState[0xA5];
      *(double *)v75 = v19;
      *(double *)&v75[1] = v20;
      *(double *)&v75[2] = v21;
      if ( result && (v19 != 0.0 || v20 != 0.0 || v21 != 0.0) )
      {
        result = (__int64 *)(*(__int64 (__fastcall **)(__int64 *, double *, _QWORD *))(*result + 0xF8))(
                              result,
                              &v70,
                              v75);
        if ( v70 != 0.0 || *(double *)&v71 != 0.0 || *((double *)&v71 + 1) != 0.0 )
        {
          v22 = *v18;
          v77 = v3;
          v76 = v4;
          if ( *((_DWORD *)pCameraState + 0x15E) != (*(unsigned int (__fastcall **)(__int64 *))(v22 + 0x1F8))(v18) )
          {
            v68 = xmmword_1480E1F40;
            v23 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
            v24 = a2[2] + a2[1];
            v25 = *a2;
            v66 = v71;
            v64 = v70;
            a2[1] = v24;
            sub_147242670(
              (__int64)pCameraState,
              v25,
              v24,
              *(float *)&v23 * 1.25,
              &v68,
              (__int64)"CamPos Planet Zone: %f %f %f",
              v64,
              *(double *)&v66,
              *((double *)&v66 + 1));
          }
          v26 = (*(double (__fastcall **)(__int64, __int64))(*(_QWORD *)qword_149A14398 + 0x98LL))(qword_149A14398, v72);
          v27 = qword_149A14398;
          v28 = *(__int64 (__fastcall **)(__int64, __int128 *, double *, __int64, int))(*(_QWORD *)qword_149A14398
                                                                                      + 0x5B8LL);
          if ( v67
            && (v29 = HIWORD(v67), v30 = sub_1403B6A80(v67 & 0xFFFFFFFFFFFFLL), n4_1 = *(_WORD *)(v30 + 4), n4_1 != 4)
            && *(_WORD *)(v30 + 2) == (v29 & 0xFFF)
            && (n4_1 == 2 && !*(_QWORD *)NtCurrentTeb_w() || check_handle_access_by_state(&v67)) )
          {
            v32 = v67 & 0xFFFFFFFFFFFFLL;
          }
          else
          {
            v32 = 0;
          }
          LOBYTE(v63) = 0;
          v33 = (double *)v28(v27, &v68, &v70, v32, v63);
          v34 = *(float *)&v26;
          v35 = *(unsigned __int64 *)v33;
          v36 = v33[1];
          v37 = v33[2];
          v38 = *(_QWORD *)qword_149A142E8;
          *((_QWORD *)&v39 + 1) = *((_QWORD *)&v35 + 1);
          *(double *)&v39 = *(double *)&v35 * *(double *)&v35 + v36 * v36 + v37 * v37;
          _XMM2 = v39;
          __asm
          {
            vmovddup xmm0, xmm2
            vsqrtpd xmm3, xmm0
            vunpckhpd xmm3, xmm3, xmm3
          }
          *((_QWORD *)&v39 + 1) = *((_QWORD *)&_XMM3 + 1);
          *(double *)&v39 = *(double *)&_XMM3 - v34;
          _XMM0 = v39;
          __asm { vcvtsd2ss xmm7, xmm0, xmm0 }
          _XMM2 = COERCE_UNSIGNED_INT64(v70 * v70 + *(double *)&v71 * *(double *)&v71 + *((double *)&v71 + 1)
                                                                                      * *((double *)&v71 + 1));
          __asm
          {
            vmovddup xmm3, xmm2
            vsqrtpd xmm6, xmm3
          }
          v68 = xmmword_1480E1F40;
          *(double *)&_XMM0 = (*(double (__fastcall **)(_LocaleUpdate *))(v38 + 0x208))(qword_149A142E8);
          *(float *)&_XMM2 = a2[2] + a2[1];
          v49 = *a2;
          __asm { vunpckhpd xmm6, xmm6, xmm6 }
          a2[1] = *(float *)&_XMM2;
          sub_147242670(
            (__int64)pCameraState,
            v49,
            *(float *)&_XMM2,
            *(float *)&_XMM0 * 1.25,
            &v68,
            (__int64)"Radius: %f ElevationUnderCam: %f Altitude %f",
            v34,
            *(float *)&_XMM7,
            *(double *)&_XMM6 - *(float *)&_XMM7);
          _XMM1 = COERCE_UNSIGNED_INT64(
                    v70 * v70
                  + *(double *)&v71 * *(double *)&v71
                  + *((double *)&v71 + 1) * *((double *)&v71 + 1)
                  + 2.225073858507201e-308);
          __asm
          {
            vmovddup xmm2, xmm1
            vsqrtpd xmm3, xmm2
            vunpckhpd xmm3, xmm3, xmm3
          }
          *(double *)&v68 = 1.0 / *(double *)&_XMM3 * v70;
          v69 = 1.0 / *(double *)&_XMM3 * *((double *)&v71 + 1);
          *((double *)&v68 + 1) = 1.0 / *(double *)&_XMM3 * *(double *)&v71;
          sub_140405A10((double *)&v74, (double *)&v68, v34, &n5_1);
          n5_2 = n5_1;
          if ( n5_1 >= 0 )
          {
            n5 = 5;
            if ( n5_1 < 5 )
              n5 = n5_1;
          }
          v68 = xmmword_1480E1F40;
          v56 = off_1499C1978[n5];              // "+X"
          v57 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
          v58 = a2[2] + a2[1];
          v59 = *a2;
          v65 = v74;
          a2[1] = v58;
          return (__int64 *)sub_147242670(
                              (__int64)pCameraState,
                              v59,
                              v58,
                              *(float *)&v57 * 1.25,
                              &v68,
                              (__int64)"XYPos: %f %f Page: %i (%s)",
                              *(double *)&v65,
                              *((double *)&v65 + 1),
                              n5_2,
                              v56);
        }
      }
    }
    else
    {
      v68 = xmmword_1480E1F40;
      v60 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v61 = a2[2] + a2[1];
      v62 = *a2;
      a2[1] = v61;
      return (__int64 *)sub_147242670(
                          (__int64)pCameraState,
                          v62,
                          v61,
                          *(float *)&v60 * 1.25,
                          &v68,
                          (__int64)"No Current Planet");
    }
  }
  return result;
}

// --- End Function: sub_147240FB0 (0x147240FB0) ---

// --- Function: sub_147241610 (0x147241610) ---
char __fastcall sub_147241610(unsigned __int64 *pCameraState, float *a2, int n2, char a4)
{
  __int128 v4; // xmm6
  __int128 v5; // xmm7
  __int128 v6; // xmm8
  _LocaleUpdate *v7; // rdi
  float v12; // xmm7_4
  float (__fastcall *v13)(_LocaleUpdate *, __int64); // rbx
  __m128 v14; // xmm0
  __int128 v16; // kr00_16
  float v18; // kr00_4
  char result; // al
  double v20; // xmm6_8
  double v21; // xmm7_8
  double v22; // xmm8_8
  __int128 v23; // xmm0
  double v24; // xmm0_8
  float v25; // kr00_4
  float v26; // xmm1_4
  __int128 v27[4]; // [rsp+50h] [rbp-58h] BYREF

  v7 = qword_149A142E8;
  v27[3] = v4;
  v27[2] = v5;
  v12 = a2[5];
  v27[1] = v6;
  v13 = *(float (__fastcall **)(_LocaleUpdate *, __int64))(*(_QWORD *)qword_149A142E8 + 0x838LL);
  (*(void (__fastcall **)(__int64))(*(_QWORD *)qword_149A14250 + 0xE8LL))(qword_149A14250);
  v14 = sub_140598DA0();
  *((_QWORD *)&v16 + 1) = v14.m128_u64[1];
  *(double *)&v16 = *(double *)v14.m128_u64 * 1000.0;
  _XMM0 = v16;
  __asm { vcvtsd2ss xmm6, xmm0, xmm0 }
  *(float *)&dword_1514B85C0 = (float)((float)(1.0 - v12) * *(float *)&dword_1514B85C0)
                             + (float)((float)(*(float *)&_XMM6 - v13(v7, 2)) * v12);
  *(float *)&_XMM6 = a2[5];
  *(float *)&dword_1514B85C4 = (float)((float)(1.0 - *(float *)&_XMM6) * *(float *)&dword_1514B85C4)
                             + (float)(*(float *)&_XMM6
                                     * (*(float (__fastcall **)(_LocaleUpdate *, __int64))(*(_QWORD *)qword_149A142E8
                                                                                         + 0x838LL))(
                                         qword_149A142E8,
                                         1));
  *(float *)&_XMM6 = a2[5];
  v18 = (float)((float)(1.0 - *(float *)&_XMM6) * *(float *)&dword_1514B85C8)
      + (float)(*(float *)&_XMM6
              * (*(float (__fastcall **)(_LocaleUpdate *, _QWORD))(*(_QWORD *)qword_149A142E8 + 0x838LL))(
                  qword_149A142E8,
                  0));
  *(float *)&dword_1514B85C8 = v18;
  result = v18 >= 0.0166 || *(float *)&dword_1514B85C4 > 0.0166 || *(float *)&dword_1514B85C0 > 0.0040000002;
  if ( n2 >= 2 || result && a4 )
  {
    v20 = v18;
    v21 = *(float *)&dword_1514B85C4;
    v22 = *(float *)&dword_1514B85C0;
    if ( result )
      v23 = xmmword_148116840;
    else
      v23 = xmmword_1480E1F40;
    v27[0] = v23;
    v24 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
    v25 = a2[2] + a2[1];
    v26 = *a2;
    a2[1] = v25;
    return sub_147242670(
             (__int64)pCameraState,
             v26,
             v25,
             *(float *)&v24 * 1.1,
             v27,
             (__int64)"Render: MT: %3.1fms RT: %3.1fms GPU: %3.1fms",
             v22,
             v21,
             v20);
  }
  return result;
}

// --- End Function: sub_147241610 (0x147241610) ---

// --- Function: sub_147241840 (0x147241840) ---
void __fastcall sub_147241840(unsigned __int64 *pCameraState, float *a2, unsigned int n5)
{
  __int64 v5; // rax
  int v6; // r12d
  __int64 v7; // rax
  int v8; // r15d
  __int64 v9; // rax
  int v10; // edi
  __int64 v11; // rax
  int v12; // esi
  char *p_Buffer; // rbp
  double v14; // xmm0_8
  float v15; // xmm1_4
  float v16; // kr00_4
  const char *p_Vulkan; // rax
  double v18; // xmm0_8
  float v19; // xmm2_4
  float v20; // xmm1_4
  double v21; // xmm0_8
  float v22; // xmm2_4
  float v23; // xmm1_4
  double v24; // xmm0_8
  float v25; // xmm2_4
  float v26; // xmm1_4
  float v27; // [rsp+40h] [rbp-88h] BYREF
  char *p_Buffer_1; // [rsp+48h] [rbp-80h] BYREF
  __int128 v29; // [rsp+50h] [rbp-78h] BYREF
  char Buffer[32]; // [rsp+60h] [rbp-68h] BYREF

  if ( n5 )
  {
    v5 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)qword_149A142A0 + 0xC0LL))(
           qword_149A142A0,
           "r_DeviceType");
    if ( v5 )
      v6 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v5 + 0x10LL))(v5);
    else
      v6 = 0;
    v7 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)qword_149A142A0 + 0xC0LL))(
           qword_149A142A0,
           "r_GfxReconstructEnabled");
    if ( v7 )
      v8 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v7 + 0x10LL))(v7);
    else
      v8 = 0;
    v9 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)qword_149A142A0 + 0xC0LL))(
           qword_149A142A0,
           "r_RenderDocEnabled");
    if ( v9 )
      v10 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v9 + 0x10LL))(v9);
    else
      v10 = 0;
    v11 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)qword_149A142A0 + 0xC0LL))(
            qword_149A142A0,
            "r_vulkanCPUValidation");
    if ( v11 )
      v12 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v11 + 0x10LL))(v11);
    else
      v12 = 0;
    p_Buffer_1 = 0;
    (*(void (__fastcall **)(_LocaleUpdate *, __int64, char **))(*(_QWORD *)qword_1514B8088 + 0x8E8LL))(
      qword_1514B8088,
      0x17,
      &p_Buffer_1);
    (*(void (__fastcall **)(_LocaleUpdate *, __int64, float *))(*(_QWORD *)qword_1514B8088 + 0x8E8LL))(
      qword_1514B8088,
      0x18,
      &v27);
    sprintf_s<32>((char (*)[32])Buffer, "%s-%i%%", p_Buffer_1, (int)(float)(v27 * 100.0));
    p_Buffer = p_Buffer_1;
    if ( v27 != 1.0 )
      p_Buffer = Buffer;
    v29 = xmmword_1480E1F40;
    v14 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
    v15 = *a2;
    v16 = a2[1] + a2[2];
    p_Vulkan = "D3D11";
    if ( v6 )
      p_Vulkan = "Vulkan";
    a2[1] = v16;
    sub_147242670(
      (__int64)pCameraState,
      v15,
      v16,
      *(float *)&v14 * 1.1,
      &v29,
      (__int64)"Graphics Renderer : %s (%s)",
      p_Vulkan,
      p_Buffer);
    if ( v8 )
    {
      v29 = xmmword_1480E1F40;
      v18 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v19 = a2[2] + a2[1];
      v20 = *a2;
      a2[1] = v19;
      sub_147242670((__int64)pCameraState, v20, v19, *(float *)&v18 * 1.1, &v29, (__int64)"GfxReconstruct: Enabled");
    }
    if ( v10 )
    {
      v29 = xmmword_1480E1F40;
      v21 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v22 = a2[2] + a2[1];
      v23 = *a2;
      a2[1] = v22;
      sub_147242670((__int64)pCameraState, v23, v22, *(float *)&v21 * 1.1, &v29, (__int64)"RenderDoc: Enabled");
    }
    if ( v12 )
    {
      v29 = xmmword_148116840;
      v24 = (*(double (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8);
      v25 = a2[2] + a2[1];
      v26 = *a2;
      a2[1] = v25;
      sub_147242670((__int64)pCameraState, v26, v25, *(float *)&v24 * 1.1, &v29, (__int64)"VULKAN VALIDATION: ENABLED");
    }
  }
}

// --- End Function: sub_147241840 (0x147241840) ---

// --- Function: sub_147241BE0 (0x147241BE0) ---
void __fastcall sub_147241BE0(unsigned __int64 *pCameraState, float *a2, int a3)
{
  char *v5; // rdx
  __m128 v6; // xmm0
  __int128 v8; // kr00_16
  float v10; // xmm10_4
  float v11; // xmm9_4
  float v12; // xmm5_4
  unsigned __int64 n0x60; // rcx
  double v25; // xmm6_8
  double v26; // xmm0_8
  float v27; // xmm2_4
  float v28; // xmm1_4
  __int128 v29; // [rsp+60h] [rbp-68h] BYREF

  if ( a3 && byte_149A147E5 && !byte_149A14490 )
  {
    (*(__int64 (**)(void))(*(_QWORD *)qword_149A14200 + 0x40LL))();
    v6 = sub_140598DA0();
    *((_QWORD *)&v8 + 1) = v6.m128_u64[1];
    *(double *)&v8 = *(double *)v6.m128_u64 * 1000.0;
    _XMM0 = v8;
    __asm { vcvtsd2ss xmm8, xmm0, xmm0 }
    v10 = 0.0;
    if ( _XMM8.m128_f32[0] <= 0.00000011920929 )
      v11 = 0.0;
    else
      v11 = 1000.0 / _XMM8.m128_f32[0];
    v12 = (float)(*(float *)&dword_1514B85DC * 0.80000001) + (float)(v11 * 0.2);
    _XMM1 = _mm_shuffle_ps(_XMM8, _XMM8, 0);
    _XMM2 = _XMM1;
    *(float *)&dword_1514B85DC = v12;
    for ( n0x60 = 0; n0x60 < 0x60; n0x60 += 8LL )
    {
      __asm
      {
        vmaxps  xmm1, xmm1, xmmword ptr [r8+rcx*4]
        vmaxps  xmm2, xmm2, xmmword ptr [r8+rcx*4+10h]
      }
    }
    __asm
    {
      vmaxps  xmm1, xmm1, xmm2
      vmovhlps xmm0, xmm1, xmm1
      vmaxps  xmm7, xmm0, xmm1
    }
    _mm_shuffle_ps(_XMM7, _XMM7, 0xF5);
    __asm { vmaxss  xmm7, xmm7, xmm0 }
    if ( n0x60 < 0x64 )
    {
      if ( 0x64 - n0x60 < 4 )
        goto LABEL_22;
      v5 = byte_1514B85E8;
      do
      {
        _XMM0 = *((unsigned int *)&qword_1514B85E0 + n0x60);
        __asm
        {
          vmaxss  xmm1, xmm0, xmm7
          vmaxss  xmm0, xmm1, dword ptr [r8+rcx*4+4]
          vmaxss  xmm1, xmm0, dword ptr [rdx+rcx*4]
          vmaxss  xmm7, xmm1, dword ptr [r9+rcx*4]
        }
        n0x60 += 4LL;
      }
      while ( n0x60 < 0x61 );
      if ( n0x60 < 0x64 )
      {
LABEL_22:
        do
        {
          _XMM0 = *((unsigned int *)&qword_1514B85E0 + n0x60++);
          __asm { vmaxss  xmm7, xmm0, xmm7 }
        }
        while ( n0x60 < 0x64 );
      }
    }
    if ( _XMM8.m128_f32[0] != *((float *)&qword_1514B85E0 + qword_1514B8770) )
    {
      v5 = (char *)(((unsigned __int64)(qword_1514B8770 + 1) * (unsigned __int128)0x47AE147AE147AE15uLL) >> 0x40);
      qword_1514B8770 = (qword_1514B8770 + 1) % 0x64uLL;
      *((float *)&qword_1514B85E0 + qword_1514B8770) = _XMM8.m128_f32[0];
    }
    if ( *(float *)&_XMM7 > 0.00000011920929 )
      v10 = 1000.0 / *(float *)&_XMM7;
    v25 = v12;
    v29 = xmmword_1480E1F40;
    v26 = (*(double (__fastcall **)(_LocaleUpdate *, char *, __int64 *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(
            qword_149A142E8,
            v5,
            &qword_1514B85E0);
    v27 = a2[2] + a2[1];
    v28 = *a2;
    a2[1] = v27;
    sub_147242670(
      (__int64)pCameraState,
      v28,
      v27,
      *(float *)&v26 * 1.1,
      &v29,
      (__int64)"Server FPS: %.1f (%.1fms) Avg: %.1f Min: %.1f (%.1fms)",
      v11,
      _XMM8.m128_f32[0],
      v25,
      v10,
      *(float *)&_XMM7);
  }
}

// --- End Function: sub_147241BE0 (0x147241BE0) ---

// --- Function: sub_147242670 (0x147242670) ---
__int64 sub_147242670(__int64 a1, float a2, float a3, float a4, __int128 *a5, __int64 a6, ...)
{
  __int64 v6; // rax
  double v8[3]; // [rsp+30h] [rbp-48h] BYREF
  int n0xB2; // [rsp+48h] [rbp-30h] BYREF
  __int128 v10; // [rsp+4Ch] [rbp-2Ch]
  float v11; // [rsp+5Ch] [rbp-1Ch]
  float v12; // [rsp+60h] [rbp-18h]
  va_list va; // [rsp+B0h] [rbp+38h] BYREF

  va_start(va, a6);
  v12 = a4;
  v10 = *a5;
  v11 = a4;
  n0xB2 = 0xB2;
  v6 = *(_QWORD *)qword_149A142E8;
  v8[0] = a2;
  v8[2] = 1.0;
  v8[1] = a3;
  return (*(__int64 (__fastcall **)(_LocaleUpdate *, double *, int *, __int64, __int64 *))(v6 + 0x560))(
           qword_149A142E8,
           v8,
           &n0xB2,
           a6,
           (__int64 *)va);
}

// --- End Function: sub_147242670 (0x147242670) ---

// --- Function: sub_147242710 (0x147242710) ---
double sub_147242710(
        unsigned __int64 *pCameraState,
        float a2,
        float a3,
        const char *p_CamDir:_%3d_%3d_%4d_FOV:_%.0f_Focal:_%.2f_FStop:_%.1f,
        ...)
{
  __int128 v4; // xmm6
  __int128 v5; // xmm7
  __int64 v6; // rax
  double result; // xmm0_8
  double v8[3]; // [rsp+30h] [rbp-68h] BYREF
  int n0xB2; // [rsp+48h] [rbp-50h] BYREF
  __int128 v10; // [rsp+4Ch] [rbp-4Ch]
  float v11; // [rsp+5Ch] [rbp-3Ch]
  float v12; // [rsp+60h] [rbp-38h]
  __int128 v13; // [rsp+70h] [rbp-28h]
  __int128 v14; // [rsp+80h] [rbp-18h]
  va_list va; // [rsp+C0h] [rbp+28h] BYREF

  va_start(va, p_CamDir:_%3d_%3d_%4d_FOV:_%.0f_Focal:_%.2f_FStop:_%.1f);
  v14 = v4;
  v13 = v5;
  v12 = 1.0;
  v10 = xmmword_1480E1F40;
  n0xB2 = 0xB2;
  v12 = (*(float (__fastcall **)(_LocaleUpdate *))(*(_QWORD *)qword_149A142E8 + 0x208LL))(qword_149A142E8) * 1.25;
  v11 = v12;
  v6 = *(_QWORD *)qword_149A142E8;
  v8[0] = a2;
  result = 1.0;
  v8[2] = 1.0;
  v8[1] = a3;
  (*(void (__fastcall **)(_LocaleUpdate *, double *, int *, const char *, __int64 *))(v6 + 0x560))(
    qword_149A142E8,
    v8,
    &n0xB2,
    p_CamDir:_%3d_%3d_%4d_FOV:_%.0f_Focal:_%.2f_FStop:_%.1f,
    (__int64 *)va);
  return result;
}

// --- End Function: sub_147242710 (0x147242710) ---

// --- Function: __security_check_cookie (0x147F6A880) ---
void __cdecl _security_check_cookie(uintptr_t StackCookie)
{
  __int64 v1; // rcx

  if ( StackCookie != _security_cookie )
ReportFailure:
    _report_gsfailure(StackCookie);
  v1 = __ROL8__(StackCookie, 0x10);
  if ( (_WORD)v1 )
  {
    StackCookie = __ROR8__(v1, 0x10);
    goto ReportFailure;
  }
}

// --- End Function: __security_check_cookie (0x147F6A880) ---

// --- Function: __report_gsfailure (0x147F6AA7C) ---
void __cdecl __noreturn _report_gsfailure(uintptr_t StackCookie)
{
  DWORD64 retaddr; // [rsp+38h] [rbp+0h]
  DWORD64 StackCookie_1; // [rsp+40h] [rbp+8h] BYREF

  StackCookie_1 = StackCookie;
  if ( IsProcessorFeaturePresent(0x17u) )
    __fastfail(2u);
  capture_previous_context(&ContextRecord);
  ContextRecord.Rip = retaddr;
  ContextRecord.Rsp = (DWORD64)&StackCookie_1;
  qword_1515EE080 = retaddr;
  ContextRecord.Rcx = StackCookie_1;
  dword_1515EE070 = 0xC0000409;
  dword_1515EE074 = 1;
  dword_1515EE088 = 1;
  qword_1515EE090[0] = 2;
  _raise_securityfailure((struct _EXCEPTION_POINTERS *)&ExceptionInfo);
}

// --- End Function: __report_gsfailure (0x147F6AA7C) ---

// --- Function: memset (0x147FB92B7) ---
// attributes: thunk
void *__cdecl memset(void *a1, int Val, size_t Size)
{
  return __imp_memset(a1, Val, Size);
}

// --- End Function: memset (0x147FB92B7) ---

// --- Function: asinf (0x147FB93A7) ---
// attributes: thunk
float __cdecl asinf(float X)
{
  return __imp_asinf(X);
}

// --- End Function: asinf (0x147FB93A7) ---

// --- Function: atan2f (0x147FB93AD) ---
// attributes: thunk
float __cdecl atan2f(float Y, float X)
{
  return __imp_atan2f(Y, X);
}

// --- End Function: atan2f (0x147FB93AD) ---

