// Decompiled code dump generated by Code Dumper (Callers/Callees/Refs)
// Start Function: 0x147220700 (sub_147220700)
// Caller Depth: 1
// Callee/Ref Depth: 4
// Total Functions Found: 18
// ------------------------------------------------------------

// --- Function: ?StopProfileThreadUsage@MemoryMgr@AK@@YA_KXZ (0x1402A1370) ---
__int64 __fastcall AK::MemoryMgr::StopProfileThreadUsage(struct _exception *a1)
{
  return 0LL;
}

// --- End Function: ?StopProfileThreadUsage@MemoryMgr@AK@@YA_KXZ (0x1402A1370) ---

// --- Function: sub_1402A1E30 (0x1402A1E30) ---
__int64 __fastcall sub_1402A1E30(unsigned __int64 n0x6400000)
{
  return sub_14739AFC0(n0x6400000, 0LL);
}

// --- End Function: sub_1402A1E30 (0x1402A1E30) ---

// --- Function: sub_1402DE890 (0x1402DE890) ---
__int64 __fastcall sub_1402DE890(__int64 **a1, __int64 a2, __int64 a3)
{
  __int64 *v4; // r11
  __int64 *v6; // rax
  __int64 result; // rax
  _QWORD *v8; // rax
  __int64 v9; // rdx
  __int64 *v10; // r8
  __int64 v11; // rcx
  __int64 v12; // rcx
  _QWORD *v13; // r8
  _QWORD *v14; // rcx
  _QWORD *v15; // rdx
  _QWORD *v16; // r8
  __int64 v17; // rcx
  _QWORD *v18; // rcx
  _QWORD *v19; // r8
  __int64 v20; // rcx
  _QWORD *v21; // rcx
  _QWORD *v22; // rcx

  a1[1] = (__int64 *)((char *)a1[1] + 1);
  v4 = *a1;
  v6 = *(__int64 **)a2;
  *(_QWORD *)(a3 + 8) = *(_QWORD *)a2;
  if ( v6 == v4 )
  {
    *v4 = a3;
    result = a3;
    v4[1] = a3;
    v4[2] = a3;
    *(_BYTE *)(a3 + 24) = 1;
    return result;
  }
  if ( *(_DWORD *)(a2 + 8) )
  {
    *v6 = a3;
    if ( v6 == (__int64 *)*v4 )
    {
      *v4 = a3;
    }
  }
  else
  {
    v6[2] = a3;
    if ( v6 == (__int64 *)v4[2] )
    {
      v4[2] = a3;
    }
  }
  v8 = (_QWORD *)a3;
  while ( !*(_BYTE *)(v8[1] + 24LL) )
  {
    v9 = v8[1];
    v10 = *(__int64 **)(v9 + 8);
    v11 = *v10;
    if ( v9 == *v10 )
    {
      v12 = v10[2];
      if ( *(_BYTE *)(v12 + 24) )
      {
        v13 = *(_QWORD **)(v9 + 16);
        if ( v8 == v13 )
        {
          v8 = (_QWORD *)v8[1];
          *(_QWORD *)(v9 + 16) = *v13;
          if ( !*(_BYTE *)(*v13 + 25LL) )
          {
            *(_QWORD *)(*v13 + 8LL) = v9;
          }
          v13[1] = *(_QWORD *)(v9 + 8);
          if ( v9 == (*a1)[1] )
          {
            (*a1)[1] = (__int64)v13;
          }
          else
          {
            v14 = *(_QWORD **)(v9 + 8);
            if ( v9 == *v14 )
            {
              *v14 = v13;
            }
            else
            {
              v14[2] = v13;
            }
          }
          *v13 = v9;
          *(_QWORD *)(v9 + 8) = v13;
        }
        *(_BYTE *)(v8[1] + 24LL) = 1;
        *(_BYTE *)(*(_QWORD *)(v8[1] + 8LL) + 24LL) = 0;
        v15 = *(_QWORD **)(v8[1] + 8LL);
        v16 = (_QWORD *)*v15;
        *v15 = *(_QWORD *)(*v15 + 16LL);
        v17 = v16[2];
        if ( !*(_BYTE *)(v17 + 25) )
        {
          *(_QWORD *)(v17 + 8) = v15;
        }
        v16[1] = v15[1];
        if ( v15 == (_QWORD *)(*a1)[1] )
        {
          (*a1)[1] = (__int64)v16;
          v16[2] = v15;
        }
        else
        {
          v18 = (_QWORD *)v15[1];
          if ( v15 == (_QWORD *)v18[2] )
          {
            v18[2] = v16;
          }
          else
          {
            *v18 = v16;
          }
          v16[2] = v15;
        }
LABEL_48:
        v15[1] = v16;
        continue;
      }
      *(_BYTE *)(v9 + 24) = 1;
      *(_BYTE *)(v12 + 24) = 1;
      *(_BYTE *)(*(_QWORD *)(v8[1] + 8LL) + 24LL) = 0;
      v8 = *(_QWORD **)(v8[1] + 8LL);
    }
    else
    {
      if ( *(_BYTE *)(v11 + 24) )
      {
        v19 = *(_QWORD **)v9;
        if ( v8 == *(_QWORD **)v9 )
        {
          v8 = (_QWORD *)v8[1];
          *(_QWORD *)v9 = v19[2];
          v20 = v19[2];
          if ( !*(_BYTE *)(v20 + 25) )
          {
            *(_QWORD *)(v20 + 8) = v9;
          }
          v19[1] = *(_QWORD *)(v9 + 8);
          if ( v9 == (*a1)[1] )
          {
            (*a1)[1] = (__int64)v19;
          }
          else
          {
            v21 = *(_QWORD **)(v9 + 8);
            if ( v9 == v21[2] )
            {
              v21[2] = v19;
            }
            else
            {
              *v21 = v19;
            }
          }
          v19[2] = v9;
          *(_QWORD *)(v9 + 8) = v19;
        }
        *(_BYTE *)(v8[1] + 24LL) = 1;
        *(_BYTE *)(*(_QWORD *)(v8[1] + 8LL) + 24LL) = 0;
        v15 = *(_QWORD **)(v8[1] + 8LL);
        v16 = (_QWORD *)v15[2];
        v15[2] = *v16;
        if ( !*(_BYTE *)(*v16 + 25LL) )
        {
          *(_QWORD *)(*v16 + 8LL) = v15;
        }
        v16[1] = v15[1];
        if ( v15 == (_QWORD *)(*a1)[1] )
        {
          (*a1)[1] = (__int64)v16;
        }
        else
        {
          v22 = (_QWORD *)v15[1];
          if ( v15 == (_QWORD *)*v22 )
          {
            *v22 = v16;
          }
          else
          {
            v22[2] = v16;
          }
        }
        *v16 = v15;
        goto LABEL_48;
      }
      *(_BYTE *)(v9 + 24) = 1;
      *(_BYTE *)(v11 + 24) = 1;
      *(_BYTE *)(*(_QWORD *)(v8[1] + 8LL) + 24LL) = 0;
      v8 = *(_QWORD **)(v8[1] + 8LL);
    }
  }
  *(_BYTE *)(v4[1] + 24) = 1;
  return a3;
}

// --- End Function: sub_1402DE890 (0x1402DE890) ---

// --- Function: unknown_libname_7 (0x1402DEE80) ---
// Microsoft VisualC v14 64bit runtime
void __noreturn unknown_libname_7()
{
  std::_Xlength_error("map/set too long");
}

// --- End Function: unknown_libname_7 (0x1402DEE80) ---

// --- Function: sub_1403577C0 (0x1403577C0) ---
void **__fastcall sub_1403577C0(void **a1, const void **a2)
{
  size_t Size; // rsi
  _DWORD *v5; // rax

  *a1 = (char *)&qword_149808ABC + 4;
  Size = *((int *)*a2 - 2);
  if ( (_DWORD)Size )
  {
    v5 = (_DWORD *)sub_14739AFC0(Size + 9, 0);
    *a1 = v5 + 2;
    *v5 = Size;
    v5[1] = Size;
    *((_BYTE *)*a1 + Size) = 0;
    if ( *a1 != *a2 )
    {
      memcpy(*a1, *a2, Size);
    }
  }
  return a1;
}

// --- End Function: sub_1403577C0 (0x1403577C0) ---

// --- Function: sub_1403DFBE0 (0x1403DFBE0) ---
__int64 __fastcall sub_1403DFBE0(unsigned __int8 **a1, _QWORD *a2)
{
  unsigned __int8 *v2; // rax
  __int64 v3; // r8
  unsigned __int8 v4; // cl

  v2 = *a1;
  v3 = *a2 - (_QWORD)*a1;
  while ( 1 )
  {
    v4 = *v2;
    if ( *v2 != v2[v3] )
    {
      break;
    }
    ++v2;
    if ( !v4 )
    {
      return 0LL;
    }
  }
  return v4 < v2[v3] ? -1 : 1;
}

// --- End Function: sub_1403DFBE0 (0x1403DFBE0) ---

// --- Function: sub_140566BA0 (0x140566BA0) ---
char __fastcall sub_140566BA0(char a1)
{
  char n2; // al

  switch ( a1 )
  {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 84:
    case 85:
    case 86:
    case 87:
      n2 = 1;
      break;
    case 9:
    case 10:
      n2 = 2;
      break;
    case 11:
    case 12:
    case 13:
    case 14:
    case 16:
    case 17:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
      n2 = 3;
      break;
    case 15:
    case 18:
    case 19:
    case 65:
      n2 = 12;
      break;
    case 33:
    case 41:
    case 42:
    case 48:
    case 52:
    case 53:
    case 55:
    case 61:
    case 71:
    case 72:
      n2 = 26;
      break;
    case 34:
    case 69:
    case 96:
    case 97:
      n2 = 4;
      break;
    case 35:
    case 36:
    case 37:
    case 68:
      n2 = 5;
      break;
    case 38:
    case 77:
      n2 = 6;
      break;
    case 39:
      n2 = 7;
      break;
    case 40:
      n2 = 9;
      break;
    case 44:
    case 45:
    case 47:
    case 60:
    case 62:
    case 73:
    case 74:
      n2 = 10;
      break;
    case 49:
    case 50:
    case 76:
      n2 = 11;
      break;
    case 54:
      n2 = 22;
      break;
    case 56:
    case 57:
    case 59:
      n2 = 29;
      break;
    case 58:
    case 79:
    case 80:
      n2 = 13;
      break;
    case 63:
    case 75:
      n2 = 28;
      break;
    case 64:
    case 78:
      n2 = 24;
      break;
    case 66:
    case 67:
      n2 = 27;
      break;
    case 70:
      n2 = 30;
      break;
    case 82:
    case 83:
      n2 = 15;
      break;
    case 88:
    case 89:
      n2 = 25;
      break;
    case 90:
    case 91:
      n2 = 16;
      break;
    case 92:
      n2 = 17;
      break;
    case 93:
    case 94:
    case 95:
      n2 = 18;
      break;
    case 98:
    case 99:
      n2 = 19;
      break;
    case 100:
      n2 = 20;
      break;
    case 101:
    case 102:
      n2 = 21;
      break;
    case 103:
      n2 = 23;
      break;
    case 104:
      n2 = 31;
      break;
    case 105:
      n2 = 51;
      break;
    case 106:
      n2 = 52;
      break;
    case 107:
      n2 = 53;
      break;
    default:
      n2 = 0;
      break;
  }
  return n2;
}

// --- End Function: sub_140566BA0 (0x140566BA0) ---

// --- Function: sub_1417C3450 (0x1417C3450) ---
_QWORD *__fastcall sub_1417C3450(_QWORD *pExceptionObject)
{
  pExceptionObject[1] = "bad allocation";
  *pExceptionObject = off_147F343E8;
  return pExceptionObject;
}

// --- End Function: sub_1417C3450 (0x1417C3450) ---

// --- Function: sub_147220700 (0x147220700) ---
__int64 *__fastcall sub_147220700(__int64 **a1, const void **a2)
{
  __int64 *v2; // rdi
  __int64 v5; // rbx
  __int64 *v6; // rdi
  __int64 v7; // rsi
  __int128 v8; // xmm0
  __int128 v10; // [rsp+20h] [rbp-38h] BYREF

  v2 = *a1;
  DWORD2(v10) = 0;
  v5 = v2[1];
  *(_QWORD *)&v10 = v5;
  while ( !*(_BYTE *)(v5 + 25) )
  {
    *(_QWORD *)&v10 = v5;
    if ( (int)sub_1403DFBE0((unsigned __int8 **)(v5 + 32), a2) >= 0 )
    {
      v2 = (__int64 *)v5;
      DWORD2(v10) = 1;
      v5 = *(_QWORD *)v5;
    }
    else
    {
      v5 = *(_QWORD *)(v5 + 16);
      DWORD2(v10) = 0;
    }
  }
  if ( *((_BYTE *)v2 + 25) || (int)sub_1403DFBE0((unsigned __int8 **)a2, v2 + 4) < 0 )
  {
    if ( a1[1] == (__int64 *)0x492492492492492LL )
    {
      unknown_libname_7();
    }
    v6 = *a1;
    v7 = sub_1402A1E30(0x38uLL);
    sub_1403577C0((void **)(v7 + 32), a2);
    v8 = v10;
    *(_QWORD *)(v7 + 40) = 0LL;
    *(_QWORD *)(v7 + 48) = 0LL;
    *(_QWORD *)v7 = v6;
    *(_QWORD *)(v7 + 8) = v6;
    *(_QWORD *)(v7 + 16) = v6;
    *(_WORD *)(v7 + 24) = 0;
    v10 = v8;
    v2 = (__int64 *)sub_1402DE890(a1, (__int64)&v10, v7);
  }
  return v2 + 5;
}

// --- End Function: sub_147220700 (0x147220700) ---

// --- Function: sub_147273B30 (0x147273B30) ---
__int64 sub_147273B30()
{
  __int64 result; // rax

  result = *(_QWORD *)(*((_QWORD *)NtCurrentTeb()->ThreadLocalStoragePointer + (unsigned int)TlsIndex) + 3400LL);
  if ( result )
  {
    return *(unsigned __int8 *)(result + 1);
  }
  return result;
}

// --- End Function: sub_147273B30 (0x147273B30) ---

// --- Function: sub_1473755E0 (0x1473755E0) ---
void __fastcall sub_1473755E0(unsigned __int64 n0x6400000)
{
  ULONG_PTR Arguments[2]; // [rsp+20h] [rbp-C8h] BYREF
  char Buffer[160]; // [rsp+30h] [rbp-B8h] BYREF

  memset(Buffer, 0, sizeof(Buffer));
  sub_147349F80(Buffer, 0xA0uLL, n0x6400000);
  Arguments[0] = (ULONG_PTR)Buffer;
  RaiseException(0x2BADFF61u, 1u, 1u, Arguments);
}

// --- End Function: sub_1473755E0 (0x1473755E0) ---

// --- Function: sub_1473986B0 (0x1473986B0) ---
unsigned __int64 __fastcall sub_1473986B0(unsigned __int64 n0xE000, unsigned __int64 n0x10)
{
  return sub_1473986C0(n0xE000, n0x10);
}

// --- End Function: sub_1473986B0 (0x1473986B0) ---

// --- Function: sub_1473986C0 (0x1473986C0) ---
unsigned __int64 __fastcall sub_1473986C0(unsigned __int64 n0xE000, unsigned __int64 n0x10)
{
  unsigned __int64 n0xE000_1; // r11
  unsigned int v3; // r8d
  int n32; // eax
  unsigned int n32_1; // r8d
  __int64 v6; // r9
  __int64 v7; // rcx
  __int64 v8; // rax
  __int64 *v9; // r10
  __int64 v10; // r8
  __int64 v11; // rdi
  __int64 v12; // r11
  __int64 v13; // r8
  __int64 *v14; // rax
  __int64 v15; // rax
  unsigned __int64 v16; // r11
  unsigned __int64 result; // rax
  __int64 v18; // rcx
  _QWORD *v19; // r8
  _QWORD *v20; // r8

  n0xE000_1 = n0xE000;
  if ( n0x10 > 0x10 )
  {
    n0xE000_1 = ~(n0x10 - 1) & (n0x10 + n0xE000 - 1);
  }
  if ( n0xE000_1 > 0xE000 )
  {
    result = sub_147398850((__int64)&qword_1513BBF10, n0xE000_1);
  }
  else
  {
    _BitScanReverse(&v3, n0xE000_1 - 1);
    n32 = 32;
    n32_1 = v3 ^ 0x1F;
    if ( (_DWORD)n0xE000_1 != 1 )
    {
      n32 = n32_1;
    }
    v6 = 0;
    v7 = 0;
    v8 = (unsigned int)(32 - n32) - 8LL;
    if ( v8 >= 0 )
    {
      v7 = v8;
    }
    v9 = &qword_148A35270[3 * v7];
    LOBYTE(v6) = n0xE000_1 % *v9 == 0;
    v10 = n0xE000_1 / *v9 - v6;
    v11 = v10 + v9[1] - v9[2] / (unsigned __int64)*v9;
    v12 = *v9 * (v10 + 1);
    v13 = 16 * (v11 + 1) + *((_QWORD *)NtCurrentTeb()->ThreadLocalStoragePointer + (unsigned int)TlsIndex) + 3552;
    v14 = *(__int64 **)v13;
    if ( *(_QWORD *)v13 )
    {
      --*(_DWORD *)(v13 + 12);
      v18 = *v14;
      result = (unsigned __int64)v14 - v12 + 8;
      *(_QWORD *)v13 = v18;
    }
    else
    {
      v15 = sub_147399BF0(&qword_1513BBF20[4 * v11]);
      if ( v15 )
      {
        result = v15 - v16 + 8;
      }
      else
      {
        result = sub_147398A80((__int64)&qword_1513BBF10, v16, v11);
      }
    }
  }
  v19 = (_QWORD *)qword_1513BD1A0;
  if ( qword_1513BD1A0 )
  {
    while ( result < (unsigned __int64)v19 || result >= (unsigned __int64)v19 + v19[1] )
    {
      v19 = (_QWORD *)*v19;
      if ( !v19 )
      {
        goto LABEL_18;
      }
    }
  }
  else
  {
LABEL_18:
    v20 = (_QWORD *)qword_1513BD0A0;
    if ( qword_1513BD0A0 )
    {
      while ( result < (unsigned __int64)v20 || result >= (unsigned __int64)v20 + v20[1] )
      {
        v20 = (_QWORD *)*v20;
        if ( !v20 )
        {
          goto LABEL_22;
        }
      }
    }
    else
    {
LABEL_22:
      __debugbreak();
    }
  }
  return result;
}

// --- End Function: sub_1473986C0 (0x1473986C0) ---

// --- Function: sub_14739A8D0 (0x14739A8D0) ---
__int64 __fastcall sub_14739A8D0(unsigned __int64 n0x6400000)
{
  __int64 result; // rax
  _QWORD pExceptionObject[2]; // [rsp+30h] [rbp-68h] BYREF
  int n26880; // [rsp+40h] [rbp-58h] BYREF
  __int64 v5; // [rsp+44h] [rbp-54h]
  int v6; // [rsp+4Ch] [rbp-4Ch]
  __int64 v7; // [rsp+50h] [rbp-48h]
  unsigned __int64 v8; // [rsp+58h] [rbp-40h]
  __int64 v9; // [rsp+60h] [rbp-38h]
  __int64 v10; // [rsp+68h] [rbp-30h]

  if ( byte_1513BD53C == 1 )
  {
    sub_1417C3450(pExceptionObject);
    throw (stdext::bad_alloc *)pExceptionObject;
  }
  byte_14981D4C4 = 1;
  ::n0x6400000 = n0x6400000;
  if ( n0x6400000 > 0x6400000 )
  {
    sub_1473755E0(n0x6400000);
  }
  n26880 = 26880;
  v5 = 0;
  v6 = 0;
  v8 = 0;
  v9 = 0;
  v10 = 0;
  v7 = 1;
  qword_149818EA0(
    &n26880,
    0,
    &p_p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp,
    &p_p_W__p4_src_CryEngine_Code_SDKs_Optick_1_3_1_src_optick_core_cpp,
    0);
  sub_1473755E0(n0x6400000);
  v8 = __rdtsc();
  qword_149818EA8(&n26880);
  return result;
}

// --- End Function: sub_14739A8D0 (0x14739A8D0) ---

// --- Function: sub_14739AFC0 (0x14739AFC0) ---
__int64 __fastcall sub_14739AFC0(unsigned __int64 n0x6400000, struct _exception *n0x10)
{
  char v4; // al
  __int64 v5; // rax
  __int64 result; // rax

  if ( n0x6400000 )
  {
    v4 = sub_147273B30();
    sub_140566BA0(v4);
    v5 = AK::MemoryMgr::StopProfileThreadUsage(n0x10);
    result = sub_1473986B0(v5 + n0x6400000, (unsigned __int64)n0x10);
    if ( result )
    {
      return result;
    }
    sub_14739A8D0(n0x6400000);
  }
  return 0LL;
}

// --- End Function: sub_14739AFC0 (0x14739AFC0) ---

// --- Function: ?_Xlength_error@std@@YAXPEBD@Z (0x147DC691E) ---
// attributes: thunk
void __fastcall __noreturn std::_Xlength_error(const char *a1)
{
  __imp_?_Xlength_error@std@@YAXPEBD@Z(a1);
}

// --- End Function: ?_Xlength_error@std@@YAXPEBD@Z (0x147DC691E) ---

// --- Function: memcpy (0x147E162BB) ---
// attributes: thunk
void *__cdecl memcpy(void *a1, const void *Src, size_t Size)
{
  return __imp_memcpy(a1, Src, Size);
}

// --- End Function: memcpy (0x147E162BB) ---

// --- Function: _CxxThrowException (0x147E1630F) ---
// attributes: thunk
void __stdcall __noreturn CxxThrowException(void *pExceptionObject, _ThrowInfo *pThrowInfo)
{
  _CxxThrowException(pExceptionObject, pThrowInfo);
}

// --- End Function: _CxxThrowException (0x147E1630F) ---

